### ISSUE TITLE
Move the daemon commands under `incus admin`

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#10]
Rather than have users invoke sub-commands on the daemon, lets move all of those over to a new `incus admin` sub-command in the client. All daemon commands have been API based for years, so there's no real reason for them to be under a different binary and having to keep both the daemon and client in the PATH has caused no end of confusion over the years.

With this change in place, the `incusd` binary should be kept out of PATH, only leaving `incus` to be user visible.

**Comment by cyphar** [comment]
This really would make things a lot nicer. Nee-`lxd init` was always a weird command to deal with. Is there a nice way to move the daemon configuration stuff from `inc config` to `inc admin` as well? I always felt it was strange that daemon and workload configuration was done through the same subcommand. Or would the plan just be to move the daemon subcommands?

**Comment by stgraber** [comment]
Hmm, I didn't think of trying to undo the `inc config` for both instance and server settings but that's something that may be worth thinking about.

My current plan was to make `inc admin` restricted to local use only, so no support for remotes or anything at that level, effectively matching what we had with the `lxd XYZ` commands as those may rely on internal unix-only APIs.

Maybe we should have a separate `inc server` sub-command with the usual set of `set/unset/show/edit/info`.
Essentially moving the server config logic over to that and keeping the top-level commands focused on instances.

**Comment by sharathsivakumar** [comment]
@stgraber I would like to work on this. Would it be possible to assign this to me?

**Comment by stgraber** [comment]
For that one, I think I'd recommend:
 - Send an initial PR moving `incusd init` to `incus admin init`
 - Then do `incusd cluster` to `incus admin cluster`
 - Then remove `import` from `incusd` and move `recover` to `incus admin recover`
 - Finally move `activateifneeded`, `shutdown` and `waitready`

That should leave us with nothing other than the boilerplate `help` and `version` commands as well as the hidden internal subcommands (mostly `forkXYZ`).

**Comment by sharathsivakumar** [comment]
Thanks @stgraber. Those recommendations help a lot.

**Comment by stgraber** [comment]
@sharathsivakumar how's that going?

**Comment by sharathsivakumar** [comment]
@stgraber Sorry was sick for the last few weeks. I am back to work this week. Looking to get the first PR out before the end of this week. Hope that's fine.

**Comment by stgraber** [comment]
Sounds good!

**Comment by sharathsivakumar** [comment]
- [ ] `incusd init` to `incus admin init` 
- [ ] `incusd cluster `to `incus admin cluster`

**Comment by stgraber** [comment]
Hey @sharathsivakumar, this is starting to become a bit more of a blocker than it once was, so I'm planning on spending some time tomorrow in my weekly live stream going through a bunch of those so we can close this issue ahead of Incus 0.1.

Let me know if you have some existing partial code, or better, open a draft PR with anything you have and I'll take it from there!

**Comment by sharathsivakumar** [comment]
@stgraber I have partial code for recover and sql. I will create a few PRs for all those I worked and you can take it from there.

**Comment by stgraber** [comment]
@sharathsivakumar thanks!

**Comment by stgraber** [comment]
Thanks to @sharathsivakumar we now have everything we can move, moved to the `incus admin` space.

I'll now take this over and send a small follow-up to:
 - Tidy up the help of `incusd`
 - Introduce an `incus admin cluster` sub-command which attempts to redirect to `incusd admin cluster` or tells the user that cluster recovery must be done through `incusd`
 - Do a quick look over the new `admin XYZ` commands to make sure they're in line with other client commands, thinking specifically about getting all their strings included in the translation template.

And that will be a wrap on that one.
