### ISSUE TITLE
Issue locating socket while joining cluster

### ISSUE THREAD

**Issue by amayer5125** [lxc/incus#1013]
# Required information

 * Distribution: Rocky Linux
 * Distribution version: 9.4
 * The output of "incus info" or if that fails:
   * Kernel version: 5.14.0-427.22.1.el9_4.x86_64
   * LXC version: 4.0.12
   * Incus version: 6.2
   * Storage backend in use: dir

# Issue description

I have a cluster leader configured. I am trying to join a cluster member. When I run `incus --force-local admin init --preseed` I get the following error:

> Error: Failed to join cluster: Failed to connect to local server: Get "http://unix.socket/1.0": dial unix /var/lib/incus/unix.socket: connect: no such file or directory

The socket is not located in /var/lib/incus, but is in /run/incus.

# Steps to reproduce

On a Fedora or RHEL based system:

 1. Configure cluster leader with dir storage and bridge network
 2. Create a token for the cluster member on the cluster leader via `incus cluster add <member hostname>`
 3. Attempt to join the cluster
     - I don't believe the method of joining the cluster matters (interactive vs preseed)

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`incus info NAME --show-log`)
 - [ ] Container configuration (`incus config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/incus/incusd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the issue)

**Comment by stgraber** [comment]
As mentioned in the PR, I wonder if this isn't just about a bad systemd setup.

It sounds like you have an `incus.socket` which points to `/run/incus/unix.socket` but a `incus.service` which doesn't set `INCUS_SOCKET` to `/run/incus/unix.socket`. So when socket activated, Incus assumes the wrong location for the socket, causing this issue and potentially a number of other more subtle issues.

**Comment by amayer5125** [comment]
You are probably correct. I am using the [Fedora `incus.service` file](https://src.fedoraproject.org/rpms/incus/blob/rawhide/f/incus-user.service). It looks like there is [a pull request](https://src.fedoraproject.org/rpms/incus/pull-request/2) open to add the `INCUS_SOCKET` environment variable.

**Comment by stgraber** [comment]
Looks good, hopefully the package gets fixed soon!
