### ISSUE TITLE
Enhancement: Unify <list>,<ls> sub-commands parameters

### ISSUE THREAD

**Issue by tregubovav-dev** [lxc/incus#1026]
# Issue
Incus provides `list` sub-commands in multiple commands. Some of them have advanced options like `--format` and `--columns`, but some does not have such options. Unified set of options significantly simplifies automation scripts development.
Below is subset of commands with different options availability:
* `incus list`, `incus cluster list`, `incus storage list`, `incus network list`, etc. provide both  `--format` and `--columns` options
* `incus cluster list-tokens`, `incus cluster group list`, `incus snapshot list`, `incus storage bucket list` provides the only `--format` option.
* `incus admin cluster list-database` has no options. Even it provides single column output `--format` option may be useful.

There were many `list'-like commands received `--format` and `--columns` options since forking from the LXD. I would appreciate it if all remaining commands could receive these options.

## P.S.
Two more possible enhancements:
* header-less format output would be useful at least for `compact` format option. For example: `--format compact-no-header`. It could be used with `shell` commands or scripts like in example below:
```
for inst in $(incus list <name pattern> -f compact-no-header -c n) do; incus exec $inst -- <do something in the instance>; done
```
* `incus top` could be enhances with `--format` and `--columns` options and no-waiting for user input.

**Comment by stgraber** [comment]
I've split up things into a couple more issues and I've got the rest sorted out in a PR.
