### ISSUE TITLE
Add support for `--column` to all list commands

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#1027]
Splitting this one out of #1026.

The full list of commands that currently do not support a `--columns` option are:

- [x] incus image alias list
- [x] incus cluster list-tokens
- [x] incus cluster group list
- [x] incus config template list
- [x] incus config trust list-tokens
- [x] incus image alias list
- [x] incus network list-leases
- [x] incus network list-allocations
- [x] incus network forward list
- [x] incus network integration list
- [x] incus network load-balancer list
- [x] incus network peer list
- [x] incus network zone list
- [x] incus operation list
- [x] incus remote list
- [x] incus snapshot list
- [x] incus storage bucket list
- [x] incus storage bucket key list

**Comment by HassanAlsamahi** [comment]
I'd like to work on this. Can it be assigned to me?

**Comment by HassanAlsamahi** [comment]
I would like to continue working on this issue, can it be assigned to me? Thanks.

**Comment by stgraber** [comment]
Done!

**Comment by HassanAlsamahi** [comment]
While going through them. I noticed that the long description is not consistent across all commands. 

For example:
```
incus storage list -h

Description:
  List available storage pools

  Default column layout: nDSdus

  == Columns ==
  The -c option takes a comma separated list of arguments that control
  which instance attributes to output when displaying in table or csv
  format.

  Column arguments are either pre-defined shorthand chars (see below),
  or (extended) config keys.

  Commas between consecutive shorthand chars are optional.

  Pre-defined column shorthand chars:
    n - Name
    D - Driver
    d - Description
    S - Source
    u - used by
    s - state
```

VS

```
incus network list -h
Description:
  List available networks

  The -c option takes a (optionally comma-separated) list of arguments
  that control which image attributes to output when displaying in table
  or csv format.

  Default column layout is: ntm46dus
  Column shorthand chars:
  4 - IPv4 address
  6 - IPv6 address
  d - Description
  e - Project name
  m - Managed status
  n - Network Interface Name
  s - State
  t - Interface type
  u - Used by (count)
```

Also, some of them are misleading. In network list it says "control which image attributes" instead of "control which network attributes". I fell for that myself in some of the previous PRs.

I can fix that indeed, but should I open PRs directly, or should an issue be open first for fixing the long descriptions?

**Comment by stgraber** [comment]
Feel free to open PRs directly to fix those.

I suspect we did a bunch of copy/pasting over the years :)

**Comment by HassanAlsamahi** [comment]
Okay. Thanks.

**Comment by HassanAlsamahi** [comment]
Running `incus config template list <instance-name>` returns only one column with me:
```
root@incus-dev:~# incus config template list electric-snapper 
+--------------+
|   FILENAME   |
+--------------+
| hostname.tpl |
+--------------+
| hosts.tpl    |
+--------------+
```

Is there a case that it returns multiple columns? If not, is column selection still needed here?

**Comment by stgraber** [comment]
@HassanAlsamahi yeah, we can skip that one.
