### ISSUE TITLE
Archlinux wrong path to OVMF

### ISSUE THREAD

**Issue by Nerksal** [lxc/incus#1030]
https://github.com/lxc/incus/blob/65ac8ef7df790e56b941b94b02b5e7b2ee1792e8/internal/server/instance/drivers/edk2/driver_edk2.go#L38C12-L38C13

In archlinux default path for ovmf files is /usr/share/OVMF/x64/

`diff --git a/internal/server/instance/drivers/edk2/driver_edk2.go b/internal/server/instance/drivers/edk2/driver_edk2.go
index bdbabca44..a7e25e84b 100644
--- a/internal/server/instance/drivers/edk2/driver_edk2.go
+++ b/internal/server/instance/drivers/edk2/driver_edk2.go
@@ -35,7 +35,7 @@ const (
 
 var architectureInstallations = map[int][]Installation{
        osarch.ARCH_64BIT_INTEL_X86: {{
-               Path: "/usr/share/OVMF",
+               Path: "/usr/share/OVMF/x64/",
                Usage: map[FirmwareUsage][]FirmwarePair{
                        GENERIC: {
                                {Code: "OVMF_CODE.4MB.fd", Vars: "OVMF_VARS.4MB.fd"},`

**Comment by project0** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/incus/-/issues/6

**Comment by stgraber** [comment]
Can you show `ls -lh /usr/share/OVMF/x64/` so we can see what other firmware files are in there.
Also, it'd be useful to know what the path is on arm64 as it's probably not `/usr/share/OVMF/x64` on that architecture.

**Comment by baioc** [comment]
@stgraber I'm not the one you asked this to, but also running arch:
```
$ ls /usr/share/OVMF/x64
MICROVM.4m.fd  OVMF_CODE.4m.fd      OVMF_CODE.secboot.4m.fd
MICROVM.fd     OVMF_CODE.csm.4m.fd  OVMF_CODE.secboot.fd
OVMF.4m.fd     OVMF_CODE.csm.fd     OVMF_VARS.4m.fd
OVMF.fd        OVMF_CODE.fd         OVMF_VARS.fd
```

The Arch maintainers are already aware of [this issue](https://gitlab.archlinux.org/archlinux/packaging/packages/incus/-/issues/6) with Incus 6.3 and have [a fix](https://gitlab.archlinux.org/archlinux/packaging/packages/incus/-/merge_requests/4) waiting to be reviewed and merged, but for those who don't want to wait the manual fix is:
- `# systemctl edit --full incus.service`
  - Change `Environment=INCUS_OVMF_PATH=...` to `Environment=INCUS_EDK2_PATH=...`
- `# systemctl restart incus.service`

**Comment by stgraber** [comment]
@baioc can you show a full `ls -lh` for that folder so we can see what's a symlink and what's not?

**Comment by baioc** [comment]
No symlinks in the x64 folder, but the parent `/usr/share/OVMF` itself is a symlink:
```
$ ls -lh /usr/share/OVMF/x64/
total 29M
-rw-r--r-- 1 root root 4.0M 2023-11-24 11:22 MICROVM.4m.fd
-rw-r--r-- 1 root root 2.0M 2023-11-24 11:22 MICROVM.fd
-rw-r--r-- 1 root root 4.0M 2023-11-24 11:22 OVMF.4m.fd
-rw-r--r-- 1 root root 2.0M 2023-11-24 11:22 OVMF.fd
-rw-r--r-- 1 root root 3.5M 2023-11-24 11:22 OVMF_CODE.4m.fd
-rw-r--r-- 1 root root 3.5M 2023-11-24 11:22 OVMF_CODE.csm.4m.fd
-rw-r--r-- 1 root root 1.9M 2023-11-24 11:22 OVMF_CODE.csm.fd
-rw-r--r-- 1 root root 1.9M 2023-11-24 11:22 OVMF_CODE.fd
-rw-r--r-- 1 root root 3.5M 2023-11-24 11:22 OVMF_CODE.secboot.4m.fd
-rw-r--r-- 1 root root 1.9M 2023-11-24 11:22 OVMF_CODE.secboot.fd
-rw-r--r-- 1 root root 528K 2023-11-24 11:22 OVMF_VARS.4m.fd
-rw-r--r-- 1 root root 128K 2023-11-24 11:22 OVMF_VARS.fd

$ ls -lh /usr/share/OVMF
lrwxrwxrwx 1 root root 15 2023-11-24 11:22 /usr/share/ovmf -> /usr/share/edk2

$ ls -lh /usr/share/ovmf
lrwxrwxrwx 1 root root 15 2023-11-24 11:22 /usr/share/ovmf -> /usr/share/edk2
```

**Comment by stgraber** [comment]
https://github.com/lxc/incus/pull/1033 should handle this, at least on x86_64 without having to use the env variable override.
