### ISSUE TITLE
Fingerprint mismatch transferring OCI images between cluster members

### ISSUE THREAD

**Issue by elburb** [lxc/incus#1053]
# Required information

 * Distribution: debian
 * Distribution version: 12
   * Kernel version: 6.9.7-zabbly+
   * LXC version:
   * Incus version: 6.3
   * Storage backend in use: zfs

# Issue description

Attempting to launch an OCI image on two different members of an incus cluster fails with a fingerprint mismatch when attempting to copy the OCI image between the cluster members.

If the image is deleted and re-downloaded the container can be start as normal.

# Steps to reproduce

launch an OCI image on one cluster member:

```sh
$ incus launch docker:hello-world --console --ephemeral --target server1
Launching the instance
Instance name is: relaxing-doe                       

The instance you are starting doesn't have any network attached to it.
  To create a new network, use: incus network create
  To attach a network to an instance, use: incus network attach


Hello from Docker!
This message shows that your installation appears to be working correctly.

[ and so on ]
```

then launch the same image on another cluster member:

```sh
 $ incus launch docker:hello-world --console --ephemeral --target server2
Launching the instance
Error: Failed instance creation: Failed transferring image "1408fec50309afee38f3535383f5b09419e6dc0925bc69891e79d84cc4cdcec6" from "[xxxxxxxxx]:8443": Image fingerprint doesn't match. Got 138b4269117bd6831e3c9f0f01a94c9ed90e2dcd4f22e052b8bf9251aa2ddd31 expected 1408fec50309afee38f3535383f5b09419e6dc0925bc69891e79d84cc4cdcec6
```

```sh
$ incus image list
...
|            | 1408fec50309 | no     | docker.io/library/hello-world (OCI)      | x86_64       | CONTAINER       | 0.00MiB   | 2024/07/26 21:35 BST |
...
```

**Comment by stgraber** [comment]
This has actually been fixed on Friday :)

https://github.com/lxc/incus/commit/951fd0c6b429b50685c33cf95429ef7fe3dc038c
