### ISSUE TITLE
Include documentation for incus-agent installation on VMs

### ISSUE THREAD

**Issue by victoitor** [lxc/incus#1055]
Currently, I don't think the documentation has any information on how to install the incus-agent on VMs which were not obtained through the image server. Such documentation can be found on the forum, but it should be usual enough to have it included in the official docs.

**Comment by victoitor** [comment]
Btw, I mention something like this:

```
mount -t 9p config /mnt
cd /mnt
./install.sh
```

**Comment by simos** [comment]
In which location in the `doc/` should that information get added?

**Comment by victoitor** [comment]
This is a great question, but not one I have an answer to. I would guess some place inside the instances tab.
To contribute to this discussion, I searched for places in thich the incus-agent is mentioned and I found the following links.
* https://linuxcontainers.org/incus/docs/main/howto/instances_access_files/
* https://linuxcontainers.org/incus/docs/main/howto/instances_console/#access-the-graphical-console-for-virtual-machines
* https://linuxcontainers.org/incus/docs/main/instance-exec/

It is also mentioned on the following link, but I'm not sure it's related to learning how to install it: https://linuxcontainers.org/incus/docs/main/cloud-init/#cloud-init-and-virtual-machines

Maybe it would make sense on a new submenu inside the instances menu and it should be linked from those places I provided.

**Comment by simos** [comment]
There are four types of documentation, and two of them are _howto_ and _explanation_. 

Most likely this should be a _howto_ document, which means it would have a title like _How to enable manually the incus-agent in a VM_.

An _explanation_ document would explain the background with incus-agent, why it's needed, how it is provided automatically in the most common cases, and why you need to setup manually in some specific cases.

**Comment by stgraber** [comment]
@simos I'd add it to the `instances_create` howto as it already covers creating instances from ISO images and manually adding the agent is the logical follow-up step to that.

**Comment by simos** [comment]
I have added the text here, https://github.com/lxc/incus/pull/1067
