### ISSUE TITLE
Documentation needs correction

### ISSUE THREAD

**Issue by alex14641** [lxc/incus#1057]
# Required information

 * Distribution: Slackware
 * Distribution version: current
 * The output of "incus info" or if that fails:
   * Kernel version: 6.6.41
   * LXC version: 6.0.1
   * Incus version 6.0.1
   * Storage backend in use: lvm

# Issue description

In the "Configure instances" section of the "Getting Started" chapter, the command for starting a limited instance is wrong. It is currently
`incus launch images:ubuntu/22.04 limited --config limits.cpu=1 --config limits.memory=192MiB`
The problem is that limits.cpu and limits.memory only work for virtual machines. The command should be
`incus launch images:ubuntu/22.04 limited --vm --config limits.cpu=1 --config limits.memory=512MiB`
Increasing the memory size is necessary because 128MiB is not enough to start a VM.

# Steps to reproduce

 N/A

# Information to attach

 N/A

**Comment by stgraber** [comment]
That's incorrect, limits work with containers and that example is a valid one for a container.
