### ISSUE TITLE
Memory limits ignored for instances, even after setting  security.syscalls.intercept.sysinfo=true

### ISSUE THREAD

**Issue by alex14641** [lxc/incus#1069]
# Required information

 * Distribution:
 * Distribution version:
 * The output of "incus info" or if that fails:
   * Kernel version: 6.6.43
   * LXC version:6.0.1
   * Incus version:6.0.1
   * Storage backend in use:btrfs

# Issue description

Memory limits not being displayed.
`incus launch images:ubuntu/22.04 limited --config limits.cpu=1 --config limits.memory=192MiB`
`incus exec limited -- free -m`
`incus-env incus exec limited -- free -h`
`               total        used        free      shared  buff/cache   available`
`Mem:            31Gi       3.1Gi        20Gi        26Mi       8.0Gi        27Gi`
`Swap:           33Gi          0B        33Gi`
`incus config set limited security.syscalls.intercept.sysinfo=true`
`incus-env incus exec limited -- free -h`
`               total        used        free      shared  buff/cache   available`
`Mem:            31Gi       3.1Gi        20Gi        26Mi       8.0Gi        27Gi`
`Swap:           33Gi          0B        33Gi`

I have stopped and restarted the instance; same result.

**Comment by stgraber** [comment]
Please provide the full `incus info` output and also detail how Incus was installed and on what Linux distribution.

**Comment by alex14641** [comment]
incus info: 
[incus-info.txt](https://github.com/user-attachments/files/16470276/incus-info.txt)

Incus was installed from source following the instructions in the "From source: Install" section of the "Install Incus" chapter.

**Comment by stgraber** [comment]
Did you also install and run LXCFS?

**Comment by alex14641** [comment]
Running LXCFS fixed the issue. Thank you for your help.
