### ISSUE TITLE
[ceph] volume attach fails when ceph.conf is symlink

### ISSUE THREAD

**Issue by slapcat** [lxc/incus#1076]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "incus info" or if that fails:
   * Kernel version: 5.15.0-117-generic
   * LXC version: 6.2
   * Incus version: 6.2 
   * Storage backend in use: `ceph` (RBD)

# Issue description

After adding a new `ceph` (RBD) storage pool, I can create storage volumes, but not attach them to instances:
```
Error: Failed to start device "sunbeam-0": Failed to call monitor hook for block device: Failed adding block device for disk device "sunbeam-0": Failed adding block device: error reading conf file /etc/ceph/ceph.conf: No such file or directory
```

Pool creation and volume creation both succeeded previously without error. The issue seems to be caused by /etc/ceph/ceph.conf being a symlink. When replaced with a regular file, the attach works. It would be nice if incus could follow the symlink during the attach operation. Presumably it was able to follow it when adding the storage pool and creating the volume.

# Steps to reproduce

1. Ensure ceph.conf is a symlink:
 ```
# ls -l /etc/ceph/ceph.conf 
lrwxrwxrwx 1 root root 42 Jul  7 17:02 /etc/ceph/ceph.conf -> /var/snap/microceph/current/conf/ceph.conf
```
2. Create pool:
```
# incus storage create ceph-rbd ceph 
Storage pool ceph-rbd created
```

3. Create volume:
```
# incus storage volume create --type block ceph-rbd sunbeam-0 size=50GiB
Storage volume sunbeam-0 created
```

4. Attach volume:
```
# incus storage volume attach ceph-rbd sunbeam-0 sunbeam
Error: Failed to start device "sunbeam-0": Failed to call monitor hook for block device: Failed adding block device for disk device "sunbeam-0": Failed adding block device: error reading conf file /etc/ceph/ceph.conf: No such file or directory
```

# Workaround

Make ceph.conf a regular file instead of symlink.

**Comment by stgraber** [comment]
Got it reproduced
