### ISSUE TITLE
Add local caching for remote images list

### ISSUE THREAD

**Issue by togawa-sakiko** [lxc/incus#1093]
Currently, every attempt to autocomplete remote images (e.g., the default `images:`) in the CLI will cause Incus to fetch and parse a whole brand new list from the remote server, resulting in a high latency (about 3 seconds) and blocking the CLI.

Such high real-time requirement for the list seems unnecessary. Maybe we can maintain a local cache of the list and update it at a minute level.

**Comment by stgraber** [comment]
Should be pretty easy as we already do that on the server side and have both `CachePath` and `CacheExpiry` that can be set in the connection arguments to handle it.

We'd just want to be careful to use the correct path for this, possibly limiting it just to Linux first and expanding as we learn the correct path on other platforms.
