### ISSUE TITLE
Add ability to automatically restart failed instances

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#1096]
This is likely most useful for OCI containers as VMs and system containers rarely exit as part of normal operation.

My current idea for this one is to add a `boot.autorestart` config key which would automatically restart an instance when the user didn't request it be shut down.

We'll likely want to evolve this to only restart when getting a non-zero exit code, but currently LXC doesn't provide us with that information, so it's going to have to be all or nothing.

We should put a counter though and give up after 10 restarts within a 1 minute period.

**Comment by matjazp** [comment]
It would be useful if this is implemented similar to K8s Pod restart policy, at least for OCI app containers:

> After containers in a Pod exit, the kubelet restarts them with an exponential backoff delay (10s, 20s, 40s, …), that is capped at 300 seconds (5 minutes). Once a container has executed for 10 minutes without any problems, the kubelet resets the restart backoff timer for that container.

https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy
