### ISSUE TITLE
No cleanup of /var/lib/incus/users/<uid> can lead to missing user project

### ISSUE THREAD

**Issue by decentral1se** [lxc/incus#1149]
# Required information

 * Distribution: Debian
 * Distribution version: 12
 * The output of "incus info" or if that fails:
   * Kernel version: 6.1.0-23-amd64
   * LXC version: 5.0.2
   * Incus version: 6.0.1
   * Storage backend in use: dir

# Issue description

I ran into a situation in my testing where I creating/deleting/re-creating a system user, adding them to the `incus` group and creating instances under their specific project.

On deletion, I deleted also the project and project-specific bridge network. When I re-created the user, it inherited the same uid. No project was created and I can't create instances.

It appears to be a result of this check:

https://github.com/lxc/incus/blob/cdc41a991b1d796ff665996aa3e7aed4c5d49d46/cmd/incus-user/proxy.go#L83-L91

The `/var/lib/incus/users/<uid>` is not cleaned up when the Project is deleted. I assume `incus` can't know what happened to the system user at this point. However, it does lead to an inconsistency when cleaning up users and re-creating them later on.

Should this check be extended to ensure that the project exists if the `/var/lib/incus/users/<uid>` also exists?

# Steps to reproduce

 1. Create a system user
 2. Add user to `incus` group
 3. Run `incus project list` as user, confirm project created
 4. Delete system user, project & project network bridge
 5. Re-create user, ensure same uid
 6. Run `incus project list`, no project is created

# Information to attach

N/A

**Comment by stgraber** [comment]
> Should this check be extended to ensure that the project exists if the `/var/lib/incus/users/<uid>` also exists?

Yeah, but to avoid constantly checking for the project existence, we should probably have `incus-user` pull a list of projects at startup time and then keep that updated by watching for `project-created` and `project-deleted` events.

**Comment by Pushkarmondal** [comment]
Hey @stgraber can I work on this?

**Comment by stgraber** [comment]
Sure! I assigned it to you now.

**Comment by Pushkarmondal** [comment]
@stgraber can you please tell how can I work on this?

**Comment by Pushkarmondal** [comment]
Its my first time to contribute to open source project and I will try my best to do this work.

**Comment by stgraber** [comment]
The event tracking part would be nice and fancy, but to take care of this issue, I think all we really need to do is:
 - Add a projectNames global variable (`[]string`)
 - At startup, after the `Validate the configuration` step in `main_daemon.go`, call `client.GetProjectNames()` to get the project list and put it in `projectNames`
 - In `server.go` remove the `GetProjectNames` call and instead use the new `projectNames` variable for that.
 - In the same function, right after the `CreateProject` call, append the new project name to the `projectNames` variable
 - In `proxy.go`, change the `Check if the user was setup` logic to not only check for the path but also check if the project exists by checking if it is in the list of projects (`projectNames`).
 - Back in `server.go`, you need to make the function safe to run again if the files already exist but the project doesn't. I suspect you'll need to:
   - Skip MkdirAll and certificate creation if userPath already exists.
   - Check if the certificate already exists in the trust store (`GetCertificates`) and if it does, then skip trying to add it.
   - Move the CreateNetwork and UpdateProfile logic to right after the CreateProject logic (within the if statement) so those don't run if the project already exists.

**Comment by Pushkarmondal** [comment]
Thanks @stgraber

**Comment by Pushkarmondal** [comment]
hey @stgraber in which file I have to declare ([]string)
is this on main_daemon.go?

**Comment by stgraber** [comment]
Yeah, I'd set that at the top of main_daemon.go

**Comment by Pushkarmondal** [comment]
Hey @stgraber  how to test my changes?

**Comment by stgraber** [comment]
Easiest is to build `incus-user` and then replace the current binary at `/opt/incus/bin/incus-user`.

Once it's in place, you should be able to test that it works by first creating a local user and making it a member of the `incus` group, then get a shell as that user and run `incus project list`, you should see it get a new project name `user-1001` (or whatever the UID is).

You can then reproduce the issue by doing (as root or a user in `incus-admin`), `incus project delete -f user-1001`, this will fully delete the project but not delete the certificate used for the project.

After that, you can try running `incus project list` again as the test user, that should kick in the creation of the `user-1001` project again and then list it.

**Comment by stgraber** [comment]
Hi @Pushkarmondal, how is it going with this one?

That issue is targeted for Incus 6.5 which is to be released later tomorrow.
Any chance you can push what you have in a draft PR? Then I can take a look and tweak anything that's missing.

**Comment by Pushkarmondal** [comment]
Yes yes I am working on that.

**Comment by stgraber** [comment]
Sorry, I'm about to release Incus 6.5 and I'm not seeing any copy of your work as a draft PR or even on your own Github. As a result I'm now quickly doing the fix needed for this issue myself.

Hopefully this didn't cause you to waste too much of your time and you still found this to be useful and may consider looking into some of our other easy issues.
