### ISSUE TITLE
After a rolling reboot, load-balancer prefixes (/32) are not advertised

### ISSUE THREAD

**Issue by trunet** [lxc/incus#1188]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "incus info" or if that fails:
   * Kernel version: 6.8.0-40-generic
   * LXC version: 6.0.1
   * Incus version: 6.4
   * Storage backend in use: ceph

# Issue description

After a rolling restart of my incus cluster, it fails to advertise its load-balancers /32. I could not see them `incus query /internal/testing/bgp`. However if I create one LB it triggers a refresh somehow and bring all of them back. This needs to be done for each OVN to refresh its LBs.

```
incus network load-balancer create ovn-mystack 10.[REDACTED]
incus network load-balancer delete ovn-mystack 10.[REDACTED]
```

# Steps to reproduce

 1. Rolling reboot all servers
 2. LBs are not reacheable

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`incus info NAME --show-log`)
 - [ ] Container configuration (`incus config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/incus/incusd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the issue)

**Comment by stgraber** [comment]
Got the issue reproduced here

**Comment by stgraber** [comment]
Trivial fix...
