### ISSUE TITLE
Add support to activate LVM snapshot

### ISSUE THREAD

**Issue by skyxx** [lxc/incus#1216]
# Request description
Hi, it will be nice to add support activate + mount existing LVM snapshots for storage volumes and containers.

When using LVM storage driver, created snapshots are not accesible as LV is not accesible and not mounted.
Only path `/var/lib/incus/storage-pools/<pool_name>/<type>-snapshots/default_<volume_name>/<snapshot_name>` is created but no data accessible.

When using BTRFS storage driver after creating snapshot data from it are available automaticaly.
`/var/lib/incus/storage-pools/<pool_name>/<type>-snapshots/default_<volume_name>/<snapshot_name>`

So something like this will be nice:
`incus snapshot activate <instance> <snapshot_name>`
`incus snapshot deactivate <instance> <snapshot_name>`

`incus storage volume snapshot activate <pool_name> <volume_name> <snapshot_name>`
`incus storage volume snapshot deactivate <pool_name> <volume_name> <snapshot_name>`

**Comment by stgraber** [comment]
We're definitely not going to be doing that. In general we never want anyone to directly access files through /var/lib/incus and we definitely will not be adding a user facing API to trigger more mounts happening in there.

For a proper way to access snapshot data, we have: https://github.com/lxc/incus/issues/1174
