### ISSUE TITLE
Addition of helper functions in the QEMU scriptlet

### ISSUE THREAD

**Issue by bensmrs** [lxc/incus#1226]
Hi!
I'm making good progress with my black magic operations to get macOS working, thanks to the new QEMU scriptlet.
I’m finding myself defining plenty of functions like `qom_get`, `qom_set`,… which are critical to me. Would it be interesting to have them directly available to the scriptlets?
I know it will only serve 5 to 10 people, but if that sounds good to you, I’ll add them to the Incus codebase.

**Comment by stgraber** [comment]
Yeah, that should be fine to add a few of the most common ones as exported functions for this scriptlet.
