### ISSUE TITLE
cannot mount proc read-only

### ISSUE THREAD

**Issue by itviewer** [lxc/incus#1238]
I recently encountered a similar problem as LXD,
https://discourse.ubuntu.com/t/mount-root-proc-cannot-mount-proc-read-only-with-lxd-5-21-2-22f93f4-from-snap/47533

And it was fixed by https://github.com/canonical/lxd/pull/13997

I wonder how Incus handles this issue.

**Comment by stgraber** [comment]
Please only file issues when you actually know there is a problem :)

**Comment by stgraber** [comment]
```
stgraber@dakara:~$ incus launch images:ubuntu/24.04 u1
Launching u1
stgraber@dakara:~$ incus exec u1 bash              
root@u1:~# mkdir ~/proc
root@u1:~# mount -t proc proc ~/proc/
root@u1:~# 
```

**Comment by stgraber** [comment]
Okay, we'll take a look at Ubuntu 24.04 to see what's going.

AppArmor mount rules are getting very frustrating so we may end up fixing this by just not longer using the feature at all.
