### ISSUE TITLE
[lxd-to-incus] Support migrating clusters

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#128]
Currently `lxd-to-incus` refuses to migrate clusters.
That's because there's a fair bit more synchronization involved with migrating a cluster as opposed to a standalone system.

For clusters, we'll need to:
 - Confirm that all cluster members are currently online
 - Show the list of machines that will need to be migrated
 - Have the user confirm that they wish to migrate their cluster
 - Generate a single database patch to be run by the initial migrated server
 - Provide a command line flag to `lxd-to-incus` for the remaining servers which will bypass all validation and just do the data migration. This is needed as once we start shutting down LXD, we won't be able to talk to it again from the remaining servers.

**Comment by sharathsivakumar** [comment]
@stgraber I would like to work on this.

**Comment by stgraber** [comment]
Cool, assigned it to you!

**Comment by stgraber** [comment]
@sharathsivakumar any luck with this one?

I need to migrate a cluster from LXD to Incus, so I was planning on taking anything you may have done and tweak that to get it to behave with my cluster, getting the result into Incus and hopefully it will work for others too!

**Comment by sharathsivakumar** [comment]
@stgraber I have not been able to work on this due to personal issues. However I am keen to get this done, so will it be fine if I turn it in by the end of this week?

**Comment by stgraber** [comment]
Hey there!

Sorry to hear about your personal issues, I hope things are better now :(

I'm planning on releasing Incus 0.2 towards the end of next week and we definitely want `lxd-to-incus` to be able to migrate clusters at that point.

That still leaves you some time to work on it this week and I'll pick things up where they are next week.
