### ISSUE TITLE
Automatically bring bridge.external_interfaces up

### ISSUE THREAD

**Issue by bensmrs** [lxc/incus#1281]
External interfaces need to be unconfigured for an incus-managed bridge to be configured. However, Incus doesn’t itself bring those interfaces up when the bridge is brought up. To properly do it, we must write something like the following for each external interface (with `systemd-networkd`), which is neither obvious nor resilient to renaming:
```
BindCarrier=<the bridge interface>
Unmanaged=yes
```

Would an option `bridge.enable_external_interfaces` (or another name) taking a list of external interfaces to bring up, or a wildcard `*` for all the interfaces configured in `bridge.external_interfaces`, be interesting?

**Comment by stgraber** [comment]
We can just have the code bring them up, I've actually got that already in the OVN implementation.
