### ISSUE TITLE
[Doc] Description of proxy bind option

### ISSUE THREAD

**Issue by candlerb** [lxc/incus#1282]
At https://linuxcontainers.org/incus/docs/main/reference/devices_proxy/#type-proxy it says:

> To add a proxy device, use the following command:
> 
> ```
> incus config device add <instance_name> <device_name> proxy listen=<type>:<addr>:<port>[-<port>][,<port>]
>     connect=<type>:<addr>:<port> bind=<host/instance_name>
>                                             ^^^^^^^^^^^^^
> ```

The suggests that if you want to bind on the instance side, you have to give the instance name. But in reality, you put literally the string "instance", i.e. `bind=instance`.

I think it should just say `bind=<host/instance>`

The later description of the `bind` option is correct.

**Comment by stgraber** [comment]
Indeed
