### ISSUE TITLE
doc: installing macOS and Windows client

### ISSUE THREAD

**Issue by hnakamur** [lxc/incus#132]
https://github.com/lxc/incus/blob/2d853763d9f70e02cc205369479717ce54bb410c/doc/installing.md#other-operating-systems
says about clients for macOS and Windows.

However it seems they do not exist yet. The following pages are 404 Not Found.

* https://formulae.brew.sh/formula/incus
* https://community.chocolatey.org/packages/incus

**Comment by stgraber** [comment]
Yeah, those two packages are work in progress and should appear in the next few days.

**Comment by hnakamur** [comment]
Alright, thanks!
When I confirm these packages appear, I will close this issue.

**Comment by stgraber** [comment]
https://github.com/Homebrew/homebrew-core/pull/150036 is the pending one for HomeBrew.
For Chocolatey it will take a tiny bit longer.

**Comment by hnakamur** [comment]
I confirmed https://formulae.brew.sh/formula/incus is ready.
https://community.chocolatey.org/packages/incus is not ready yet.

**Comment by stgraber** [comment]
https://community.chocolatey.org/packages/incus/ now exists but the package itself is still pending publication.

**Comment by stgraber** [comment]
Closing as both links are now valid even if still pending review
