### ISSUE TITLE
Feature request: Support OCI-compatible images registry

### ISSUE THREAD

**Issue by itviewer** [lxc/incus#1320]
This is a feature request, after careful consideration, I think this suggestion is better posted as an issue here instead of Discourse.

When I was learning about macOS virtualization, I came across the [tart project](https://github.com/cirruslabs/tart). Tart supports publishing (pushing) macOS or Linux virtual machine images to any OCI-compatible container registry, and then pulling and running virtual machines with commands like
```
tart clone ghcr.io/cirruslabs/ubuntu:latest ubuntu
tart run ubuntu
```
I think this is a great idea and it is also what incus has been missing: a hub-like infrastructure support mechanism.
If the incus client can store and pull images from any public OCI-compatible images registry(e.g. ghcr.io) in a similar way as Docker, it will greatly facilitate users to share pre-built images and promote user usage.

I'm not sure how much work would be required to support this beyond converting `simple streams` and `raw` images to an OCI-compatible format, but I think it would be worth some effort.

Appreciate everyone’s advice.

**Comment by stgraber** [comment]
I don't think this is something we'll be doing.

For system containers and virtual machine images, we very much do not want to encourage people building their and sharing their own images. System containers and virtual machines should generally be created from pristine, trustworthy OS images and then customized from that point on, effectively the same story as your OS images in the public cloud.

For application containers, we already use (exclusively) OCI registries for those as for those application images. The registry ecosystem makes sense there, those are applications which people customize and build on top of each other, with publishing a new image being the only way to share those modifications.
