### ISSUE TITLE
Build aarch64 static binaries

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#136]
When building static binaries for incus and incus-migrate, also have Go cross-compile some arm64 versions for all three OS.

**Comment by adamcstephens** [comment]
Is `incus` feature complete as a static binary, or are there missing features? The Makefile currently builds a dynamically linked version:

https://github.com/lxc/incus/blob/f2c3c8242533b9f3855ea812d95e44a0c256f301/Makefile#L42

**Comment by stgraber** [comment]
The client is fully functional as a static binary, the main downside with Go when building statically is that it doesn't get to use the system's libnss and so handles DNS resolution on its own.
