### ISSUE TITLE
incus export failed because of tmpdir

### ISSUE THREAD

**Issue by webservicebe** [lxc/incus#1363]
incus export web5 /backup/daily/web5.tar.gz
resulted in:
Error: Create backup: Backup create: Error adding "/var/lib/incus/storage-pools/default/containers/web5/rootfs/nas/..." to tarball: Failed to copy file content "/var/lib/incus/storage-pools/default/containers/web5/rootfs/nas/..": io: read/write on closed pipe

Getting down in the logs I saw the problem:
Nov 09 09:26:17 cntrd1 promtail[1734224]: level=error ts=2024-11-09T08:26:17.412726406Z caller=positions.go:179 msg="error writing positions file" error="write /tmp/.positions.yaml8778350468977343617: no space left on device"

This is normally because the instance is 50 GB and the space left in /tmp is only 25 GB.

Is there a way I can change the tmp-dir incus usages for creating backups?

Fixed! (I guess)
saw these 2 variable which I can point to a storage with more volume
storage.backups_volume
storage.images_volume

**Comment by stgraber** [comment]
Indeed the solution for this kind of issue is to set storage.backups_volume so the backup is stored somewhere with sufficient storage space.

**Comment by candlerb** [comment]
This just bit me.

I think it's non-obvious that:
1. If your container is large, a large amount of temporary file storage space is needed during the export.
2. Even if you specify the target file path on a filesystem with lots of space, the temporary files are not created there, and you may run out of storage on your root filesystem.
3. To specify a different location for temp files, you need to create a custom storage volume and set it as a place for storing backups (even though you're not actually storing the backup here)

    ```
    lxc storage volume create zfs container-backups
    lxc config set storage.backups_volume zfs/container-backups
    ```

Perhaps this could be mentioned in the documentation [here](https://linuxcontainers.org/incus/docs/main/howto/instances_backup/#instances-backup-export)?

**Comment by Charadon** [comment]
Yeah, it should really be mentioned in the docs, because I ran into this issue and it took quite a while to find this issue with the solution (Setting storage.backups_volume)

**Comment by valankar** [comment]
Just came across this issue. I didn't expect it to use a tmp directory locally. Even when I use an output file of '-' and send this to another machine, it still requires essentially double the container disk usage locally.

Is there perhaps some way to improve this? Isn't btrfs send capable of just sending data without a tmp location? I am using incus on a machine with low disk space, and it is difficult to use this backup system without having lots of free space.
