### ISSUE TITLE
Humble Plea to Simplify Web UI Auth

### ISSUE THREAD

**Issue by gitizenss** [lxc/incus#1366]
![image](https://github.com/user-attachments/assets/3764db91-3056-4b5a-86ed-b9d8506e7743)
As someone who is going through the painful setup process, I can't help but feel this small change has caused countless hours wasted well before it is remotely necessary for security.

Most of the initial experience with incus is right in the web UI, and it has been half-broken on various browsers for over a year. 

People want to try out incus just to see if it's actually something they want to use. The clunky auth system gets in the way of that. I can't think of a justification for that friction being a forced default. 

I am requesting a simple, easy way to either disable auth entirely or set it to use a user-provided password. Each time I revisit incus on a new machine this completely halts me in my tracks and wrestles me into spending hours debugging device-specific edge-cases.

![image](https://github.com/user-attachments/assets/fa176ccb-ba6c-4fd9-bec7-909c5b7d28cc)
https://discuss.linuxcontainers.org/t/how-to-install-and-setup-the-incus-web-ui/19522/2
https://discuss.linuxcontainers.org/t/incus-ui-install-error-using-token-not-authorized/18822

**Comment by stgraber** [comment]
We have done that already, Incus 6.7 will have `incus webui` which opens the UI immediately in your web browser.

**Comment by gitizenss** [comment]
Awesome!!
