### ISSUE TITLE
Use tags with semver syntax

### ISSUE THREAD

**Issue by rgl** [lxc/incus#138]
Instead of using `incus-0.1` please use tags with the semver syntax like `0.1.0` or `v0.1.0`. That would make things easier to reason about (e.g. tools like [renovate](https://github.com/renovatebot/renovate) work out-of-the-box with those).

**Comment by stgraber** [comment]
We're not going to be changing our pattern for now as it's consistent across all Linux Containers project and is the pattern that our own tooling and downstream users have been used to consuming for over a decade.

That said, we do have the 6.0 LTS coming across all our projects in April 2024 which could be a valid time to change tag patterns across the board.

I did a quick survey of all the projects we commonly interact with and seems like it's pretty much split equally between vx.y.z and project-version patterns so I'd expect tooling that commonly parses tags to understand both.

Closing as it's something we want to consider across our entire Github org and only consider when moving to the next major release.
I did make a note to look at this when preparing for our next LTS though!
