### ISSUE TITLE
Display hostname for 'incus webui'

### ISSUE THREAD

**Issue by andyl** [lxc/incus#1386]
# Required information

Incus 6.7 on an Ubuntu 22.04 host.

# Issue description

The new `incus webui` in Incus 6.7 is excellent - thank you!

When using `incus webui remote:`, I find myself losing track of which host is active in the webui.  I can't find a <remote_name> label on the web interface.  The URL in the browser window shows 'localhost'.

Feature request: show the  remote name in the page title and/or somewhere on the web interface.

**Comment by stgraber** [comment]
`incus webui` doesn't really have control over the title or anything in the UI.

That said, for the Incus UI (rebranded LXD UI), the UI itself looks for `user.ui.title`.
So you can do `incus config set user.ui.title=my-server` and that will be reflected in the UI.
