### ISSUE TITLE
Question about logs from systemd: Is dnsmasq shutting down properly?

### ISSUE THREAD

**Issue by dontlaugh** [lxc/incus#1392]
Incus versions are Client version: 6.7; Server version: 6.7

`journalctl -fu incus` then run `systemctl restart incus`

This shows up in the logs

```
systemd[1]: Stopping Incus - Daemon...
systemd[1]: incus.service: Deactivated successfully.
systemd[1]: incus.service: Unit process 94026 (dnsmasq) remains running after unit stopped.
Nov 17 19:15:15 augustus systemd[1]: Stopped Incus - Daemon.
systemd[1]: incus.service: Found left-over process 94026 (dnsmasq) in control group while starting unit. Ignoring.
systemd[1]: This usually indicates unclean termination of a previous run, or service implementation deficiencies.
```

dnsmasq is given a new PID on every restart, so presumably our intention is to have that process terminate w/ the service.

**Comment by stgraber** [comment]
Not quite. We purposefully don't terminate dnsmasq when Incus exits as we want it to keep being available for the instances running during a service restart.

However as soon as Incus starts back up, it restarts all the networks to generate an up to date dnsmasq config.

So it's perfectly normal to both see dnsmasq still run when Incus goes down and to see it get restarted when Incus starts up.

**Comment by smemsh** [comment]
Unfortunately with dnsmasq still running, the filesystem housing the lease cannot be unmounted.   In my case, it means encrypted disks housing the incus data cannot be stopped and be brought offline, without manually killing the dnsmasq after figuring out the correct pid (potentially amongst other dnsmasq running on the system).

Perhaps the dnsmasq should not be part of the systemd unit for incus if it is supposed to remain running.  It might instead have its own unit file, so it can be stopped when that is required.  If it just stays running forever after its parent unit was started at least once on the host system, that breaks the abstraction of having the unit in the first place.  Hence, the complaint by systemd that it is an abnormal situation.

**Comment by smemsh** [comment]
What if incus shuts down the dnsmasq if there are no longer any instances running that are configured with the incus network which started the dnsmasq? In my case I have shut down all instances, yet the dnsmasq remains, but if I understand comments in #1554, it's only needed for instances that remain running during a restart.
