### ISSUE TITLE
Move commands to standard `cmd` directory

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#14]
Another thing we've meant to do in LXD but never really found the time for is to re-organize the repo a bit, starting with moving the individual commands under a `cmd` directory.

In time, this should allow for a cleaner repository root with the structure looking like:
 - client/ => The Go client package for the API
 - cmd/ => Commands
 - internal/ => Internal packages (can't be used externally)
 - shared/ => Packages that are meant for outside users to consume

**Comment by rjtch** [comment]
Hey can i take this task?

**Comment by stgraber** [comment]
I'm going to keep that one to myself, sorry.
Basically all the easy commands have been moved, the only one left is `incusd` but this one is going to be a bit of a mess to move and will likely be done in a little while.

We could just move it to the other directory easily enough, but I don't want there to be sub-packages within the cmd/ packages.
So things need to be moved to either internal or shared and then shared needs a big cleanup too.
