### ISSUE TITLE
Make scriptlet validation even safer

### ISSUE THREAD

**Issue by bensmrs** [lxc/incus#1403]
Currently, we validate scriptlets simply if they pass Starlark’s parsing. I intend to add an additional validation step in the `*Validate` methods to ensure that required functions (`qemu_hook` for `QEMU`, `instance_placement` for `InstancePlacement`, `authorize` for the future `Authorize`) are actually defined in the scriptlet.
It will not ensure that the scriptlet works or is well-typed, but adds quite a bit of safety.

If it looks good to you, you can assign me on the issue and I’ll ship it with the Authorization scriptlet.

**Comment by stgraber** [comment]
Sounds good!
