### ISSUE TITLE
incusd will not run with --syslog specified but no syslog available.

### ISSUE THREAD

**Issue by cmspam** [lxc/incus#1413]
I have been testing Incus on Chimera Linux and encountered an issue related to logging. Chimera Linux does not enable a syslog service on boot by default, but incusd is started with the --syslog option.

As a result, on a fresh install without enabling syslog, incusd fails to start and exits with the following error message:

`Syslog logging isn't supported on this platform`

I thought it was a Chimera problem initially, but during some discussion in the Chimera Linux IRC, it was suggested that services typically do not terminate solely because syslog is unavailable. While it is helpful that incusd reports this error, the current behavior raises a question:

Is the intended behavior for incusd to terminate completely in this scenario? Alternatively, would it be preferable for incusd to continue running, emit the error, and proceed without syslog logging?

I would love to get your insights.

**Comment by stgraber** [comment]
I think the current behavior is reasonable. You specifically requested that Incus uses syslog logging by passing `--syslog` so having Incus fail to start when it can't do so seems appropriate as the alternative would be Incus running with no logging as you've instructed it to log everything to a non-existing target.

Syslog logging tends to be used in many enterprise environments where failing to log through syslog may be a compliance issue, so having startup fail when it was requested and isn't working seems appropriate.


This is different from a number of other pieces of software where they will automatically attempt to log to syslog and fallback to stderr or a log file if they can't connect to syslog, but in those environments the user didn't explicitly request that logging happens through syslog.
