### ISSUE TITLE
[doc] `incus list` documentation formatting

### ISSUE THREAD

**Issue by bensmrs** [lxc/incus#1421]
https://linuxcontainers.org/incus/docs/main/reference/manpages/incus/list/, generated from `doc/reference/manpages/incus/list.md`, in turn generated from the manpages, is wrongly formatted. Additional processing should be done on the command description.

**Comment by stgraber** [comment]
Hmm, we basically entirely rely on spf13/cobra for that stuff. Using the markdown output from `incus manpage PATH --format=md --all`, so we'd need to try and tweak the input to get a more suitable output.
