### ISSUE TITLE
PR documentation changes get uploaded by the CI job before merging

### ISSUE THREAD

**Issue by bensmrs** [lxc/incus#1422]
Everything is in the title, the CI job uploads the documentation artifacts even when a PR hasn’t been merged. It can lead to obvious issues if a malevolent actor wants to upload something on linuxcontainers.org.
I think it happens only if the whole CI pipeline is green, but still pretty easy to mess up things…

**Comment by bensmrs** [comment]
I mean… look at the website :)
https://linuxcontainers.org/incus/docs/main/authorization/

**Comment by stgraber** [comment]
Hmm, going to have to go look at what's going on with that script :)

**Comment by stgraber** [comment]
Fixed! We were performing quite a few checks on the artifact but apparently were incorrectly relying on what Github says is the repo when Github meant the target repo for the PR... Anyway, adding an extra filter for the triggering event should do the trick.
