### ISSUE TITLE
Is the 'name' instance property still supported?

### ISSUE THREAD

**Issue by lgrn** [lxc/incus#1436]
# Required information

Debian GNU/Linux 12 (bookworm) 6.1.0-28-amd64 running Incus 6.7

# Issue description

According to [Instance properties](https://linuxcontainers.org/incus/docs/main/reference/instance_properties/#instance-properties), there is a `name` property. It's not completely clear from the doc what "read only" actually means, but I think it's heavily implied by the later warning that this means that it cannot be changed as a config value after creation (with `incus config edit` for example), and that you should do it with `incus rename` instead. This is also supported by the [parent article](https://linuxcontainers.org/incus/docs/main/explanation/instance_config/) that states:

> Some of the properties are read-only and cannot be changed after creation

That article also states that:

> In the YAML configuration, properties are on the top level.

Based on this, I was expecting this to work:

`config.yaml`
```yaml
name: my-name
config:
  cloud-init.network-config: |
    version: 2
    ethernets:
      eth0:
(...)
```
```bash
incus launch images:alpine/edge/cloud < config.yaml
```

Instead of `my-name` as expected, the name is auto-generated.

Under the [Pass a configuration file](https://linuxcontainers.org/incus/docs/main/howto/instances_create/#pass-a-configuration-file) section, the suggestion is to use `incus show foo` to inspect the existing config, but `name:` is missing here as well.

So the question is, can the property be used at all to set the name of an instance in yaml configuration, and if so how? Regardless of the expected behavior I think the docs could use some clarification, since the property doesn't even seem to show up with `incus config show`.

**Comment by stgraber** [comment]
I believe the YAML is being read into an InstancePut struct, so only letting you change the writable fields of the instance after its creation.

`incus launch images:alpine/edge/cloud my-name < config.yaml` should work as expected.

**Comment by stgraber** [comment]
I just confirmed that it is being read as an `InstancePut` (https://github.com/lxc/incus/blob/main/shared/api/instance.go#L156) and the remaining fields of `InstancesPost` are filled in from the CLI (image being used and name).

**Comment by lgrn** [comment]
> `incus launch images:alpine/edge/cloud my-name < config.yaml` should work as expected.

Sure, that works fine, but I guess what's confusing me is why the `name` instance property is even in the documentation at all if it's neither configurable in the YAML nor shows up in the config show output, and the only two ways to interface with this value is through `incus launch/init` or `incus rename`?

If anything it seems more like a kind of primary key to the entire object than a property of the object itself.

**Comment by stgraber** [comment]
It doesn't have to be modifiable for it to be a valid property. There are actually a bunch more properties which are currently missing in documentation, I sent out https://github.com/lxc/incus/pull/1439 to address that.

The documentation for the YAML based creation seems correct, it refers to `incus config show` as a way to get what's allowed in the YAML and `incus config show` correctly extracts the InstancePut part of the struct, which are the same fields that create/launch consumes.

But that's not the entire set of properties, some of the others are used by things like `incus info` or `incus list`.

**Comment by stgraber** [comment]
If you want to look at what's actually on the full object, you can poke the API with `incus query /1.0/instances/c1` or using `incus list -fyaml c1`.
