### ISSUE TITLE
incus storage create hangs in script

### ISSUE THREAD

**Issue by pgrobelniak** [lxc/incus#1467]
Following command hangs when run in script, while when running interactively it succeeds immediately without any prompt:

    incus storage create default lvm \
      source=vg_default \
      lvm.vg_name=vg_default \
      lvm.vg.force_reuse=true \
      lvm.use_thinpool=true \
      lvm.thinpool_name=LXDPool
      
Reproduced today on ubuntu 24.04.1 with incus 6.0.2-202409162106-ubuntu24.04_amd64.deb
Works fine with 6.0-202405282244-ubuntu22.04_amd64

**Comment by stgraber** [comment]
Most `create`, `launch` and similar commands can consume YAML input to provide a full object to be created. This is most likely the source of the problem for you here, your script must somehow have been passed some stdin data and so ends up stuck trying to read that into YAML.

Try doing:
```
incus storage create default lvm \
  source=vg_default \
  lvm.vg_name=vg_default \
  lvm.vg.force_reuse=true \
  lvm.use_thinpool=true \
  lvm.thinpool_name=LXDPool < /dev/null
```

To override your current stdin with nothing, if that's the issue, it will unblock things.

**Comment by pgrobelniak** [comment]
That did the trick, thanks!
