### ISSUE TITLE
Expose IPv4 and IPv6 router address for OVN networks

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#1481]
Currently the WAN side IPv4 and IPv6 address for an OVN network is available by looking at volatile configuration keys in `incus network show XYZ`. That's fine, but it would make more sense to also have it in `incus network info XYZ` where we already show the router name and active chassis.

To do that cleanly, we should expand `NetworkStateOVN` to include the information, fill it in on the server side and have the CLI tool show it when available.

**Comment by winiciusallan** [comment]
Hi @stgraber! I would like to work on this issue, can you assign it for me? Thanks!

**Comment by stgraber** [comment]
Done!

**Comment by winiciusallan** [comment]
After changes, it is looking like this:

```
OVN:
  Chassis: testt
  Logical router: incus-net3-lr
  UplinkIPv4: 10.250.150.101
  UplinkIPv6: fd42:e1aa:3b75:6d22:216:3eff:fec8:3130
```
