### ISSUE TITLE
incus    shell does not accept --project global flag

### ISSUE THREAD

**Issue by cquike** [lxc/incus#1487]
# Required information

 * Distribution: Debian 
 * Distribution version: 12

# Issue description

According to the `incus shell --help` one can use the global flag `--project` . However that fails:

```
incus --project my_project   shell my_instance
Error: unknown command "shell" for "incus"
```

**Comment by stgraber** [comment]
This has already been fixed earlier this month.

**Comment by cquike** [comment]
Thanks!
