### ISSUE TITLE
Incus 6.7 cephfs storage on microceph still requires config files at /etc/ceph/

### ISSUE THREAD

**Issue by tregubovav-dev** [lxc/incus#1489]
I was surprised to see that `Incus 6.7` can create `Ceph RBD` storage on `microceph` cluster shared the same nodes without installation `ceph-common` packages and copying config files from the `microceph` snap. (`6.5` couldn't to do that). 

Below is an example from my 3-node test cluster with `incus` and `microceph`
```
for i in {1..3}; do sudo incus storage create incus ceph --target=vm-0$i; done && sudo incus storage create incus ceph ceph.osd.force_reuse=true
Storage pool incus pending on member vm-01
Storage pool incus pending on member vm-02
Storage pool incus pending on member vm-03
Storage pool incus created
```

However, attempting to create `cephfs` storage fails:
```
for i in {1..3}; do sudo incus storage create incus_fs cephfs source=incus_fs --target=vm-0$i; done && sudo incus storage create incus_fs cephfs
Storage pool incus_fs pending on member vm-01
Storage pool incus_fs pending on member vm-02
Storage pool incus_fs pending on member vm-03
Error: Failed to open "/etc/ceph/ceph.conf": open /etc/ceph/ceph.conf: no such file or directory
```

The workaround is to symlynk or copy `ceph.conf` and `ceph.keyring` files from `/var/snap/microceph/current/conf` to `/etc/snap`.

**Comment by stgraber** [comment]
Nothing has changed on our end. Interactions with Ceph RBD are usually done by calling `ceph` and `rbd` as shell commands which microceph typically provides as aliases. Those operations don't require parsing of /etc/ceph/.

However cephfs is done by directly telling the kernel to mount cephfs, doing that requires us to directly read the configuration, which fails if it's not available at the standard Ceph location.

You'd also notice virtual machines failing to start when /etc/ceph/ isn't available.
