### ISSUE TITLE
Remove all references to LXD and `lxc` command line

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#15]
This is going to be a big one, but the entire codebase needs to be looked at and all mentions of LXD, lxd or lxc need to go away and be replaced with their new Incus equivalent. This can't be done fully programmatically as there are cases where lxc/LXC for example refers to liblxc rather than the confusingly named LXD client, those need to be preserved.

At the end of this process, a test should be added to ensure that this doesn't regress when importing LXD changes into this repository.

**Comment by netlore** [comment]
I can only comment that moving away from using the command line tool named "lxc" is alone a reason to move to this fork... I cannot tell you how irritating it is to search for information about LXC on `$favourite_search_engine` and only find results for LXD.

**Comment by stgraber** [comment]
That unfortunately won't improve as Canonical will keep using the lxc/lxd combo...
And I don't expect `inc` is going to be a whole lot more Googlable, though Incus might be :)

**Comment by AkihiroSuda** [comment]
FYI `/usr/bin/inc` seems taken by mmh: https://pkgs.alpinelinux.org/contents?branch=v3.18&name=mmh&arch=x86_64&repo=community

**Comment by stgraber** [comment]
That's kinda the issue with any three letter command these days...

Hopefully there aren't many systems that both want mmh and Incus installed concurrently.

Looking at mmh it seems likely that if one uses Incus, mmh would find itself inside a container rather than on the host.

**Comment by kees** [comment]
Why not make cli command "incus"? Seems like not much different, and can search for help easier. "inc<tab>" instead of "inc<space>" :)

**Comment by stgraber** [comment]
Yeah, as much as having just the three letters saves some typing, using `incus` would certainly make things a bit more googlable and folks can still create a local alias.

**Comment by stgraber** [comment]
I think I'll prepare a PR to rename the daemon to incusd, then rename the CLI to incus so we can get an idea of what that involves :)

**Comment by paulocoghi** [comment]
@palaashatri and every user that would like to use `inc` will be able to do so by creating an alias.

**Comment by netlore** [comment]
Although I'm hardly in a position to be part of any decision making process, I'd like to suggest that "incus" is preferable to "inc", as the latter will be almost impossible to search on google, since there will be many unrelated instances of "inc", as an abbreviation for "include", and other things.

**Comment by stgraber** [comment]
Yeah, we'll be going with `incus` for the command line tool, I'm preparing a PR for the rename.

**Comment by igalic** [comment]
all "usage" functions will need to be adapted to talk about the right tool

**Comment by stgraber** [comment]
Yep, the priority right now likely is:
 - cmd/incus
 - doc/
 - cmd/*
 - incusd/

Basically from most to least user visible. For each of those, we need to evaluate every instance of `LXD`, `LXC`, `lxd` and `lxc`.
It would be easy to just run sed over the whole thing and call it done, but it's not quite that simple as there are some cases that need to be noted down as things to keep for backward compatibility reasons, just as there will still be legitimate uses for `LXC` and `lxc` when it refers to liblxc or the LXC project.

That's why the current renames took some time, they weren't fully automated, I would write a bunch of grep patterns to identify the bulk of what needed changing, then sed patterns to rename the most common safe ones, then keep going until only a few odd ones remain and then process those entirely by hand as they're the ones that may need to stay the way they were.
