### ISSUE TITLE
skopeo not inheriting outgoing proxy configuration

### ISSUE THREAD

**Issue by antifob** [lxc/incus#1509]
# Required information

 * Distribution: Debian
 * Distribution version: bookworm
 * The output of "incus info" or if that fails:
   * Kernel version:
   * LXC version:
   * Incus version: 6.8
   * Storage backend in use:

# Issue description

`skopeo` does not inherit the outgoing proxy settings of `core.proxy_http` and `core.proxy_https`.
In some configurations, this results in an `Image not found` error due to `skopeo` not being able to reach the Internet.

# Steps to reproduce

The below demonstrate that `skopeo` does not contact the configured proxy server.

```
# listen on a tcp port
nc -lnvp 1080

# point incusd to the "proxy"
incus config set core.proxy_https=http://127.0.0.1:1080

incus remote add docker https://docker.io --protocol=oci
incus launch --console docker:hello-world --ephemeral

# expected: the proxy/netcat is poked by incusd
```

# Information to attach

Underlying error as seen from `incus monitor`.

```
metadata:
  context:
    name: hello-world
    stderr: 'Failed to run: skopeo inspect docker://docker.io/hello-world: exit status
      1 (time="2024-12-13T14:23:16Z" level=fatal msg="Error parsing image name \"docker://docker.io/hello-world\":
      pinging container registry registry-1.docker.io: Get \"https://registry-1.docker.io/v2/\":
      dial tcp: lookup registry-1.docker.io on 9.9.9.9:53: dial udp 9.9.9.9:53: connect:
      network is unreachable")'
    stdout: ""
  level: debug
  message: Error getting image alias

```

# Workaround

For the Zabbly-provided package...

```
cat>>/etc/default/incus<<__EOF__
http_proxy=http://proxyhost:port
https_proxy=http://proxyhost:port
__EOF__
systemctl restart incus.service
```

**Comment by winiciusallan** [comment]
Should we override the `HTTPS_PROXY` environment variable if `core.proxy_http` or `core.proxy_https` exists? Something like `HTTPS_PROXY skopeo inspect ...`

here https://github.com/lxc/incus/blob/ed2def116ee105fda6bb36ef8c62ff18308ca2ff/client/oci_images.go#L309

**Comment by stgraber** [comment]
We already pass proxy information from the server config to the client logic.

So from within oci_images.go, we should be able to get the proxy by calling `r.http.Transport.(*http.Transport).Proxy` with a fake `http.Request` roughly matching what we want to access (scheme and host must be correct at least).

**Comment by winiciusallan** [comment]
Hi @stgraber. Could you assign this issue to me? I was doing some tests, and I made certain progress. Thanks!

**Comment by winiciusallan** [comment]
Now, I'm able to get the proxy with what you said.

```go
req, err := http.NewRequest("GET", r.httpHost, nil)
proxy, err := r.http.Transport.(*http.Transport).Proxy(req)
```

So, do I need to pass it to the skopeo command as I suggested in the previous comment or set it to `ProtocolOCI.http`?

**Comment by stgraber** [comment]
Right, you'd want to use `subprocess.RunCommandSplit` instead so you can pass it the environment.

**Comment by winiciusallan** [comment]
Hi @stgraber, I tested the changes that I made. Now, it is possible to connect to the proxy, but with the example of the issue, the image can not be inspected, even if the `netcat` connects to the `docker` registry. I don't know if it is a firewall issue in my VM or another thing. If you could give me some feedback, I'd appreciate it.
