### ISSUE TITLE
Improve contribution guide

### ISSUE THREAD

**Issue by bensmrs** [lxc/incus#1521]
Having touched some parts of the Incus code, I feel like some code additions/modifications could benefit from dedicated contribution documentation pages. What about moving the “Contribute to Incus” to its own dedicated section below “General” and have specialized subpages? (i.e. how to add a new configuration key, a new scriptlet, a new authorizer…)

Then, would a (normalized) workflow of posting to the “Tutorials” forum section, then opening an issue to integrate posts to the documentation, be suited for it?

**Comment by stgraber** [comment]
Looks like the current content could already be split between an `Introduction` page which basically is the included content from `CONTRIBUTING.md` and then a `Documentation` page with the current content on how to contribute to documentation. Then we can add more to that.

**Comment by bensmrs** [comment]
Ok let’s go with that first, I’ll draft a few detailed guides in the coming weeks.
