### ISSUE TITLE
Wrong argument name in QMP scriptlet

### ISSUE THREAD

**Issue by bensmrs** [lxc/incus#1523]
When I implemented the QMP scriptlet, I initially used the name `stage` for the argument. In the doc you wrote, @stgraber, you used `hook_name`. When I wrote the function checks, I read the documentation and enforced the `hook_name` argument name. That’s where it gets nasty: the scriptlet expects `stage` but the check expects `hook_name`. Should I rename everything to `stage` or `hook_name`?

**Comment by stgraber** [comment]
Oh, that's annoying. I think we should go with `stage`, a bit shorter and just as clear.

**Comment by bensmrs** [comment]
Yes it is… At least now I’m a bit more comfortable implementing the breaking changes in #1400. I really have to add checks for this scriptlet along with the addition of the `config` stage for the next release.
