### ISSUE TITLE
Cannot rejoin cluster with ceph pool

### ISSUE THREAD

**Issue by slapcat** [lxc/incus#1532]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "incus info" or if that fails:
   * Kernel version: 5.15.0-128-generic
   * LXC version: 5.21.2 LTS
   * Incus version: 6.8-ubuntu22.04-202412151800
   * Storage backend in use: ceph-rbd

# Issue description

I removed a node from a cluster to reinstall the OS. When I try to readd it, it fails with a confusing error about the pool being cluster member specific even though I'm specifying the specific rbd pool name. I've confirmed the ceph cluster and rbd pool are reachable from the node.

# Steps to reproduce

 1. Generate token on existing node.
 2. Try to init and join:
```
# incus admin init
Would you like to use clustering? (yes/no) [default=no]: yes
What IP address or DNS name should be used to reach this server? [default=192.168.0.10]: 10.10.0.10
Are you joining an existing cluster? (yes/no) [default=no]: yes
Please provide join token: eyJzZX****************************MVoifQ==
All existing data is lost when joining a cluster, continue? (yes/no) [default=no] yes
Choose "source" property for storage pool "ceph-rbd": blocks
Choose "source" property for storage pool "dir": /var/lib/incus/storage-pools/dir
Would you like a YAML "init" preseed to be printed? (yes/no) [default=no]: 
Error: Failed to join cluster: Failed to initialize member: Failed to initialize storage pools and networks: Failed to update storage pool "ceph-rbd": Config key "source" is cluster member specific
```

# Additional Information
I can see in the cowsql db that the other nodes are configured the same way:
```
# incus admin sql global .dump |grep source
...
INSERT INTO storage_pools_config VALUES(54,4,8,'source','blocks');
INSERT INTO storage_pools_config VALUES(61,4,10,'source','blocks');
INSERT INTO storage_pools_config VALUES(62,4,10,'volatile.initial_source','blocks');
INSERT INTO storage_pools_config VALUES(66,6,10,'source','/var/lib/incus/storage-pools/dir');
INSERT INTO storage_pools_config VALUES(68,6,8,'source','/var/lib/incus/storage-pools/dir');
...
```

**Comment by stgraber** [comment]
Hmm, that's a pretty weird one as our normal deployment tooling also joins machines in the same way you're doing here, yet those haven't been running into issues...

Do you get the same issue if you wipe `/var/lib/incus/` clean on that joining machine, then run `systemctl restart incus` and attempt the join again?

If so, maybe try with `--debug` so we can see exactly what data it's sending on join.

**Comment by slapcat** [comment]
That worked! Very strange, since like I said this is a newly installed machine, so there shouldn't be any cruft in /var/lib/incus.

Thanks as always, @stgraber !
