### ISSUE TITLE
Feature request: Always use btrfs send/receive when copying an instance and never rsync

### ISSUE THREAD

**Issue by broizter** [lxc/incus#1549]
If you run ```incus copy sample-container sampleserver: --mode push --refresh --instance-only``` it will use BTRFS send/receive for the initial transfer, but every subsequent run rsync will be used instead. Maybe there is a good reason for this but using rsync can be VERY slow. For me its 10x slower than btrfs send/receive, making ```incus copy``` not a great backup method.

Edit: I should mention this is when using the BTRFS storage driver.

**Comment by broizter** [comment]
I realized now that this only happens when you use --instance-only, making it not as big of a deal. Although it would be nice if btrfs send/receive was always used.

**Comment by stgraber** [comment]
Yeah, that's normal, all the snapshots can be nicely transferred through our migration protocol using native transfer methods like send/receive, but the last pass of the currently mounted storage can't be done that way so it's done with rsync.

You can seriously limit the amount of data in that stage by having a recent snapshot. For example, heading a snapshot schedule creating snapshots once or twice a day.
