### ISSUE TITLE
Release tarball needs to include the vendored tree for lxd-to-incus

### ISSUE THREAD

**Issue by juippis** [lxc/incus#166]
# Required information

 * Distribution: Gentoo
 * Distribution version: ~
 * The output of "inc info" or if that fails:
   * Kernel version: 6.1.55
   * LXC version: 5.0.3
   * Incus version: 0.1
   * Storage backend in use: -

# Issue description

I downloaded incus-0.1 from https://linuxcontainers.org/incus/downloads/ which holds the vendored go modules. When making distribution package, these are often built offline so providing the vendored go mods is great! But it looks like there's some sort of a problem with the **lxd-to-incus** tool in this tarball. I don't understand go enough, but this is the error I'm getting:
```
main module (github.com/lxc/incus) does not contain package github.com/lxc/incus/cmd/lxd-to-incus
```

I will attach the fuild build log so you can inspect it. Building the other tools, *fuidshift incus-benchmark incus-user incus lxc-to-incus incusd incus-migrate incus-agent* work correctly. Only **lxd-to-incus** is problematic.

# Steps to reproduce

 1. Download tarball from https://linuxcontainers.org/incus/downloads/
 2. Build it offline so go doesn't have a chance to download any missing modules

**Comment by juippis** [comment]
[incus-0.1:20231013-194301.log](https://github.com/lxc/incus/files/12898303/incus-0.1.20231013-194301.log)

**Comment by stgraber** [comment]
Yeah, that's intentional, `lxd-to-incus` is kept as a standalone Go package so we don't have Incus itself pulling in LXD and all its dependencies.

So rather than doing `go build -v -x ./cmd/lxd-to-incus` you need to do `cd cmd/lxd-to-incus && go build -v -x ./`

**Comment by stgraber** [comment]
I'll have to check the way we make the tarballs though as those may indeed have a bit of a problem in this situation.
