### ISSUE TITLE
panic: Architecture isn't supported: loong64

### ISSUE THREAD

**Issue by gibmat** [lxc/incus#170]
Debian has [announced](https://lists.debian.org/debian-devel-announce/2023/08/msg00000.html) loong64 as a new port. While Incus hasn't yet been uploaded to Debian, LXD  encounters a run-time panic on that architecture ([buildd log](https://buildd.debian.org/status/fetch.php?pkg=lxd&arch=loong64&ver=5.0.2-5&stamp=1696461135&raw=0)), and I would expect Incus to have the same issue:

```
panic: Architecture isn't supported: loong64

goroutine 1 [running]:
github.com/lxc/lxd/shared/version.getUserAgent()
	github.com/lxc/lxd/shared/version/useragent.go:22 +0x548
github.com/lxc/lxd/shared/version.init()
	github.com/lxc/lxd/shared/version/useragent.go:15 +0x28
```

I'm not sure if this will require more than just adding loong64 to `shared/osarch/architectures.go`.

(Also reported to LXD as https://github.com/canonical/lxd/issues/12387)

**Comment by stgraber** [comment]
Should just need that one change.
