### ISSUE TITLE
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by wyz2019** [lxc/incus#173]
在 LXD 的Debain容器里 可以安装docker，但是无法运行，提示如下错误
Docker can be installed in the Debain container of LXD, but it cannot run with the following error prompt
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by stgraber** [comment]
There's nothing fundamentally different between LXD and Incus that would explain this, so the issue has got to do with either Docker (and its init scripts) or with the distro.

My guess is that it may have to do with: https://gitlab.com/apparmor/apparmor/-/merge_requests/1112

In which case you may be able to update the apparmor script manually to handle Incus properly.
