### ISSUE TITLE
Incus fails to launch (Arch AUR)

### ISSUE THREAD

**Issue by ShalokShalom** [lxc/incus#183]
# Required information

 * Distribution: Garuda
 * Distribution version: rolling
 * The output of "inc info" or if that fails:
   * Kernel version: 6.5.7-zen2-1-zen
   * LXC version: 5.0.3
   * Incus version: 0.1
   * Storage backend in use: huh?

# Issue description

Hi there. :)

I just installed incus fresh and attempted to launch an image. 
This fails in a very generic error message. 

# Steps to reproduce

 1. I freshly installed incus from AUR
 2. incus launch images:archlinux/current/amd64 kate
 3. `Error: Get "http://unix.socket/1.0": dial unix /var/lib/incus/unix.socket: connect: no such file or directory`

# Information to attach

[dmesg](https://paste.ee/p/W6Kqe)

inc is not available on my system. 
var/log/incus is empty

```
incus launch --debug images:archlinux/current/amd64 kate

DEBUG  [2023-10-21T21:29:50+02:00] Connecting to a local Incus over a Unix socket
DEBUG  [2023-10-21T21:29:50+02:00] Sending request to Incus                      etag= method=GET url="http://unix.socket/1.0"
Error: Get "http://unix.socket/1.0": dial unix /var/lib/incus/unix.socket: connect: no such file or directory

```

The Arch AUR package seems to do a few things weird, it does not setup incus-admin, as an example, and I don't have `inc` available.

**Comment by stgraber** [comment]
Closing as this feels like an issue that should be filed against the distribution package rather than Incus itself.

From the errors above, it sounds like incusd just hasn't been started on the system.
If you want to debug this yourself, I'd recommend taking a look at the systemd units included in that AUR package and making sure that they're properly installed and running.

**Comment by ShalokShalom** [comment]
I wasn't sure, if this was due to the AUR, thanks for confirming! 🥳
