### ISSUE TITLE
Improve error message about failed launch

### ISSUE THREAD

**Issue by ShalokShalom** [lxc/incus#184]
[The internet said](https://discuss.linuxcontainers.org/t/lxd-error-get-http-unix-socket-1-0-dial-unix-var-snap-lxd-common-lxd-unix-socket-connect-connection-refused/12305/2), that this message essentially says that Incus failed to spin up a server: 

`Error: Get "http://unix.socket/1.0": dial unix /var/lib/incus/unix.socket: connect: no such file or directory`

I that is the cause, do you think we could improve this message, and add some links to the documentation?

Something like: 

The Incus server is not running. Did you try the following? Otherwise, take a look at XYZ.

**Comment by stgraber** [comment]
We may be able to catch the basic socket doesn't exist case and replace the error with something like `Error: The incus daemon doesn't appear to be started (socket path: /var/lib/incus/unix.socket)` but can't really be more specific as that then varies widely between operating systems (the incus client works on Windows and MacOS too) and also can vary a lot from distribution to distribution.

**Comment by ShalokShalom** [comment]
That sounds a lot more useful, and as if testing this on other platforms is mandatory. 

I can test this on Arch.
