### ISSUE TITLE
Basic scriptlet-based authorizer

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#188]
We now have OpenFGA for fine grained access control, but not everyone needs to run a full authorization server and for simpler cases, it could be very useful to have a basic built-in option that can still be very flexible.

I'm thinking of a new `authorization.scriptlet` server config key which takes a scriplet that would then be called with some user context, object context and action and have the ability to allow or deny the request.

**Comment by sharathsivakumar** [comment]
@stgraber I would be interested to work on this.

**Comment by hi-ko** [comment]
I would be happy to test on this. I guess such a script hook would open for much more scenarios to use incus as remote image server having something like a voter script which could then access external services like ldap or db to block or allow access. Are you thinking of a shell script or a Go construct?

**Comment by stgraber** [comment]
We're looking at using a scriptlet which is already a technology we use for our scheduler.
Those scriptlets are python looking scripts that are run inside of a safe environment directly within the Go daemon.

This uses go-starlark from Google.

**Comment by stgraber** [comment]
Unassigning due to lack of activity.

**Comment by christina-zh** [comment]
Im interested in working on this issue, can I be assigned to it please?

**Comment by stgraber** [comment]
Probably best to tackle last in the current batch of stuff assigned to you as that's a bit trickier than the others. But #652 should help you get familiar with some of that stuff already.

This will need a new kind of scriptlet be defined in `internal/server/scriptlet`. It will also need a new server configuration key `authorization.scriptlet` to be added.

The basic infrastructure you can do with:
 - Add an API extension, let's call it `authorization_scriptlet`
 - Add the new config key in `internal/server/cluster/config/config.go`
 - Re-generate the documentation keys with `make update-metadata`
 - Add the new scriptlet definition to `internal/server/scriptlet`
 - Add the new authorizer to `internal/server/auth`
 - Add the needed glue (handle the new config key) to `cmd/incusd/daemon.go` and `cmd/incusd/api_1.0.go`

**Comment by stgraber** [comment]
@christina-zh hello, do you still intend to work on this one or should I clear the assignee?

**Comment by christina-zh** [comment]
hi @stgraber , our group might not have the time to continue working on this issue. You could clear the assignee. Thank you for your help!

**Comment by bensmrs** [comment]
Hi! I’d like to work on this, you can put it in the “soon” milestone.

**Comment by stgraber** [comment]
There you go!

**Comment by bensmrs** [comment]
A few questions as I’m implementing this…
- Do you want the authorization scriptlet to be defined at the server level or cluster level (`localConfig` vs `globalConfig`)?
- The `Get*Access` methods don’t really fit the scriptlet authorization paradigm; do I return the empty list for both?

**Comment by bensmrs** [comment]
I’m allowing myself this shameless ping…
@stgraber

**Comment by stgraber** [comment]
Sorry, been slightly burried under Github notifications lately ;)

The authorization scriptlet should be global (same on all servers), so globalConfig.

And indeed, for the two Get*Access functions, we can just return an empty dataset for now, that's fine.

In theory we could have get_instance_access and get_project_access as functions in the scriptlet which would directly return the access set, if not present then we return an empty set. That'd in theory allow for a scriptlet which defines a bunch of users and access in a Python dict or something, then uses that for permission checks and can also return some version of the access info.

**Comment by bensmrs** [comment]
No problem, I might have been sitting next to some of the notification-makers last week :)

Alright, I’ll see what I can do. As a validation step, to be 100% safe consistency-wise, I propose to check what `get_*_access` give back when invoking them, if they exist, and to reinject the results into the scriptlet, to ensure that every returned user *actually* has access. Is this overzealous or does it seem reasonable to you?

**Comment by stgraber** [comment]
It's probably more than really needed but it's also pretty cheap a check to make, so may as well do it :)

**Comment by bensmrs** [comment]
Are `openfga.*` and `authorization.scriptlet` mutually exclusive? If both are defined, do we chose one? do we exit the server with an error?

**Comment by stgraber** [comment]
yeah, they should be mutually exclusive I think, gets pretty weird if you have both mixed in, so can ignore that for now :)

**Comment by bensmrs** [comment]
> It's probably more than really needed but it's also pretty cheap a check to make, so may as well do it :)

Well, I’m starting to wonder if it’s even possible… on the one hand, the `Get*Access` functions give us users and roles, on the other hand, `CheckPermission` wants a user and an entitlement (among other things). I don’t think maintaining a role<>entitlement map is great, nor is calling the scriptlet n times for each entitlement associated to a role…
I may be mixing up concepts, but the getters’ outputs clearly cannot be mapped to the checker’s input.
