### ISSUE TITLE
[lxd-to-incus] Rewrite OVN database during migration

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#216]
LXD uses a `lxd-` prefix on a variety of OVN objects in both the NorthBound and SouthBound databases.

All of those need to be renamed to the matching `incus-` as part of the migration.

**Comment by sharathsivakumar** [comment]
@stgraber If you have not done this yet, I would like to take a stab at this.

**Comment by stgraber** [comment]
I am most of the way through this one.

It ended up being extremely tricky as it requires pulling both of the OVN databases and updating a lot (but not quite all) of records.

I've got the logic that does that now but I'm working on a way to keep a running log of all those changes so should something go wrong, there will be a few to figure out what needs manual fixing

**Comment by sharathsivakumar** [comment]
Ah, sounds good. I will pick up something else then.
