### ISSUE TITLE
How do I use the incus binaries on the release page

### ISSUE THREAD

**Issue by jiqing112** [lxc/incus#219]
How do I use the incus binary from the release page ?

For example, I downloaded "bin.linux.incus.x86_64 "  on a RHEL Linux system, chmod 755 it .

When I execute ./bin.linux.incus.x86_64 directly, there seems to be command output, which is normal, but the server service is not started.

like that :

_root@2023103101:~# incus version  
Client version: 0.2  
Server version: unreachable_

When I try to use systemctl to manage incus, I get an error: Error: 

_The incus daemon doesn't appear to be started (socket path: /var/lib/incus/unix.socket)_

**Comment by stgraber** [comment]
The `incus` command is the client.

The server is `incusd` which cannot be built statically and so cannot be distributed through the release page (other than the source code to build it yourself).
