### ISSUE TITLE
Add suport for forceful project deletion

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#245]
When dealing with temporary projects, it's a bit annoying having to figure out everything that needs to be removed before being able to delete the project.

It'd be useful to have a force flag which just goes and delete everything in the project instead.

**Comment by dnegreira** [comment]
Can I have a stab at this one?

**Comment by stgraber** [comment]
@dnegreira of course!

**Comment by stgraber** [comment]
@dnegreira I suspect you're going to want to:
 - Add an API extension string for this in doc/api-extensions.md and internal/version/api.go
 - Add a DeleteProjectForce function to the client package which passes a `?force=true` to the API
 - Update the projectDelete API handler to handle the `force` variable and if set to true, then go through everything the project owns and delete it. You probably want to start with instances, then volumes and buckets, then profiles, then networks (starting with acls, zones, peering before networks themselves).

**Comment by stgraber** [comment]
Unassigned this one per @dnegreira's request, it's available for anyone who wants it!

**Comment by MaheshPunjabi** [comment]
Can I try?

**Comment by stgraber** [comment]
Of course!

**Comment by MaheshPunjabi** [comment]
Few follow up questions:
1. Is it fine to specify force as a query type parameter ? Didn't see any existing query parameters, so I thought its best to check. I assume this is yes coz of use of ?force=true
2. When deleting artifacts, do we also want to delete images(if features.images is set) ?
3. Does this need any changes to client/simplestreams ?

Proposed changes:
- [ ] Add an API extension string for this in doc/api-extensions.md and internal/version/api.go. _call it "projects_force_delete"_

- [ ] Update the projectDelete API handler,_in "cmd/incusd/api_project.go"_ to handle the force variable and if set to true, then go through everything the project owns and delete it. You probably want to start with instances, then volumes and buckets, then profiles, then networks (starting with acls, zones, peering before networks themselves).

- [ ] _Re-generate the swagger YAML data (make update-api)._

- [ ] Add a DeleteProjectForce function to "client/incus_projects.go" which passes a ?force=true to the API. _add that function to the ImageServer interface._

- [ ] _Add new "force" argument to "cmd/incus/project.go". when passed, call DeleteProjectForce_
- [ ] _Re-generate the translation template for the new CLI string._

Proposed commits:
api: projects_force_delete
incusd/api_project: Add support for force delete
doc/rest-api: Refresh swagger YAML
client: Add DeleteProjectForce 
incus/projects: add --force flag
i18n: Update translation templates

**Comment by stgraber** [comment]
> Is it fine to specify force as a query type parameter ? Didn't see any existing query parameters, so I thought its best to check. I assume this is yes coz of use of ?force=true

Yeah, I think that's fine. The alternative would have been to support a JSON body in the DELETE request but we've not currently done so for any of our DELETE endpoints, so using a query parameter is likely better.

> When deleting artifacts, do we also want to delete images(if features.images is set) ?

Yep, we'll need to delete:
 - All instances (always)
 - All profiles except for `default` (if features.profiles=true)
 - Empty the default profile
 - All images (if features.images=true)
 - All networks (if features.networks=true)
 - All network zones (if features.networks.zones=true)
 - All network ACLs (if features.networks=true)
 - All storage volumes (if features.storage.volumes=true)
 - All storage buckets (if features.storage.buckets=true)

> Does this need any changes to client/simplestreams ?

Nope, no change to the simplestreams logic.

**Comment by stgraber** [comment]
@MaheshPunjabi how's this one going?

**Comment by MaheshPunjabi** [comment]
I'm still working on it, sorry, got side tracked. I also just posted some questions in that new PR.
