### ISSUE TITLE
Add description field on certificate entries

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#246]
Certificates are one of the few objects which currently don't have a description.
With web UI and a variety of tools now using restricted certificates, it'd be good to have the ability to add comments.

**Comment by presztak** [comment]
Hey @stgraber , can I work on this one?

**Comment by stgraber** [comment]
Absolutely!

**Comment by stgraber** [comment]
This one will need an API extension, addition of the field in the CertificatePut struct and a small DB schema update to add the missing column to store the value
