### ISSUE TITLE
Switch OVN/OVS command line calls to libovsdb

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#255]
The OVN project maintains a Go package to access the databases, it's available at https://github.com/ovn-org/libovsdb

We should slowly transition our various calls to ovn-nbctl/ovn-sbctl to using libovsdb instead, if only to not be dependent on a specific version of the OVN tooling and to also allow for more efficient and race-free interactions with OVN.

**Comment by Abhiram824** [comment]
Hello! I am Abhi, a student for UT Austin. As a part of my final project in virtualization, I was interested in looking into this issue.  I see that you have assigned this already to yourself, but if you need anyone to help out on it, I would be happy to do so!

**Comment by stgraber** [comment]
Hey there,

This one is one of those issues that can be worked on by multiple people in parallel so long as we don't work on the exact same function at the same time :)

Basically there are a whole bunch of functions under `internal/server/network/ovn/ovn_nb_actions.go` that currently call `o.nbctl`. All of those need to be moved to using `o.client` which is the Go-native OVN client (libovsdbclient).

The way I've handled this work so far is by picking a function that's currently using `o.nbctl`, for example let's look at `LogicalRouterAdd`. Then I always go through the same steps:
 - Rename the function to follow our new naming convention, in this case, it would become `CreateLogicalRouter`
 - Add a new `ctx context.Context` argument as the first argument of the function
 - Actually replace the code within the function to use libovsdbclient. In this case, I'd have that function look very similar to `CreateLogicalSwitch` that I've already ported.
 - Commit that work as something like: `incusd/network/ovn/nb: Port CreateLogicalRouter to OVSDB`
 - Then update any existing use of the old function to use the new one and commit that as `incusd/network/ovn: Update for function changes`

Then send that as a pull request and pick the next function to port, rinse repeat until we're done with all of them :)

Feel free to go for the easier ones if a function doesn't seem obvious to map to the structs and actions within the new client logic, just leave them and I can pick them up later.

**Comment by DhruvNistala** [comment]
Hi, I am also working with Abhiram on all the issues for this project. We implemented the CreateLogicalRouter function based on the implementation of the CreateLogicalSwitch function. I created a Draft PR at https://github.com/lxc/incus/pull/750. Let me know if any additional changes need to be made

Additionally, could I be assigned to all the issues that Abhiram is as well?

**Comment by stgraber** [comment]
Thanks, I'll take a look shortly!

I've assigned you to this issue. GitHub only lets me assign issues to people who commented on the issue so you're going to need to post a comment on the other issues so I can assign you there too.

**Comment by dhruvvnistala** [comment]
Thanks, I've left a comment on the other issues accordingly.

**Comment by Abhiram824** [comment]
Hello, we added some more functions in. CreateLogicalRouterSNAT seemed more involved and required sifting through some documentation to add code in, so please let us know if anything does not look right. We created the draft PR at https://github.com/lxc/incus/pull/809

**Comment by Abhiram824** [comment]
Hey I saw in https://github.com/lxc/incus/pull/812 that you combined deleteLogicalRouter for DNAT and SNAT rules, should I do the same for the CreateLogicalRouterSNAT and DNATSNAT?

**Comment by stgraber** [comment]
Yeah, `LogicalRouterDNATSNATAdd` can probably be dropped and `CreateLogicalRouterSNAT` be renamed to `CreateLogicalRouterNAT` and made to handle both type of rules.

**Comment by stgraber** [comment]
@Abhiram824 @DhruvNistala hello, do you still intend to send more changes for this issue or should I clear the assignee field?

**Comment by Abhiram824** [comment]
Hi, we were still intending on working on the issue

**Comment by stgraber** [comment]
Sounds good!

**Comment by Abhiram824** [comment]
Awesome and btw I am out of town rn but will pick things back up in a week

**Comment by Abhiram824** [comment]
I'm working on replacing LogicalRouterRouteAdd. If the route is a discard route do I set the NextHop to be "discard" or do I need to store this information in the "options" field.

**Comment by stgraber** [comment]
According to documentation, that goes into NextHop

**Comment by stgraber** [comment]
I've been porting some of those functions over the past few days, we're now down to just 32 calls left and I've got a batch of 8 or so in progress, slowly getting there :)
