### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by dkwo** [lxc/incus#273]
Trying to build and package incus for void linux https://github.com/void-linux/void-packages/pull/47573 , I noticed the warnings
```
objdump: /destdir//incus-0.3.0/usr/bin/sysinfo: .gnu.version_r invalid entry
objdump: warning: private headers incomplete: bad value
objdump: /destdir//incus-0.3.0/usr/bin/incus-migrate: .gnu.version_r invalid entry
objdump: warning: private headers incomplete: bad value
objdump: /destdir//incus-0.3.0/usr/bin/incus-agent: .gnu.version_r invalid entry
objdump: warning: private headers incomplete: bad value
```
as well as encountered a test failure (after many passing tests)
```
PASS
ok  	github.com/lxc/incus/shared/validate	(cached)
?   	github.com/lxc/incus/test/dev_incus-client	[no test files]
?   	github.com/lxc/incus/test/syscall/sysinfo	[no test files]
FAIL
```
Could you help debug this?

**Comment by stgraber** [comment]
Hmm, how exactly are you building those?

Can you try a standard `make` from the top directory on Void to make sure that things also misbehave in that case?

The `sysinfo` binary is a test binary used in our testsuite, it definitely should not be built as part of a package.

The `incus-agent` failure makes it sound like it's not being built statically which would be a big issue.

Similarly, `incus-migrate` is usually not included in packages as its goal is to migrate a remote system into Incus, so it should be a static binary that can be retrieved by the user on the source system.

**Comment by dkwo** [comment]
I'm building them as in here https://github.com/void-linux/void-packages/pull/47573/commits/5d82020396a3d2f7d8d92c4d035769ed56f4ba17 with
```
go_import_path=github.com/lxc/incus
go_build_tags=libsqlite3
go_package="${go_import_path}/..."
```
and
```
export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"
export GOFLAGS="-buildmode=pie"
```
Notice that the `objdump` warnings are at the end, when the build script generates runtime dependences, not in the build phase, and do not prevent the building of the package. The test failures (in `do_check` phase) happen before those.

The test fails in the same way if I use make and make check:
```
PASS
ok  	github.com/lxc/incus/shared/validate	(cached)
?   	github.com/lxc/incus/test/dev_incus-client	[no test files]
?   	github.com/lxc/incus/test/syscall/sysinfo	[no test files]
FAIL
```
and also here I see the objdump warnings (if i skip tests).
This is with 0.3 version and go 1.21.4
Thanks for helping.

**Comment by dkwo** [comment]
if instead i use
`CGO_LDFLAGS="${CGO_LDFLAGS} -static" go install -p "${XBPS_MAKEJOBS}" -v -tags agent,netgo "${go_import_path}/cmd/incus-agent"` i get warnings
```
# github.com/lxc/incus/cmd/incus-agent
/usr/bin/ld: /tmp/go-link-3559558471/000019.o: in function `_cgo_6f668e16310a_Cfunc_mygetgrouplist':
getgrouplist_unix.cgo2.c:(.text+0x1e): warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-3559558471/000018.o: in function `_cgo_6f668e16310a_Cfunc_mygetgrgid_r':
cgo_lookup_cgo.cgo2.c:(.text+0x40): warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-3559558471/000018.o: in function `_cgo_6f668e16310a_Cfunc_mygetgrnam_r':
cgo_lookup_cgo.cgo2.c:(.text+0xe1): warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-3559558471/000018.o: in function `_cgo_6f668e16310a_Cfunc_mygetpwnam_r':
cgo_lookup_cgo.cgo2.c:(.text+0x186): warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /tmp/go-link-3559558471/000018.o: in function `_cgo_6f668e16310a_Cfunc_mygetpwuid_r':
cgo_lookup_cgo.cgo2.c:(.text+0x235): warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```
but then objtool does not complain, and i get a static executable
`Stripped static executable: /usr/bin/incus-agent`
Is this acceptable?

**Comment by dkwo** [comment]
the test failure is still there though.

**Comment by stgraber** [comment]
Pretty sure you don't want `go_package="${go_import_path}/..."` as that's making it build every single binary in the entire code tree, including those test binaries and other undesirable things.

**Comment by stgraber** [comment]
What's the output of `go version` on that system?

**Comment by dkwo** [comment]
go version go1.21.4 linux/amd64

**Comment by dkwo** [comment]
what do you suggest then, besides /cmd/{incus,fuidshift} ?

**Comment by stgraber** [comment]
https://linuxcontainers.org/incus/docs/main/packaging/

**Comment by dkwo** [comment]
Thanks. The building part now looks better:
```
   Stripped position-independent executable: /usr/bin/incus-migrate
   Stripped position-independent executable: /usr/bin/incus-user
   Stripped static executable: /usr/bin/incus-agent
   Stripped position-independent executable: /usr/bin/incusd
   Stripped position-independent executable: /usr/bin/fuidshift
   Stripped position-independent executable: /usr/bin/lxc-to-incus
   Stripped position-independent executable: /usr/bin/incus-benchmark
   Stripped position-independent executable: /usr/bin/incus
```
I'm still testing with
```
go test -v -tags libsqlite3 ./...
cd test && ./main.sh
```
Is this the wrong way? the test failure happens during go test.

**Comment by stgraber** [comment]
> Is this the wrong way? the test failure happens during go test.

You probably don't want to run the `cd test && ./main.sh` part as that's a very very heavy testsuite which is better run on a dedicated system. That's what we run upstream for all pull requests and releases.

`go test -v -tags libsqlite3 ./...` should be fine though.

Can you show the full output you're getting? It could be that it's a somewhat unrelated piece of code like `lxc-to-incus` that's failing due to the system it's being run on.

**Comment by dkwo** [comment]
Got it. The build indeed is inside a chroot. I attach the full log. [incus.log](https://github.com/lxc/incus/files/13573555/incus.log)
Is there a way to make it more verbose?
As a side note, I've not yet added `cmd/lxd-to-incus` to the build, not sure if relevant.

**Comment by stgraber** [comment]
Right, so it's the tests in `lxc-to-incus` which is failing.
I've managed to reproduce this here though it's not hitting us in CI.
I'll look at what needs updating in that test to have it behave.

**Comment by stgraber** [comment]
I tracked it down, it's because you're missing the `lxc-busybox` template script.

On most systems, that should be located at `/usr/share/lxc/templates/lxc-busybox` and be provided by the `lxc` package or something like it.

You likely are just missing some kind of dependency to bring that in in your case.

Alternatively, you can skip that particular test with:
```
go test -v -skip TestConvertNetworkConfig ./...
```

**Comment by stgraber** [comment]
> is this worth investigating?

Nah, I wouldn't bother. It's a pretty finicky test which validates the behavior of `lxc-to-incus`. That's unlikely to affect many users and those that do care will have a working LXC setup so won't face any issues.



> One last question: since void folks seem to prefer to keep around lxd for a while, I can make it conflict with incus. However, both require raft. Current raft is at 0.16 in void and lxd at 5.9, so my question: What is the minimal raft version required to build incus and cowsql? My pr packages 0.19.1 from the forked repo, but it seems arch linux can make it work with 0.18 from the old repo (they have a more recent lxd though).

I would try to avoid having Incus and LXD conflict with each other as you need both of them installed at the same time to transition the data with `lxd-to-incus` (once it supports Void).

cowsql/raft is made to remain compatible with LXD's own use of raft, so you should be able to update the Linux distribution as a whole to use cowsql/raft as the source for the raft package and then have both cowsql and dqlite use that (which are then used for both Incus and LXD).
That's the approach taken by Debian and a few other distros. Others went with instead packaging cowsql/raft as a new raft-cowsql package to keep things fully separate.

**Comment by stgraber** [comment]
I've never seen those warnings here, but so long as the resulting binary is indeed static, it "should" be fine. You'd likely know pretty quickly if something is wrong by launching a few VMs and testing the incus-agent that way.

**Comment by stgraber** [comment]
Yeah, I guess so, we definitely don't want anything dynamic in there since it needs to run in an unknown environment (the VM).
