### ISSUE TITLE
lxd-to-incus - check shift=true availability on target before migrating

### ISSUE THREAD

**Issue by asmartin** [lxc/incus#309]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "incus info" or if that fails:
   * Kernel version: 5.4.0
   * LXC version: 5.19
   * Incus version: 0.3
   * Storage backend in use: ZFS

# Issue description

I recently migrated from LXD 5.19 to Incus 0.3 on Ubuntu 20.04. My storage pool is on ZFS, and a couple of my containers use `shift=true` to share a folder on the host with the guest:

```
devices:
  mydev:
    path: /path/on/guest
    shift: "true"
    source: /path/on/host
    type: disk
```
    
Under the hood LXD was using shiftfs to accomplish this since idmapped mounts are [not supported on ZFS until ZFS 2.2](https://linuxcontainers.org/incus/docs/main/reference/storage_zfs/#limitations). However, I didn't realize this when migrating so I proceeded and after migrating found that I could not start some of my containers. I was able to work around this by accessing the files a different way, but it would be great if the `lxd-to-incus` migration tool checked that the target supports `shift=true` if it detects that it is used in any of the source containers/VMs. Thanks!

# Steps to reproduce

1. create a container on LXD that uses `shift=true` on a filesystem which does not support idmapped mounts
2. run `lxd-to-incus` to migrate to incus
3. attempt to start the container on incus and see that it fails

# Information to attach

 - [N/A] Any relevant kernel output (`dmesg`)
 - [N/A] Container log (`incus info NAME --show-log`)
 - [x] Container configuration (`incus config show NAME --expanded`)
 - [N/A] Main daemon log (at /var/log/incus/incusd.log)
 - [N/A] Output of the client with --debug
 - [N/A] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the issue)

**Comment by stgraber** [comment]
Ah yeah, that's unfortunate. Note that if you want ZFS 2.2, I have kernel builds here https://github.com/zabbly/linux which are compatible with a ZFS 2.2 build here https://github.com/zabbly/zfs.

As for adding detection logic, it's unfortunately not something that I believe to be reasonably doable. The reason for that is that there is no good way from user space to check whether a given filesystem will allow the use of idmap mounts, not until you actually do the mount attempt anyway (which is what Incus does)...

We don't want to outright block `shift=true` as it will work in many cases, with exactly what scenarios work or don't work being dependent on what's in the user's kernel.

I think the best we can do is check if the shiftfs kernel module is loaded and if it is, show a warning to the user prior to the migration.

**Comment by stgraber** [comment]
Luckily shiftfs was never a default feature of the LXD snap, it never was stable enough for us to roll it out to all users, so as it was opt-in, the userbase for it should be extremely small.

**Comment by asmartin** [comment]
Or maybe adding a note to the migration documentation page that says for the user to check for compatibility if they use shiftfs would be all that's needed

**Comment by stgraber** [comment]
yeah but then we need to go into details on what shiftfs is as most users won't have a clue.

I think the warning in the tool itself if we detect that the module is loaded (and therefore the user has enabled the feature) should do a better job at warning the target audience before they go through with the migration.

**Comment by asmartin** [comment]
Sounds good. Thanks for the fast response on this!

**Comment by stgraber** [comment]
```
root@v1:~# ./lxd-to-incus 
=> Looking for source server
==> Detected: snap package
=> Looking for target server
==> Detected: systemd
=> Connecting to source server
=> Connecting to the target server
=> Checking server versions
==> Source version: 5.19
==> Target version: 0.3
=> Validating version compatibility
=> Checking that the source server isn't empty
=> Checking that the target server is empty
=> Validating source server configuration

WARNING: The shiftfs kernel module was detected on your system.
         This may indicate that your LXD installation is using shiftfs
         to allow shifted passthrough of some disks to your instance.

         Incus does not support shiftfs but instead relies on a recent
         feature of the Linux kernel instead, VFS idmap.

         If your instances actively rely on shiftfs today, you may need
         to update to a more recent Linux kernel or ZFS version to keep
         using this shifted passthrough features.


The migration is now ready to proceed.
At this point, the source server and all its instances will be stopped.
Instances will come back online once the migration is complete.

Proceed with the migration? [default=no]: 
```

That should do the trick.
