### ISSUE TITLE
Builds from releases fail because of broken OpenFGA canonical imports

### ISSUE THREAD

**Issue by bketelsen** [lxc/incus#315]
# Required information

 * Distribution: all
 * Distribution version: n/a
 * The output of "incus info" or if that fails:
  N/A

# Issue description

OpenFGA oauth2 package declares a canonical import for golang.org/x/oauth2, but the openfga/credentials package imports the code in their package namespace. Go's tooling correctly pulls in golang.org/x/oauth2 and ignores the openfga package. This causes incus builds to fail if dependencies are vendored.

issue: https://github.com/openfga/go-sdk/issues/63
PR: https://github.com/openfga/go-sdk/pull/64

# Steps to reproduce

 1. download released incus
 2. build
 3. observe failure

# Information to attach
See issue in COPR build here: https://github.com/ganto/copr-lxc4/issues/34

Note: this is an issue with a dependency, not Incus directly, but will require dependency updates when upstream is fixed.

**Comment by stgraber** [comment]
The OpenFGA folks have been pretty quick at reviewing and merging fixes so with a bit of luck we'll have that one in time for Incus 0.4 tomorrow.

**Comment by bketelsen** [comment]
https://github.com/openfga/go-sdk/releases/tag/v0.3.1

0.3.1 released with import fix.

**Comment by stgraber** [comment]
Ah, so we've got a bit of a problem with that one...
We can only pull as recent as 0.2.2 for now due to our requirement of still building on Go 1.20...

**Comment by stgraber** [comment]
openfga/go-sdk and mdlayher/socket are the two packages that we currently have to pin to older releases to still be able to build on Go 1.20.

**Comment by stgraber** [comment]
That will go away once Go 1.22 releases as we'll then deprecate support for Go 1.20.

**Comment by stgraber** [comment]
Going to check if there's some creative way around this particular one

**Comment by rhamzeh** [comment]
We can release `v0.3.1-go1.20` if that helps unblock you @stgraber

**Comment by stgraber** [comment]
@rhamzeh that'd be great!

**Comment by rhamzeh** [comment]
Releasing now, warning that there's some breaking changes introduced in the `v0.3.0` release - will submit a draft PR for the update that you can take over

**Comment by rhamzeh** [comment]
Draft PR here: https://github.com/lxc/incus/pull/316, feel free to take over
