### ISSUE TITLE
Cannot attach USB devices without Incus agent running in the VM

### ISSUE THREAD

**Issue by tarruda** [lxc/incus#323]
As explained in https://discuss.linuxcontainers.org/t/cant-attach-usb-device-to-windows-vm/18511/2, attaching a USB device to a VM that doesn't have the Incus agent running fails with `Error: VM agent isn't currently running`. I discovered while trying to attach an external HD to a windows 10 VM.

Incus version: 0.3

**Comment by stgraber** [comment]
The failure appears to be in the event notification path, so the device should still ahve been passed to the VM.
