### ISSUE TITLE
Upgrade with offline cluster member results in whole cluster becoming unavailable

### ISSUE THREAD

**Issue by sesa-me** [lxc/incus#328]
# Required information

 * Distribution: debian
 * Distribution version: bookworm 12.4
 * incus version: 0.3 to 0.4 cluster upgrade

# Issue description

I have a 4 node incus cluster that has been running 0.3 and wanted to upgrade to 0.4. 
One of the cluster nodes has been temporarily powered off for a while so, whilst it was currently unavailable, I had intended to restart it in the future and so had left it configured as a member within the cluster.

Attempting to upgrade each of the 3 nodes that were online resulted in the cluster hanging and becoming unavailable. Each member was waiting for the 4th node to be available and reporting:

 - "Dqlite: attempt 1: server [xxxxx]:8443: dial: Failed connecting to HTTP endpoint ..."
 - "Wait for other cluster nodes to upgrade their versions, cluster not started yet"

Luckily I was able to restart and upgrade the 4th node to get the cluster back online but this might not be possible for others in a similar situations. 

I understand, with hindsight, that it was probably a dumb move to try upgrading the cluster with a missing cluster member, and also understand that removing the offline node first is likely the correct answer. However, the hard failure was a surprise, I had expected the cluster could be formed with the 3 online nodes given there was enough nodes for consensus. It would be nice if incus was able to realise the 4th node wasn't contactable and ignore it when restarting the cluster (appreciating this would then require the 4th node to be upgraded before it was able to rejoin again).

I was also not particularly clear how I could recover from such a situation if I hadn't been able to get the 4th node back online. 

# Steps to reproduce

 1. Create an incus cluster and make one of the cluster members unavailable
 2. Attempt an upgrade
 3. The whole cluster becomes unavailable as it waits for the missing node to be be upgraded and restored to the cluster

**Comment by stgraber** [comment]
https://linuxcontainers.org/incus/docs/main/howto/cluster_manage/#upgrade-cluster-members has a pretty clear warning about exactly this scenario.

https://linuxcontainers.org/incus/docs/main/howto/cluster_recover/ covers the recovery steps in the event that you missed the warning and do have to forcefully kick a server out.

**Comment by stgraber** [comment]
We require all cluster members to upgrade at the same time when the database or API is altered, this is the case going from 0.3 to 0.4. All servers must be available as the database is shared amongst them and in some environments, network (OVN) or storage (Ceph) may also be shared and so require consistent actions across all machines.

**Comment by sesa-me** [comment]
RTFM :) Thanks for the quick update.
