### ISSUE TITLE
launch on a specific cluster group fails

### ISSUE THREAD

**Issue by mtempling** [lxc/incus#335]
I have a cluster with a few members and they are divided into two cluster groups (=g1 and g2).

This command fails:

    $ incus launch images:ubuntu/20.04 c1 --target=@g1 --network=n1
    Creating c1
    Error: Failed loading network "n1": Cluster member not found

The launch command works if I omit the --network option. I tried to force the scheduler.instance config on all members but that did not help.

    $ incus --version
    0.4

**Comment by stgraber** [comment]
Could you show the output of those two `incus launch` runs (with and without --network) while passing `--debug`? That should show the exact API call being made and will make it easier to figure this one out without having to reproduce it first.

**Comment by mtempling** [comment]
incus launch images:ubuntu/20.04 c1 --target=@g1 --debug &> OK
    incus launch images:ubuntu/20.04 c1 --target=@g1 --network=n1 --debug &> NOK
    grep -E '^Error:|Creating c1|url=' OK NOK
    OK:time="2023-12-30T19:24:40+01:00" level=debug msg="Sending request to Incus" etag= method=GET url="http://unix.socket/1.0"
    OK:Creating c1
    OK:time="2023-12-30T19:24:40+01:00" level=debug msg="Sending request to Incus" etag= method=POST url="http://unix.socket/1.0/instances?target=%40g1"
    OK:time="2023-12-30T19:24:40+01:00" level=debug msg="Sending request to Incus" etag= method=GET url="http://unix.socket/1.0/operations/d70b4257-6e61-4cb7-b819-077cbc4c4d8e?target=%40g1"
    OK:time="2023-12-30T19:24:43+01:00" level=debug msg="Sending request to Incus" etag= method=GET url="http://unix.socket/1.0/instances/c1?target=%40g1"
    OK:time="2023-12-30T19:24:43+01:00" level=debug msg="Sending request to Incus" etag= method=PUT url="http://unix.socket/1.0/instances/c1/state?target=%40g1"
    OK:time="2023-12-30T19:24:43+01:00" level=debug msg="Sending request to Incus" etag= method=GET url="http://unix.socket/1.0/operations/9002073e-440c-4b41-ac65-0579f7181b04?target=%40g1"
    NOK:time="2023-12-30T19:26:52+01:00" level=debug msg="Sending request to Incus" etag= method=GET url="http://unix.socket/1.0"
    NOK:Creating c1
    NOK:time="2023-12-30T19:26:52+01:00" level=debug msg="Sending request to Incus" etag= method=GET url="http://unix.socket/1.0/networks/n1?target=%40g1"
    NOK:Error: Failed loading network "n1": Cluster member not found

**Comment by stgraber** [comment]
Sent a fix for this one

**Comment by msperl-github** [comment]
Same issue exists for "incus create"
`incus create docker:vaultwarden/server:latest vaultwarden -c boot.autostart=true -c boot.autorestart=true --network=lxcbr1 --target=@prod
Creating vaultwarden
Error: Failed instance creation: Couldn't find a cluster member for the instance`
