### ISSUE TITLE
Chocolatey link goes to LXD client package instead of incus

### ISSUE THREAD

**Issue by dazoe** [lxc/incus#336]
# Required information
 * Distribution: N/A 
 * Distribution version: N/A
 * The output of "incus info" or if that fails:
   * Kernel version: N/A
   * LXC version: N/A
   * Incus version: N/A
   * Storage backend in use: N/A

# Issue description

https://github.com/lxc/incus/blob/2dd6ad074656dd1d510eef000406a5c5715c1917/doc/installing.md?plain=1#L172
should be updated to https://community.chocolatey.org/packages/incus.

# Steps to reproduce
  * N/A

# Information to attach
  * N/A

**Comment by stgraber** [comment]
Ah yeah, we were waiting for it to finally get published before changing the link, but then forgot to actually do it :)

I've sent a branch to fix this now, thanks!
