### ISSUE TITLE
Don't expand ipvX.address/ipvX.nat when joining a cluster

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#338]
When creating a new network as part of joining a cluster, the resulting network should not have `ipv4.address/ipv6.address` and `ipv4.nat/ipv6.nat` get filled in when not present in the database.

Instead they should be treated as equivalent to `none` and `false` avoiding an error during joining.

**Comment by vivekkoya** [comment]
https://github.com/lxc/incus/blob/main/internal/server/db/network_zones.go
In line 232, should the ? marks be replaced with the ipv4/6 address/nat filled in. Is that what you are referring to? Thanks

**Comment by stgraber** [comment]
No, it's not, that file is about network zones.

It's likely the calls to `FillConfig` in `cmd/incusd/networks.go` that need to be made conditional on whether the network is being added as part of cluster join rather than as an initial creation request.
