### ISSUE TITLE
Disable OVN gateway chassis when evacuated

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#340]
As a machine that's evacuated is likely to be going down shortly thereafter, it would make sense for the evacuated state to be tied to either a disabled OVN gateway chassis state or at least a much lower chassis priority.

**Comment by Abhiram824** [comment]
Could we be assigned to this as well please?

**Comment by stgraber** [comment]
For this one, you're going to want to look at `cmd/incusd/api_cluster.go` for the evacuation logic.

The easiest way to have the chassis disabled is going to be by stopping all networks while evacuated. So loading all local networks and calling `Stop()` on them should do that fine.

You'll also need to add a check to `cmd/incusd/daemon.go` so that on system startup the networks don't get started when the machine is evacuated (look for `networkStartup`).

Then you'll need logic in the evacuation restore logic to start the networks back up once the system is fully restored.

**Comment by Abhiram824** [comment]
Hello! We made some progress and created a draft PR. Does our initial approach look correct? 
https://github.com/lxc/incus/pull/747

**Comment by dhruvvnistala** [comment]
Hi, commenting on this post as per our discussion on https://github.com/lxc/incus/issues/340
