### ISSUE TITLE
Setting the openfga properties breaks incus admin init --preseed

### ISSUE THREAD

**Issue by rgl** [lxc/incus#341]
# Required information

 * Distribution: Debian
 * Distribution version: 12
 * The output of "incus info" or if that fails:
   * Kernel version: `Linux incus 6.1.0-16-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux`
   * LXC version:
   * Incus version: 0.4
   * Storage backend in use: btrfs

# Issue description

Setting the openfga properties as (full example at https://github.com/rgl/incus-playground/blob/main/provision-incus.sh#L124-L133):

```bash
incus admin init --preseed <<EOF
config:
  openfga.api.url: https://$openfga_domain:8080
  openfga.api.token: abracadabra
  openfga.store.id: $(jq .store.id /vagrant/shared/openfga-incus.json)
...
EOF
```

breaks `incus admin init --preseed` with the error:

```
incus: Error: Failed to create storage pool "default": Post "http://unix.socket/1.0/storage-pools": EOF
```

Please note that configuring the openfga properties after the initial `incus admin init --preseed` works fine.

# Steps to reproduce

 1. At `incus admin init --preseed` time set the openfga properties as described in this issue description. 
 2. See the error.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`incus info NAME --show-log`)
 - [ ] Container configuration (`incus config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/incus/incusd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the issue)

**Comment by stgraber** [comment]
Can you look for a stack trace in your `journalctl -n 300` output or in /var/log/incus/incusd.log?

**Comment by rgl** [comment]
here are the logs:

```console
root@incus:~# journalctl -u incus
dez 29 07:29:07 incus systemd[1]: Starting incus.service - Incus - Daemon...
dez 29 07:29:07 incus incusd[6282]: time="2023-12-29T07:29:07Z" level=warning msg=" - Couldn't find the CGroup hugetlb controller, hugepage limits will be ignored"
dez 29 07:29:07 incus incusd[6282]: time="2023-12-29T07:29:07Z" level=warning msg=" - Couldn't find the CGroup network priority controller, per-instance network priority will be ignored. Please use p>
dez 29 07:29:08 incus systemd[1]: Started incus.service - Incus - Daemon.

root@incus:~# 
```

**Comment by stgraber** [comment]
Thanks, that should make it easy to fix!

**Comment by stgraber** [comment]
@rgl could you share the full preseed file?

I've tried with your snippet as well as a similar snippet also including a storage pool definition, but this doesn't trigger the crash.

**Comment by rgl** [comment]
@stgraber you mean https://github.com/rgl/incus-playground/blob/main/provision-incus.sh#L133-L167?

**Comment by stgraber** [comment]
Oops, I missed that link earlier, sorry :)

**Comment by stgraber** [comment]
Got the fault reproduced here.
