### ISSUE TITLE
a user in the operator role cannot launch an instance

### ISSUE THREAD

**Issue by rgl** [lxc/incus#346]
# Required information

 * Distribution: Debian
 * Distribution version: 12
 * The output of "incus info" or if that fails:
   * Kernel version:
   * LXC version:
   * Incus version: 0.4
   * Storage backend in use: btrfs

# Issue description

I've created the `bob` user in the `operator` role with:

```bash
incus project create foo
fga tuple write \
  user:bob@pandora.incus.test \
  operator \
  project:foo
```

But `bob` is not able to start an instance with:

```console
vagrant@pandora:~$ install -d -m 700 .config{,/incus}

vagrant@pandora:~$ incus remote add incus.test --auth-type oidc
URL: https://pandora.incus.test:8443/realms/pandora/device?user_code=XXGH-CKLV
Code: XXGH-CKLV

vagrant@pandora:~$ incus info incus.test: | grep auth_ # check your user information.
- auth_pki
- auth_user
auth_methods:
auth_user_name: bob@pandora.incus.test
auth_user_method: oidc

vagrant@pandora:~$ incus list incus.test:
+------+-------+------+------+------+-----------+
| NAME | STATE | IPV4 | IPV6 | TYPE | SNAPSHOTS |
+------+-------+------+------+------+-----------+

vagrant@pandora:~$ incus project list incus.test:
+---------------+--------+----------+-----------------+-----------------+----------+---------------+-------------+---------+
|     NAME      | IMAGES | PROFILES | STORAGE VOLUMES | STORAGE BUCKETS | NETWORKS | NETWORK ZONES | DESCRIPTION | USED BY |
+---------------+--------+----------+-----------------+-----------------+----------+---------------+-------------+---------+
| foo (current) | YES    | YES      | YES             | YES             | NO       | NO            |             | 1       |
+---------------+--------+----------+-----------------+-----------------+----------+---------------+-------------+---------+

vagrant@pandora:~$ incus launch images:debian/12 incus.test:debian-ct
Creating debian-ct
Error: Failed instance creation: Failed creating instance record: Failed initialising instance: Failed getting root disk: No root device could be found
``` 

Please note that the image was correctly downloaded, as we can later see with:

```console
vagrant@pandora:~$ incus image list incus.test:
+-------+--------------+--------+----------------------------------------+--------------+-----------+----------+-------------------------------+
| ALIAS | FINGERPRINT  | PUBLIC |              DESCRIPTION               | ARCHITECTURE |   TYPE    |   SIZE   |          UPLOAD DATE          |
+-------+--------------+--------+----------------------------------------+--------------+-----------+----------+-------------------------------+
|       | 0d7020c2928b | no     | Debian bookworm amd64 (20231229_05:24) | x86_64       | CONTAINER | 94.36MiB | Dec 29, 2023 at 12:57pm (UTC) |
+-------+--------------+--------+----------------------------------------+--------------+-----------+----------+-------------------------------+
```

From my interpretation of `operator` role at https://linuxcontainers.org/incus/docs/main/authorization/#openfga-model it should be able to create an instance.

Please note that the above steps work as expected with a user in the `admin` role created as:

```bash
fga tuple write \
  user:alice@pandora.incus.test \
  admin \
  server:incus
```

# Steps to reproduce

 1. See the description.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`incus info NAME --show-log`)
 - [ ] Container configuration (`incus config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/incus/incusd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the issue)

**Comment by stgraber** [comment]
From the error it sounds like your `default` profile in that project hasn't been configured and so lacks a root device.

**Comment by stgraber** [comment]
A quick shortcut for the simpler cases is `incus profile show default --project default | incus profile edit default --project new-project` to effectively copy anything that was in the default profile of the default project, but in many cases you'll want to customize things a bit.

**Comment by rgl** [comment]
that was it. thank you!
