### ISSUE TITLE
Lxd-to-incus should also look in /var/snap/lxd

### ISSUE THREAD

**Issue by mgariepy** [lxc/incus#348]
# Required information

 * Distribution: Arch linux
 * Distribution version:
 * The output of "incus info" or if that fails:
 * 
   * Kernel version:
   * LXC version:
   * Incus version:
   * Storage backend in use:

# Issue description
 lxd-to-incus fail with 

```
=> Looking for source server
Error: No source server could be found
```

# Steps to reproduce

https://github.com/lxc/incus/blob/main/cmd/lxd-to-incus/sources_snap.go#L14C1-L20

looking at this if the /snap/lxd directory doesn't exist it can't fall back to /var/snap/

# workaround

creating the /snap/lxd dir pass the check and the lxd-to-incus can be launched sucessfully.

**Comment by stgraber** [comment]
`/var/snap/lxd` isn't an equivalent of `/snap/lxd`, what path is used as the equivalent on your platform? It's probably something under `/var/lib/snap` or the like.

**Comment by stgraber** [comment]
You should be able to easily tell by looking at `/proc/mounts` and seeing where the .snap files are mounted.

**Comment by mgariepy** [comment]
they were mounted in /var/lib/snapd/snap
