### ISSUE TITLE
support fish shell   completions

### ISSUE THREAD

**Issue by djemilbakhti** [lxc/incus#367]

**Comment by stgraber** [comment]
`incus completion fish` using a daily build will work fine.

**Comment by djemilbakhti** [comment]
> `incus completion fish` using a daily build will work fine.

not working on archlinux

**Comment by stgraber** [comment]
That's because it's not using a daily build :)

It will be in Incus 0.5.

**Comment by symgryph** [comment]
Just an FYI works FINE now on alpine (someone was nice and made a package for alpine!)
