### ISSUE TITLE
Bash completion broken with `incus-user`

### ISSUE THREAD

**Issue by gibmat** [lxc/incus#377]
I hope this isn't a user or packaging error on my end, but in Incus 0.4 it appears that bash completion is broken if a normal user is setup to use `incus-user` via being a member of the "incus" group. The function `_incus_names()` tries to get the current project by searching for "(current)", which isn't included in the output of `incus project list`:

```
$ incus project list
+-----------+--------+----------+-----------------+-----------------+----------+---------------+---------------------------------------------+---------+
|   NAME    | IMAGES | PROFILES | STORAGE VOLUMES | STORAGE BUCKETS | NETWORKS | NETWORK ZONES |                 DESCRIPTION                 | USED BY |
+-----------+--------+----------+-----------------+-----------------+----------+---------------+---------------------------------------------+---------+
| user-1000 | YES    | YES      | YES             | YES             | NO       | YES           | User restricted project for "gibmat" (1000) | 2       |
+-----------+--------+----------+-----------------+-----------------+----------+---------------+---------------------------------------------+---------+

$ sudo incus project list
+-------------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------------------------------+---------+
|       NAME        | IMAGES | PROFILES | STORAGE VOLUMES | STORAGE BUCKETS | NETWORKS | NETWORK ZONES |                 DESCRIPTION                 | USED BY |
+-------------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------------------------------+---------+
| default (current) | YES    | YES      | YES             | YES             | YES      | YES           | Default Incus project                       | 4       |
+-------------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------------------------------+---------+
| user-1000         | YES    | YES      | YES             | YES             | NO       | YES           | User restricted project for "gibmat" (1000) | 2       |
+-------------------+--------+----------+-----------------+-----------------+----------+---------------+---------------------------------------------+---------+
```

When trying to auto-complete a command like `incus start <container>`, instead of a completion you get the error `Error: User does not have permissions for project "default"`.

If my user is a member of the "incus-admin" group, auto-completion works correctly.

**Comment by stgraber** [comment]
Ah, that should be an easy fix. We'd still want `(current)` to show up in this situation.

**Comment by stgraber** [comment]
@gibmat I'm not able to reproduce this with a clean user here.

**Comment by stgraber** [comment]
I can artificially cause it by mangling the config.yml though, so I can still work on a workaround for this situation, but it shouldn't happen for a clean user.

**Comment by gibmat** [comment]
OK, does that indicate I've done something wrong with the packaging? I don't see any `config.yml` in the source, so is that auto-created on a per-user basis, or maybe is a different `config.yml` left over from prior testing? (I haven't been wiping and re-creating my test account, although I have been fully purging the system level packages.)

I can do some more testing later today.

**Comment by stgraber** [comment]
~/.config/incus/config.yml

This is generated on first use of the CLI.

You can reproduce your issue if the user isn't a member of the incus group on first CLI use but is then subsequently added to that group.

**Comment by gibmat** [comment]
That was it, thanks!
