### ISSUE TITLE
Better error messages in client

### ISSUE THREAD

**Issue by mcondarelli** [lxc/incus#406]
I have been bitten by having forgotten a piece of documentation.

I tried to migrate a **_running_** container with:
```
incus copy lxd:webserver incus:webserver --no-profiles --instance-only
```
It consistently failed after 2.64G with message:
```
Error: Failed instance creation: Error transferring instance data: Failed migration on target: Error reading migration control source: websocket: close 1000 (normal)
```
Which I failed to understand.

Only when I thought about looking at sender server logs (`ssh root@lxd -- tail /var/log/incus/incusd.log`) I found:
```
time="2024-01-19T14:38:57+01:00" level=error msg="Failed migration on source" clusterMoveSourceName= err="migration dump failed\n(00.126004) Error (criu/namespaces.c:460): Can't dump nested uts namespace for 287003\n(00.126020) Error (criu/namespaces.c:721): Can't make utsns id\nError (criu/util.c:627): execvp(\"iptables-restore\", ...) failed: No such file or directory\n(00.132875) Error (criu/util.c:642): exited, status=1\nError (criu/util.c:627): execvp(\"ip6tables-restore\", ...) failed: No such file or directory\n(00.135282) Error (criu/util.c:642): exited, status=1\n(00.135963) Error (criu/cr-dump.c:2098): Dumping FAILED." instance=webserver live=true project=default push=false
```
This finally triggered my memory and I stopped the container prior to migration.

If at all possible I would suggest to issue a more explicit message on client side, better yet would be to check if container (with network) is running and refuse directly to attempt migration without waiting for failure.

Many Thanks in Advance

**Comment by stgraber** [comment]
Yeah, we should be able to get a better error in this case for sure.

Incus attempted a container live migration given your container was running, that's the normal behavior, but that live migration failed (as most do). As it failed "cleanly", there's no reason why that error should haven't propagated back to the client.

**Comment by stgraber** [comment]
Got the exact error reproduced here in a dev environment so should be pretty easy to sort out a fix now.
