### ISSUE TITLE
ZFS Storage Volume Refresh Fails

### ISSUE THREAD

**Issue by slapcat** [lxc/incus#413]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "incus info" or if that fails:
   * Kernel version: 5.15.0-91-generic
   * LXC version: N/a
   * Incus version: 0.4-202312232115
   * Storage backend in use: ZFS

# Issue description

As [advised by stgraber](https://discuss.linuxcontainers.org/t/zfs-storage-volume-refresh-fails/18714/1), I am raising an issue about ZFS storage volumes failing to refresh in a cluster recently migrated from LXD. Here is the error:

```
$ incus storage volume cp local/apache2 local/apache2 --target=daphne --destination-target=yogi --refresh
Error: Failed to run: zfs snapshot -r local/custom/default_apache2@copy-4684ffb1-fbe7-47a7-8af1-8431be5f70e9: exit status 2 (cannot open 'local/custom/default_apache2': dataset does not exist
usage:
	snapshot [-r] [-o property=value] ... <filesystem|volume>@<snap> ...

For the property list, run: zfs set|get

For the delegated permission list, run: zfs allow|unallow)
```

# Steps to reproduce

1. incus storage volume create local test-refresh --target daphne
2. incus storage volume snapshot create local test-refresh snap0 --target daphne
3. incus storage volume copy local/test-refresh local/test-refresh --target daphne --destination-target yogi
4. incus storage volume snapshot create local test-refresh snap1 --target daphne
5. incus storage volume copy local/test-refresh local/test-refresh --target daphne --destination-target yogi --refresh
6. incus storage volume snapshot delete local test-refresh snap1 --target daphne
7. incus storage volume copy local/test-refresh local/test-refresh --target daphne --destination-target yogi --refresh

Error from this test:
```
incus storage volume copy local/test-refresh local/test-refresh --target daphne --destination-target yogi --refresh
Error: Failed to transfer main volume: Failed to wait for receiver: cannot receive: failed to read from stream cannot restore to local/custom/default_test-refresh@snapshot-52a9bddd-988f-49fd-a603-8fe0037bd37e: destination already exists : exit status 1
```

I'm happy to provide any more information you may need.

**Comment by stgraber** [comment]
Got the issue reproduced here, I'll work out a fix for it tomorrow.

**Comment by stgraber** [comment]
Oh, I think I know what's going on.
