### ISSUE TITLE
shell command is missing from help

### ISSUE THREAD

**Issue by carlotm** [lxc/incus#421]
# Required information

 * Distribution: Arch Linux

# Issue description

the command `shell` should be included in the `help` output, under the `Available Commands` section

# Steps to reproduce

 1. Run `incus help`

**Comment by stgraber** [comment]
That's because it's not an actual command, instead it's a built-in alias.
That's why `incus shell --help` for example shows you the `incus exec` help message.

**Comment by stgraber** [comment]
That's also why you'll never see us refer to `incus shell` in our documentation. All examples use `incus exec` directly.

**Comment by carlotm** [comment]
Gotcha, thank you!
