### ISSUE TITLE
Incus fails to launch VM because zvol_id is not found

### ISSUE THREAD

**Issue by mkgvt** [lxc/incus#424]
# Required information

 * Distribution: NixOS
 * Distribution version: 23.11
 * The output of "incus info" or if that fails:
   * Kernel version: 6.6.77
   * LXC version: 4.0.2 (I think)
   * Incus version: 0.2
   * Storage backend in use: zfs

[incus-info.log](https://github.com/lxc/incus/files/14026789/incus-info.log)

```console
$ incus version
Client version: 0.2
Server version: 0.2
```

# Issue description

Launching a VM with Incus on NixOS 23.11 using ZFS as the storage backend fails with the error message: `Error: Failed instance creation: Failed creating instance from image: exec: "zvol_id": executable file not found in $PATH`. Launching the corresponding container works fine.

I am not sure if this is an Incus issue or a [nixpkgs](https://github.com/NixOS/nixpkgs/issues/283250) issue.

# Steps to reproduce

1. `incus launch images:ubuntu/22.04/desktop test --vm --console=vga` (The specific image doesn't seem to matter.)
2. Wait while the VM is created... It exits with the error message above.
3. Verify that `zvol_id` is installed at `ls $(readlink $(which zfs) | sed 's:/bin.*::')/lib/udev/zvol_id` just not being found.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`incus info NAME --show-log`)
 - [ ] Container configuration (`incus config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/incus/incusd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the issue)

**Comment by adamcstephens** [comment]
This is a NixOS problem, so this issue can be closed.

**Comment by adamcstephens** [comment]
Actually @stgraber maybe this is an incus issue. Am I reading this correctly that zvol_id is only checked in `/lib/udev/zvol_id` ?

https://github.com/lxc/incus/blob/e5690705e842d3961d8a1d18c0ec002c25345af8/internal/server/storage/drivers/driver_zfs_volumes.go#L1811

**Comment by stgraber** [comment]
Yeah, we check in both places. A lot of distros don't ship with zvol_id in the path.

**Comment by adamcstephens** [comment]
Yeah NixOS doesn’t either, but I can expose it for the incusd service.
