### ISSUE TITLE
suggestion: Add a question for the proxie(s) to 'admin init'

### ISSUE THREAD

**Issue by marneu** [lxc/incus#438]
Mostly, if using a proxy for the setup, the _admin init_ needs a followed _incus config edit_ to set the proxy as a one time task.
This could also come from the distro setting.

**Comment by stgraber** [comment]
This is too niche a question to ask everyone during `init`.
Most packages, at least those I'm making will respect `/etc/environment` and will load `http_proxy` and `https_proxy` from there.

So a system that's normally configured for system-wide proxy configuration will just work without needing to use the Incus config keys. Those config keys are only for the few cases where you either don't want to enable your proxy system-wide or need to use a different proxy just for Incus.
