### ISSUE TITLE
Switch to using minio's `mc` client

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#450]
Minio has moved its madmin-go to AGPLv3 some time ago, making it unsuitable for use within Incus.

We've so far been able to avoid this issue by sticking to an older version of the package which was still under Apache 2.0. Unfortunately recent Minio has now deprecated the service API supported by that older version of the admin client.

As a result, we need to either switch to another Go package to handle admin functions or need to switch to the `mc` command line tool instead.

**Comment by dontlaugh** [comment]
Was [SeaweedFS](https://github.com/seaweedfs/seaweedfs?tab=readme-ov-file#example-using-seaweed-object-store) ever evaluated? It looks like a more complex project, but it's Apache licensed.

**Comment by stgraber** [comment]
I believe it was back when we were looking at adding S3 storage support and indeed felt like even more of a beast than minio.

I'm hoping that replacing the few admin API calls we have today with command line calls ends up being pretty simple. If we have to somehow completely switch away from minio, I suspect it will be far easier for us to just natively provide our own S3 API than to rely on a 3rd party solution to do that.

**Comment by presztak** [comment]
Hey @stgraber , if you don't mind I can start working on that one.

**Comment by stgraber** [comment]
That'd be great!

**Comment by knutov** [comment]
just wonder - how name conflict with midnight commander (`mc`) is solved here?

**Comment by stgraber** [comment]
The code supports both `mc` and `mcli` as names for the minio client.

It checks the `--version` output for the expected `mc version XYZ` pattern from a valid MinIO client, if it doesn't get it, it will fallback to looking for `mcli` instead.
