### ISSUE TITLE
Support custom file permissions in templates

### ISSUE THREAD

**Issue by stefanor** [lxc/incus#465]
# Issue description

Currently image metadata template files are written with mode 644, to write executables, it would be useful to be able to customize this.

Why is that handy? Templates are a fairly straightforward way to inject content into an image when importing it into Incus. Sometimes you want to inject something executable.

My use-case here is to inject `lxc.generator` into arbitrary images that we import into Incus as part of https://salsa.debian.org/freexian-team/debusine/-/issues/271 I can work-around this by appending an executable file to the image tarball, instead of using metadata templates.

**Comment by stgraber** [comment]
Makes sense, we can easily add `mode`, `uid` and `gid` to make things consistent with how we generally handle files.
