### ISSUE TITLE
Disable the architecture check on `incus copy` or add a flag to disable this.

### ISSUE THREAD

**Issue by phol** [lxc/incus#478]
# Issue description

Created after this [discussion](https://discuss.linuxcontainers.org/t/can-the-architecture-check-of-incus-be-disabled-on-copy/18996)

I’m happily using a combination of amd64 and arm64 machines with incus.
My main server is arm64. My backup server is amd64.
Both are using a btrfs storage backend.

I can succesfully snapshot and copy containers between amd64 machines.
However, when I try to copy from arm64 to amd64, Incus doesn’t let me as it does an architecture check:

```sh
incus copy av backupserver:av
```

```log
Error: Failed instance creation: Failed creating instance record: Requested architecture isn't supported by this host
```

I understand that this is a reasonable response. 
However, I only want to copy the containers for backup purposes, not to actually run them.
I’ve tried to figure out if there is a way to ignore this check, but I haven’t been able to find one.
Is there any way to override this behaviour, such as adding something like an --ignore-arch flag?

I’ve also tried only copying the storage volume, but that doesn’t work either as the volume belongs to a machine. Therefore, the following command also doesn’t work

```sh
incus storage volume copy default/av/snap1 backupserver:default/av 
```

```log
Error: Storage pool not found
```

This makes sense, as when adding the --debug flag, it shows that it goes to the default/volumes/custom path:

```log
etag= method=GET url="http://unix.socket/1.0/storage-pools/default/volumes/custom/av"
```

# Steps to reproduce

 1. Machine A runs on ARM64
 2. Machine B runs on AMD64
 3. Try to `incus copy` a container.

**Comment by presztak** [comment]
@stgraber can I take that one?

**Comment by stgraber** [comment]
Yep!

**Comment by presztak** [comment]
@stgraber which approach do you prefer? Disabling check or adding new flag?

**Comment by stgraber** [comment]
I'd just disable the check for such copies/migrations.

If asked to create an instance from an image or backup or something, that should still fail, but when just getting an existing instance moved in, we shouldn't check it. We'll obviously want to make sure that we don't allow trying to start such an instance though.
