### ISSUE TITLE
Containers should not be placed directly inside of a root cgroup in systemd based systems

### ISSUE THREAD

**Issue by webczat** [lxc/incus#492]
# Required information

 * Distribution: fedora
 * Distribution version: 39
 * The output of "incus info" or if that fails:

config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- network_sriov
- console
- restrict_dev_incus
- migration_pre_copy
- infiniband
- dev_incus_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- dev_incus_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- backup_compression
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
- server_trusted_proxy
- clustering_update_cert
- storage_api_project
- server_instance_driver_operational
- server_supported_storage_drivers
- event_lifecycle_requestor_address
- resources_gpu_usb
- clustering_evacuation
- network_ovn_nat_address
- network_bgp
- network_forward
- custom_volume_refresh
- network_counters_errors_dropped
- metrics
- image_source_project
- clustering_config
- network_peer
- linux_sysctl
- network_dns
- ovn_nic_acceleration
- certificate_self_renewal
- instance_project_move
- storage_volume_project_move
- cloud_init
- network_dns_nat
- database_leader
- instance_all_projects
- clustering_groups
- ceph_rbd_du
- instance_get_full
- qemu_metrics
- gpu_mig_uuid
- event_project
- clustering_evacuation_live
- instance_allow_inconsistent_copy
- network_state_ovn
- storage_volume_api_filtering
- image_restrictions
- storage_zfs_export
- network_dns_records
- storage_zfs_reserve_space
- network_acl_log
- storage_zfs_blocksize
- metrics_cpu_seconds
- instance_snapshot_never
- certificate_token
- instance_nic_routed_neighbor_probe
- event_hub
- agent_nic_config
- projects_restricted_intercept
- metrics_authentication
- images_target_project
- cluster_migration_inconsistent_copy
- cluster_ovn_chassis
- container_syscall_intercept_sched_setscheduler
- storage_lvm_thinpool_metadata_size
- storage_volume_state_total
- instance_file_head
- instances_nic_host_name
- image_copy_profile
- container_syscall_intercept_sysinfo
- clustering_evacuation_mode
- resources_pci_vpd
- qemu_raw_conf
- storage_cephfs_fscache
- network_load_balancer
- vsock_api
- instance_ready_state
- network_bgp_holdtime
- storage_volumes_all_projects
- metrics_memory_oom_total
- storage_buckets
- storage_buckets_create_credentials
- metrics_cpu_effective_total
- projects_networks_restricted_access
- storage_buckets_local
- loki
- acme
- internal_metrics
- cluster_join_token_expiry
- remote_token_expiry
- init_preseed
- storage_volumes_created_at
- cpu_hotplug
- projects_networks_zones
- network_txqueuelen
- cluster_member_state
- instances_placement_scriptlet
- storage_pool_source_wipe
- zfs_block_mode
- instance_generation_id
- disk_io_cache
- amd_sev
- storage_pool_loop_resize
- migration_vm_live
- ovn_nic_nesting
- oidc
- network_ovn_l3only
- ovn_nic_acceleration_vdpa
- cluster_healing
- instances_state_total
- auth_user
- security_csm
- instances_rebuild
- numa_cpu_placement
- custom_volume_iso
- network_allocations
- zfs_delegate
- storage_api_remote_volume_snapshot_copy
- operations_get_query_all_projects
- metadata_configuration
- syslog_socket
- event_lifecycle_name_and_project
- instances_nic_limits_priority
- disk_initial_volume_configuration
- operation_wait
- image_restriction_privileged
- cluster_internal_custom_volume_copy
- disk_io_bus
- storage_cephfs_create_missing
- instance_move_config
- ovn_ssl_config
- certificate_description
- disk_io_bus_virtio_blk
- loki_config_instance
- instance_create_start
- clustering_evacuation_stop_options
- boot_host_shutdown_action
- agent_config_drive
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
auth_user_name: webczat
auth_user_method: unix
environment:
  addresses: []
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIB+DCCAX6gAwIBAgIRAI8WMe7zBWZgoPRJMy9cxMMwCgYIKoZIzj0EAwMwLzEZ
    MBcGA1UEChMQTGludXggQ29udGFpbmVyczESMBAGA1UEAwwJcm9vdEB3bGFwMB4X
    DTI0MDIxMzEzNTkxOVoXDTM0MDIxMDEzNTkxOVowLzEZMBcGA1UEChMQTGludXgg
    Q29udGFpbmVyczESMBAGA1UEAwwJcm9vdEB3bGFwMHYwEAYHKoZIzj0CAQYFK4EE
    ACIDYgAETfqkPHcdW2BRosfPeN2ebu5AqqtNBLQ2121kwznwObFKTdJ5fFR5MfBP
    j7fNqUzh3BlZI8evOEn5EzApL/MvhbEDO7RcC3Ok6XpGKHyTzuBkOYA9adke9DzK
    34ynW14ho14wXDAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYIKwYBBQUHAwEw
    DAYDVR0TAQH/BAIwADAnBgNVHREEIDAeggR3bGFwhwR/AAABhxAAAAAAAAAAAAAA
    AAAAAAABMAoGCCqGSM49BAMDA2gAMGUCMQDQSV+Ieuz0AQ07Xoe4cGnsab0PLzj2
    3uHBB7UE47acBx/QPMzcdL5pJaLQjAV6JL0CMDpKMyfTku4aFQB7Auzh9T9JJvur
    Q1X6a+R+09PLUVay+U7XHv8YjM7F3TM9jLNjCg==
    -----END CERTIFICATE-----
  certificate_fingerprint: 602347e37baf566d70b7e1ef8691a8cf64d8cc95b71ea0f96aafda9d38f05c79
  driver: lxc | qemu
  driver_version: 5.0.3 | 8.1.3
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 6.7.4-200.fc39.x86_64
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Fedora Linux
  os_version: "39"
  project: default
  server: incus
  server_clustered: false
  server_event_mode: full-mesh
  server_name: wlap
  server_pid: 6321
  server_version: 0.5.1
  storage: lvm
  storage_version: 2.03.23(2) (2023-11-21) / 1.02.197 (2023-11-21) / 4.48.0
  storage_supported_drivers:
  - name: dir
    version: "1"
    remote: false
  - name: lvm
    version: 2.03.23(2) (2023-11-21) / 1.02.197 (2023-11-21) / 4.48.0
    remote: false
  - name: btrfs
    version: "6.7"
    remote: false

   * Kernel version:6.7.4
   * LXC version:5.0.3
   * Incus version:0.5.1
   * Storage backend in use:lvm

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

From what I know, systemd doesn't recommend running anything, like containers, in the root cgroup directly, and instead offers a delegation feature where some service/scope cgroup
is delegated and subcgroups can be created inside.
However, incus/lxc seems to create their cgroups in the root cgroup. Unsure if this can cause problems in the future or not.
In addition, at least on my fedora, the .service file of incus has Delegate=yes set, which would be redundant in case where root cgroup is used directly.
In addition it seems it also force-enables cgroup controllers systemd didn't in the root cgroup?

# Steps to reproduce

 1. Run any container.
 2. Observe that groups starting with lxc appear directly under /sys/fs/cgroup in the host.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`incus info NAME --show-log`)
 - [ ] Container configuration (`incus config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/incus/incusd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the issue)

**Comment by stgraber** [comment]
Yeah, this is intentional:
 - We support far more than just systemd systems so can't rely on systemd for cgroup management and would rather have the same cgroup characteristics across all distributions
 - Systemd has (at least historically) been missing support for a number of cgroup controllers that we rely on making relying solely on scope/slice unfeasible
 - Delegate=true is still required to prevent systemd from disabling resource controllers in some situations. It's a very odd behavior we ran into back in the LXD days where when the last Delegate=true unit stops, systemd performs some kind of cgroup cleanup, leading to unused controllers getting disabled
 - There is a cost to cgroup depth, so needlessly adding depth to the cgroup tree isn't usually considered a good idea

In general while this indeed doesn't follow systemd's own recommendations, we've been pretty careful to not cause any bad interactions with systemd's own cgroup usage model. We also have a very good relationship with the systemd upstream folks so tend to get advance notice of anything that could affect us ;)


Closing as we're not planning on changing logic on the Incus side. There is some potential for supporting systemd's cgroup API directly in low-level LXC though as that would enable simpler user-owned unprivileged containers (our instructions there currently use systemd-run for that case).

**Comment by webczat** [comment]
okay, if the systemd folks know about this behavior and so on, then...
As for missing controllers, I think nowadays the only missing controller you support but systemd does not is hugetlb. Previously it was different.

**Comment by stgraber** [comment]
Yeah, the issue with that is that we still need to run on pretty old distributions which are missing a lot more than just hugetlb :)

The common saying within the team is that if we need anything from the base OS (kernel, systemd, ...) we basically need that feature to have been around for at least 5 years for us to be able to rely on it being around...

**Comment by webczat** [comment]
that's fair. i just noticed the page describing systemd's delegation behavior is itself from around 5 years ago. Was curious if systemd's official stance has since lifted, especially about what you are doing... maybe not about force-enabling controllers, still talking about using a root cgroup.
Because imo realistically, systemd might manage root cgroup attrs like controllers, and services within, but why would it even want to step on people making arbitrary groups in that specific place? Maybe if I'm so curious I should ask on systemd list instead. The only thing I can think of is probably not that realistic, in theory putting containers in some service cgroup can allow me to give some global unmodifiable resource allocation for all containers, except of course that it's mood if moving to root cgroup is still possible as the process is privileged.

**Comment by stgraber** [comment]
I haven't checked recently so I may be wrong, but I thought that the controller selection was hierarchical in cgroup2, so you need to enable all the controllers at the root if you want any descendant to be able to select them.

Incus will run fine when put inside of a cgroup and it should detect what controllers are available at that level, so if it's something you want to do and you can get systemd to enable all the controllers that we care about then that should be okay. However you need to be careful about systemd's process tracking mode as you don't want `systemctl restart incus` to kill everything in the cgroup as that would also kill all the containers, VMs, ... in the process :)

**Comment by zstas** [comment]
sorry guys for writing in the closed issue. 

how one could force incus to run all the containers inside some parent cgroup?
I have a custom dataplane (for network) and I want to fully isolate on system level 2 cores for dataplane and let incus use the rest cores. I could of course give cpuset for every container but I'd like to achieve it w/o using it.

my initial plan was to use systemd system.slice to run all the userspace + containers, but despite the incus process started in system.slice - all the cgroups for containers are created in the root.

**Comment by stgraber** [comment]
The easiest should be to set `raw.lxc` to `lxc.cgroup.relative=1` in your `default` profile.
