### ISSUE TITLE
Unable to launch VMs on LVM with XFS filesystem 

### ISSUE THREAD

**Issue by rnalrd** [lxc/incus#498]
# Required information

 * Distribution: Alpine
 * Distribution version: edge
 * The output of "incus info" or if that fails:
   * Kernel version: 6.6.16-0-lts
   * LXC version: 5.0.3
   * Incus version: 0.5.1
   * Storage backend in use: LVM

# Issue description

Cannot launch any VM when XFS filesystem is in use:

```
test3:~# incus launch images:ubuntu/focal vm1 --vm -c security.secureboot=false -s lvm-xfs
Launching vm1
Error: Failed instance creation: Failed creating instance from image: Error creating LVM logical volume: Error making filesystem on LVM logical volume: Failed to run: mkfs.xfs /dev/lvm-xfs/images_747d9a78d926f33484bb5b7b50140f6f9f5e579a22ba0e7cacee629e703ba681: exit status 1 (mkfs.xfs: small data volume, ignoring data volume stripe unit 128 and stripe width 128
Filesystem must be larger than 300MB.
```

It appears to be a specific issue on Alpine. I am unable to reproduce the problem on Ubuntu Jammy.

# Steps to reproduce

 1. `incus storage create lvm-xfs lvm volume.block.filesystem=xfs source=/dev/X`
 2. `incus launch images:ubuntu/focal vm1 --vm -c security.secureboot=false -s lvm-xfs`

# Information to attach

During the execution of step 2 and before it fails, `lvs` shows that a 100MB volume is created:
```
  IncusThinPool                                                                 lvm-xfs  twi-aotz-- <11.15g                      5.56   12.47                           
  images_42545ab57e5e39eb38ce965daf290e016da6b82f80d0bf7da3928b1d7a2f7a56       lvm-xfs  Vwi---tz-k  10.00g IncusThinPool                                               
  images_747d9a78d926f33484bb5b7b50140f6f9f5e579a22ba0e7cacee629e703ba681       lvm-xfs  Vwi-a-tz-- 100.00m IncusThinPool        0.00                                   
  images_747d9a78d926f33484bb5b7b50140f6f9f5e579a22ba0e7cacee629e703ba681.block lvm-xfs  Vwi-a-tz-k  10.00g IncusThinPool        0.00        
```

**Comment by rnalrd** [comment]
[incus-launch-debug.txt](https://github.com/lxc/incus/files/14312015/incus-launch-debug.txt)

**Comment by stgraber** [comment]
Okay, sounds like we need to set a higher minimum size when creating a config volume on XFS.

**Comment by stgraber** [comment]
So that appears to be a new development in XFS as on my system I can still use a 100MB large volume.

**Comment by dermotbradley** [comment]
> So that appears to be a new development in XFS as on my system I can still use a 100MB large volume.

This appears to have changed in xfsprogs 5.19.0 (August 2022): https://git.kernel.org/pub/scm/fs/xfs/xfsprogs-dev.git/commit/?id=6e0ed3d19c54603f0f7d628ea04b550151d8a262
