### ISSUE TITLE
incus info fails to list snapshots in a YAMLish format

### ISSUE THREAD

**Issue by C0rn3j** [lxc/incus#543]
Using btrfs backed LXD 4.x works correctly with a single line per snapshot, 5.0.3 changes the output to the full tables.

lxc info on LXD 4.0.9
```yaml
Snapshots:
  snap0 (taken at 2024/02/27 09:51 CET) (stateless)
```

lxc info on LXD 5.0.3 and 5.20
```yaml
Snapshots:
+-------+----------------------+------------+----------+
| NAME  |       TAKEN AT       | EXPIRES AT | STATEFUL |
+-------+----------------------+------------+----------+
| snap0 | 2024/02/27 09:56 CET |            | NO       |
+-------+----------------------+------------+----------+
```

incus info on 0.6.0 (please additionally note the whack expire time)
```yaml
Snapshots:
+-------+----------------------+----------------------+----------+
| NAME  |       TAKEN AT       |      EXPIRES AT      | STATEFUL |
+-------+----------------------+----------------------+----------+
| snap0 | 2024/02/27 09:52 CET | 0001/01/01 00:57 LMT | NO       |
+-------+----------------------+----------------------+----------+
```

Was this intended? What used to be one line is now five, and it makes it hell to parse.  
Incus additionally has a non-sensical expire time.

**Comment by stgraber** [comment]
Info commands are meant for human consumption.

What you want in your case is `incus snapshot list` which has options for json, yaml and csv output.

**Comment by C0rn3j** [comment]
Fair enough (though a bit womp-womp on the LXD deploys), but how about the EXPIRES AT timestamp?

That looks like a bug for sure.

**Comment by stgraber** [comment]
@C0rn3j https://github.com/lxc/incus/pull/546
