### ISSUE TITLE
Add a new `incus remote generate-certificate` command

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#551]
In some cases, it makes sense to be able to manually trigger the generation of a client certificate.

Running `incus remote generate-certificate` should generate a `client.crt` and `client.key` if none is already found. If one already exists, it should error out.

**Comment by presztak** [comment]
@stgraber Can I try that one?

**Comment by stgraber** [comment]
@presztak doh, sorry, got that one ready to send as a PR, actually started working on it 5 minutes ago :)
