### ISSUE TITLE
doc: Add page on 3rd party tooling

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#556]
It would be good to have a page on 3rd party integrations/tooling highlighting at least:
 - Ansible
 - Terraform/OpenTofu
 - Packer
 - Garm

**Comment by jarrodu** [comment]
What is Garm? Do you have a link?

**Comment by jarrodu** [comment]
https://github.com/cloudbase/garm
https://github.com/cloudbase/garm-provider-lxd

**Comment by stgraber** [comment]
https://github.com/cloudbase/garm-provider-incus in this case but yeah
