### ISSUE TITLE
Better way to move containers/volumes accross projects

### ISSUE THREAD

**Issue by mkg20001** [lxc/incus#566]
# Required information

 * Distribution: nixos
 * Distribution version: unstable
 * The output of "incus info" or if that fails:

https://termbin.com/bs34

   * Kernel version:
   * LXC version:
   * Incus version:
   * Storage backend in use: zfs

# Issue description

Currently when moving a container/volume accross projects:
- each volume assigned to the container needs to be moved seperatly
- each container and volume is being copied even if the target and source storage is the same

What could be done
- only rename where a simple rename "across projects" would be enough (this is whenever the project is different but the storage stays the same)
- add a better way to move container's devices along with container. I'm not sure what the best approach is here, since the volumes being transferred might also need extra options (like the abbility to choose target storage per volume)

# Steps to reproduce

1. incus init images:ubuntu/22.04 test-cont
2. incus storage volume create default test-vol
3. incus project create test-proj 
4. incus storage volume move default/test-vol default/test-vol --target-project test-proj
5. incus move test-cont --target-project test-proj

Also just doing `incus move test-cont --target-project test-proj` without moving the volume first results in `Error: Migration operation failure: Failed creating instance record: Failed initialising instance: Failed add validation for device "storage": Failed loading custom volume: Storage volume not found` but moving the volume first works.

Also I'm not sure if after the volume is moved the container would even start since it's no longer in the same project (which doesn't have shared volumes only shared storages)

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`incus info NAME --show-log`)
 - [ ] Container configuration (`incus config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/incus/incusd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the issue)

**Comment by stgraber** [comment]
Having a server-side way to move across project would make sense and I believe we do already have that to some extent, it may be a case of the client using the less optimized path for some reason.

For the dependency on a volume or network, the error should certainly be clearer, but I don't think that there is a good way to handle it automatically. Not only because the exact environment on the target server or project may be quite different but also because a volume can be shared amongst multiple instances.

**Comment by sona78** [comment]
Would I be able to help optimize this process of moving volumes across containers, or is the existing feature robust enough?

**Comment by stgraber** [comment]
I expect this one will get fixed (along with a couple of other issues) through a big rework I'm doing in the instance migration logic.

**Comment by stgraber** [comment]
Confirmed that #727 now lets you move across project completely on the server side.
A bunch of those operations aren't full rename but still copy+delete, the exact behavior is up to individual storage drivers though.
