### ISSUE TITLE
`incus launch` fails — bypassing proxy environment variable

### ISSUE THREAD

**Issue by curable-online** [lxc/incus#574]
## Required information

 * Distribution: Arch
 * Distribution version: Current
 * The output of `incus info`: Attached:
[incus-info.txt](https://github.com/lxc/incus/files/14474711/incus-info.txt)

## Issue description

Downloading images fails without any proxy and VPN here. Which is natural due to my own internet limitation. Downloading images using OpenVPN works well, as expected. But when using environment variables, incus simply doesn't root the traffic through the defined proxy addresses.

I wasn't sure. But after a good deal of experimentation, I concluded that `incus` doesn't really consider proxy variables. Both shell variables and systemd variables.

The proxy environment variables which I'm talking about are:
```
https_proxy HTTPS_PROXY http_proxy HTTP_PROXY ftp_proxy all_proxy FTP_PROXY ALL_PROXY no_proxy NO_PROXY
```
I set all of them to be sure.

## Steps to reproduce

 1. Run `incus launch images:alpine/3.19 first`.  
Fails with the following error:
```
Error: Failed instance creation: Get "https://sgp1lxdmirror01.do.letsbuildthe.cloud/images/alpine/edge/amd64/default/20240303_13:00/incus.tar.xz": Unable to connect to: sgp1lxdmirror01.do.letsbuildthe.cloud:443 ([dial tcp 167.71.218.48:443: i/o timeout dial tcp [2400:6180:0:d0::10f8:6001]:443: connect: network is unreachable])
```

 2. Set your shell's `*_proxy` and `*_PROXY` variables.
 3. Import them to systemd environment with `sudo systemctl import-environment` and `systemctl --user import-environment`  
Fails with the same error:
```
Error: Failed instance creation: Get "https://sgp1lxdmirror01.do.letsbuildthe.cloud/images/alpine/edge/amd64/default/20240303_13:00/incus.tar.xz": Unable to connect to: sgp1lxdmirror01.do.letsbuildthe.cloud:443 ([dial tcp 167.71.218.48:443: i/o timeout dial tcp [2400:6180:0:d0::10f8:6001]:443: connect: network is unreachable])
```

 4. Use a VPN that uses TUN instead of proxy to tunnel your traffic to the server. (OpenVPN, for example)  
Downloads and creates the container successfully.

## Information to attach

 - [X] Output of `systemctl show-environment | grep -i proxy`
[systemd-env.txt](https://github.com/lxc/incus/files/14474668/systemd-env.txt)
 - [X] Output of `systemctl --user show-environment | grep -i proxy`
[systemd-user-env.txt](https://github.com/lxc/incus/files/14474667/systemd-user-env.txt)
 - [X] Output of `printenv | rg -i proxy`
[shell-env.txt](https://github.com/lxc/incus/files/14474669/shell-env.txt)
 - [X] Output of `incus launch images:alpine/edge test` with --debug
[test.txt](https://github.com/lxc/incus/files/14474709/test.txt)

**Comment by stgraber** [comment]
The incus daemon does respect the standard proxy variables but you need to keep in mind that the daemon is what does the downloading, not the client.

So you need to make sure that your init system properly passes those environment variables to the incusd process.

An alternative is to see core.proxy_http and core.proxy_https as a server config key.

**Comment by stgraber** [comment]
The documentation is correct.

The client also uses the env variables when accessing an image server directly through it as happens with `incus image export images:alpine/edge` for example.

**Comment by Alwaysin** [comment]
> 1. Set shell's *_proxy and *_PROXY variables, and import them with the service manager -- for example, with `systemctl import-environment` command on a systemd system.
>    OR
>    set them directly for your service manager -- for example, with `systemctl set-environment` command on a systemd system.
> 2. Restart `incusd` if it's running. On a systemd system with `systemctl restart incus.service incus.socket`.
> 

Thank you sir, it helped me getting rid of this issue!

**Comment by GuanglinDu** [comment]
Based on my previous experience with LXD/LXC cloud, I used the following config commands to set the proxy for Incus successfully:
```
incus config set core.proxy_http http://your_proxy_server_ip_address:port
incus config set core.proxy_https http://your_proxy_server_ip_address:port
incus config set core.proxy_ignore_hosts "localhost, 127.0.0.1"
incus info 
```
The last command is to check my config info.
