### ISSUE TITLE
Cluster API support

### ISSUE THREAD

**Issue by cfredericksen** [lxc/incus#576]
https://github.com/kubernetes-sigs/cluster-api

Adding support would put Incus in a good position with other VM/Container management tools like Proxmox, Cloudstack, VMware that all currently support Cluster API for Kubernetes cluster management.

**Comment by stgraber** [comment]
Closing as not something that would cause any addition to this repository.

A Kubernetes cluster API plugin for Incus would live in its own repository and just be another API client as far as Incus is concerned.

I think it'd be a good thing to have and we'd be happy to help out anyone working on it just as we are the other 3rd party Integrations like Ansible, Terraform, Packer and more.

**Comment by stgraber** [comment]
Maybe worth raising on the community forum to see if anyone is interested in creating such a project?
