### ISSUE TITLE
Not possible to move instance between projects while also defining a target cluster member

### ISSUE THREAD

**Issue by victoitor** [lxc/incus#590]
# Issue description

When running `incus move`, it is not allowed to use both `--target-project` together with `--target`.

# Steps to reproduce

```
victoitor@bastion:~$ incus move test --target-project aux --target @compartilhado
Error: The --target-project flag can't be used with --target
```

This was initially discussed in [this forum post](https://discuss.linuxcontainers.org/t/moving-instances-between-projects-with-cluster-groups/).

**Comment by stgraber** [comment]
The easy label here is based on the assumption that this is just a CLI or basic API issue.
This may be hiding more complex server-side issues with cross-project copies/moves.

**Comment by presztak** [comment]
@stgraber as we've discussed I can grab this as next one if you don't mind.

**Comment by stgraber** [comment]
Sure!

**Comment by presztak** [comment]
Hey @stgraber , quick update from my side. it seems that removal of https://github.com/lxc/incus/blob/ce15a0a8c41d96466ff6222f8c2d52051fcfba85/cmd/incus/move.go#L165-L167 is not enough to solve this :) 
For moving instances between cluster members we are using https://github.com/lxc/incus/blob/ce15a0a8c41d96466ff6222f8c2d52051fcfba85/cmd/incusd/instance_post.go#L365 and `migrateInstance` doesn't support moving instance across projects but I already have some changes which seems to work. I'll open tomorrow draft PR because still I've some doubts.

**Comment by stgraber** [comment]
Sounds great, thanks for the update!

**Comment by stgraber** [comment]
Confirmed that #727 fixes this one.
```
root@server01:~# incus list
+------+---------+------+------+-----------+-----------+----------+
| NAME |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS | LOCATION |
+------+---------+------+------+-----------+-----------+----------+
| d4   | STOPPED |      |      | CONTAINER | 0         | server01 |
+------+---------+------+------+-----------+-----------+----------+
| d5   | STOPPED |      |      | CONTAINER | 0         | server03 |
+------+---------+------+------+-----------+-----------+----------+
| d6   | STOPPED |      |      | CONTAINER | 0         | server03 |
+------+---------+------+------+-----------+-----------+----------+
root@server01:~# ./incus move d4 --target-project default --target server02
root@server01:~# incus list --all-projects name=d4
+---------+------+---------+------+------+-----------+-----------+----------+
| PROJECT | NAME |  STATE  | IPV4 | IPV6 |   TYPE    | SNAPSHOTS | LOCATION |
+---------+------+---------+------+------+-----------+-----------+----------+
| default | d4   | STOPPED |      |      | CONTAINER | 0         | server02 |
+---------+------+---------+------+------+-----------+-----------+----------+
root@server01:~# 
```
