### ISSUE TITLE
Pragmatic Manpages

### ISSUE THREAD

**Issue by curable-online** [lxc/incus#596]
## Required information

 * Distribution: Arch Linux
 * Distribution version: Current
 * Incus version: `0.6`

## Issue description

Invoking `incus manpage ./manpages` produces about __323__ manual pages. Each with less than __30__ lines of text. And still not covering most information provided by the online documentation.  
They are basically a conversion of `--help` descriptions to troff/groff format.  

This is as impractical as they are not produced by default in Arch Linux[[1]], explicitly wording it as worthless.

Manpages are a universally known way of documentation.

1. They are offline.  
You have local offline access to them all the time on the same system that you are running Incus server or client.
2. Manpage viewers are ubiquitous.  
They are installed on all *nix like systems by default, even Macs. You do not need to install anything new on your system to be able reading the documentation.  
3. Manpages are lightweight.  
I.e. Manpage files, besides being lightweight by themselves, do not need any kind of heavy client to render them. But for accessing online documentation, you have to open a comparably heavy client first, called Web Browser.  
4. They are usually written in uniform and unified.  
The current state of Incus documentation is really scattered between many pages linked to each other, forcing a reader to constantly go back and forth between them. 

## Suggestions

* Better documentation to be more unified, or at least more unified for manpages. 
* Manpage has to cover the required information for doing a task with a command. Currently, a reader is forced to look at online documentation for knowing the required/possible arguments of each flag/sub-command anyway. Making manpages totally pointless.

[1]:https://gitlab.archlinux.org/archlinux/packaging/packages/incus/-/blob/main/PKGBUILD?ref_type=heads#L70

## Steps to reproduce

Nothing.

## Information to attach

Nothing related.

**Comment by stgraber** [comment]
Hey there,

We're not interested in writing manpages, writing separate manpages is extremely resource intensive for something that only works on Linux when the current help can be mostly automatically generated and is available across Windows, Linux and MacOS.

The generated manpages are primarily used by the documentation itself which can then reference specific commands and sub-commands.

Distributions are then free to decide if they want to ship the generated manpages or just let the user use --help and the documentation.

Speaking of the documentation, it's part of our release tarballs as rendered html files and can be served by Incus itself if the packager includes the files in the package and sets their location through an incusd env variable.

**Comment by adamcstephens** [comment]
@stgraber would it make sense to add the relevant env variable and note to https://github.com/lxc/incus/blob/main/doc/packaging.md ?

**Comment by stgraber** [comment]
Yeah, that'd make sense to highlight.
