### ISSUE TITLE
Define proper API and Go client function to access API configuration metadata

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#600]
We've had the `/1.0/metadata/configuration` endpoint for a little while now but there's no matching structs for it in `shared/api` nor is there a Go API client function to access it.

We should:
 - Add a new `MetadataConfiguration` struct in `shared/api` matching the current JSON data
 - Add a new `GetMetadataConfiguration` function in `client` to access the endpoint and return the `api.MetadataConfiguration`

**Comment by presztak** [comment]
@stgraber can I take that one?

**Comment by stgraber** [comment]
For sure!

Can you also rename `documentation.go` to `metadata.go` while you're working on this one?
The file name doesn't make much sense right now.
