### ISSUE TITLE
Cannot delete copied instance (ceph storage)

### ISSUE THREAD

**Issue by compewter** [lxc/incus#601]
# Required information
 * Distribution: Arch Linux
 * Distribution version: 6.7.8-arch1-1
 * The output of "incus info" or if that fails:
   * Kernel version: 6.7.8-arch1-1
   * LXC version: 5.20
   * Incus version: 0.6
   * Storage backend in use: ceph rbd

# Issue description

I have a new incus cluster, using a ceph cluster as its storage. If I launch a container from images and copy it to a new container the command `incus delete new-container` hangs.

New containers delete just fine:
 1. `incus launch images:archlinux test`
 2. `incus delete test --force` 

# Steps to reproduce
1. `incus launch images:archlinux test`
2. `incus copy test test-copied`
4. `incus delete test-copied`
... hangs ...

# Information to attach
I found this relevant error in the incusd logs
`level=error msg="Error getting disk usage" err="Failed to run: rbd du --format json --id admin --cluster ceph --pool incus container_test-copied: exit status 2 (specified image container_test-copied is not found.\nrbd: du failed: (2) No such file or directory)" instance=test-copied instanceType=container project=default`

If i run `rbd ls --pool incus` before running `incus delete` I see container_test-copied listed, and after running `incus delete` it is removed. It seems like it may be removed prematurely?

In addition to the command hanging, the container is still listed in `incus ls`. and the only way I've found to actually remove it is using `incus admin sql` commands to remove the containers from the `storage_volumes` and `instances` tables:
`incus admin sql global "delete from instances WHERE name='test-copied'"`
`incus admin sql global "delete from storage_volumes WHERE name='test-copied'"`

I found [this](https://github.com/lxc/incus/blob/0d5f33f13875c6611826ff498c9be2545f991027/doc/api-extensions.md#ceph_rbd_du) storage option and set it to false to see if we can avoid the rbd du command altogether but it still hangs on the delete command and produces a different error logged by incusd:
`level=error msg="Error getting disk usage" err="Cannot get disk usage of unmounted volume when ceph.rbd.du is false" instance=test-copied instanceType=container project=default`

**Comment by stgraber** [comment]
Not having any luck reproducing this here:
```
root@chulak:~# incus launch images:archlinux test
Launching test
root@chulak:~# incus copy test test-copied
root@chulak:~# rbd ls ssd | grep test
container_demo_test
container_demo_test-copied
root@chulak:~# incus delete test-copied
root@chulak:~# incus delete -f test
root@chulak:~# rbd ls ssd | grep test
root@chulak:~# 
```

**Comment by stgraber** [comment]
Can you show `ceph versions`?
Though I'm not sure why the Ceph version would matter.

**Comment by compewter** [comment]
hm..  could it be my ceph pool?

I'm running ceph version 18.2.1 on all 3 hosts


I'll dig into my ceph pool further to see if thats where the delete command is hanging.

Is there somewhere in the incus code you could point me to see what steps the command is taking with respect to these rbd commands?

Thanks for your time

**Comment by compewter** [comment]
I ended up reinstalling ceph and everythings working fine now. thanks!
