### ISSUE TITLE
Allow VM live migration when attached disks are all on remote storage pools

### ISSUE THREAD

**Issue by dzn674206444** [lxc/incus#642]
# Required information

 * Distribution: Arch Linux
 * Distribution version: 6.7.8-arch1-1
 * The output of "incus info" or if that fails:
   * Kernel version:  6.7.8-arch1-1
   * LXC version: 5.20
   * Incus version: 0.6
   * Storage backend in use: ceph rbd

# Issue description

When a virtual machine has disks mounted other than the root hard drive, hot migration cannot be performed.
The error log is:
`Error: Instance move to destination failed: Error transferring instance data: Failed migration on target: Failed start validation for device "disk-wbT0xjUaD5": Custom volume is already attached to an instance on a different node
`

# Steps to reproduce

 1. incus init ubuntu:20.04 test --vm
 2. incus config device add test --vm disk-test disk source=default/disk-wbT0xjUaD5 path=/etc
 3. incus config set test migration.stateful true
 4. incus start test
 5. incus move test --target=other-host
# Information to attach
I found this fun in incus code
`
func VolumeUsedByExclusiveRemoteInstancesWithProfiles(s *state.State, poolName string, projectName string, vol *api.StorageVolume) (*db.InstanceArgs, error) {
	pool, err := LoadByName(s, poolName)
	if err != nil {
		return nil, fmt.Errorf("Failed loading storage pool %q: %w", poolName, err)
	}

	info := pool.Driver().Info()

	// Always return nil if the storage driver supports mounting volumes on multiple nodes at once.
	if info.VolumeMultiNode {
		return nil, nil
	}

	// Find if volume is attached to a remote instance.
	var remoteInstance *db.InstanceArgs
	err = VolumeUsedByInstanceDevices(s, poolName, projectName, vol, true, func(dbInst db.InstanceArgs, project api.Project, usedByDevices []string) error {
		if dbInst.Node != s.ServerName {
			remoteInstance = &dbInst
			return db.ErrInstanceListStop // Stop the search, this volume is attached to a remote instance.
		}

		return nil
	})
	if err != nil && err != db.ErrInstanceListStop {
		return nil, err
	}

	return remoteInstance, nil
}

`
but cephRbd does not have the volumeMultiNode attribute

**Comment by stgraber** [comment]
Got a good test environment for this one now though I've also noticed that we're hitting the issue within QEMU code, so it's going to be interesting to see how much can be done to sort it out from Incus.

**Comment by stgraber** [comment]
Got it working with an LVM cluster backend here, though there's a lot of hardcoded stuff I need to cleanup still, and then validate that it works on top of a ceph pool too.
