### ISSUE TITLE
Add support for stateless rules in network ACLs

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#651]
Currently all ACL rules are assumed to be stateful.

That's certainly fine as a default as stateless firewalling can be a bit tricky to get right, but for very high throughput/pps applications, it's a very useful tool and so should be supported.

**Comment by stgraber** [comment]
We can do this by adding a new `allow-stateless` action which in the OVN case makes us use `allow-stateless` rather than the current `allow-related`.

**Comment by christina-zh** [comment]
Im interested in working on this issue, can I be assigned to it please?

**Comment by stgraber** [comment]
For this one, you're going to want to:
 - Add an API extension string for the change (say `network_acl_stateless`)
 - Add the new value to the list in `doc/howto/network_acls.md`
 - Add it to `ValidActions` in `internal/server/network/acl/driver_common.go`
 - Add it to `ovnRuleCriteriaToOVNACLRule` in `internal/server/network/acl/acl_ovn.go` (and remove the TODO). The priority remains PortGroupAllow, it's just the action that will differ
 - Add logic to `internal/server/network/acl/acl_firewall.go` to map a stateless ACL to a normal allowRule (with a TODO comment to add NOTRACK support later)

And I think that should be it to get this working.

Expected commit list based on the above should be:
 - api: Add network_acl_stateless
 - doc/network_acl: Add allow-stateless action
 - incusd/network/acl: Add allow-stateless action

**Comment by atomus1990** [comment]
Stateless is supported for strictly for OVN networks? Or is supported for Bridge networks also?

**Comment by stgraber** [comment]
Only OVN at this time
