### ISSUE TITLE
Cannot move custom storage volumes to another host

### ISSUE THREAD

**Issue by markrattray** [lxc/incus#656]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04.4
 * The output of "incus info":
   * source host: host-p101  [storage-move_custom-volume-block_host-p101_info.txt](https://github.com/lxc/incus/files/14739758/storage-move_custom-volume-block_host-p101_info.txt)
   * destination host: host-p103  [storage-move_custom-volume-block_host-p103_info.txt](https://github.com/lxc/incus/files/14739761/storage-move_custom-volume-block_host-p103_info.txt)
   * Storage backend in use: ZFS on host local physical SAS RAID10 / SSD RAID10 / NVMe

# Issue description

Trying to rebuild Incus hosts in a production cluster due to a naming convention update, so moving instances off hosts onto others temporarily. Moving the VM instance and its root block volume through `incus move` is fine but any custom block volumes fail to start moving or even copying with the error:
```
Error: Error transferring storage volume: websocket: close 1000 (normal)
```

These servers were VMware ESXi and were rebuilt in December 2023 with Ubuntu 22.04 and LXD latest/stable, then migrated to Incus a couple of months ago, so the ZFS storage pools were created under the recent version of LXD. On the host-p103 in the attached files, I did:
 - move instances off the host but there were very few and no custom storage volumes
 - `incus cluster remove`
 - `dpkg -P incus incus-client incus-base`,
 - renamed the host (`hostnamectl`) && update hosts && add new DNS A
 - reboot
 - `apt update && apt install incus`
 - rejoin cluster with the new name and FQDN
 - `apt update && apt dist-upgrade` all other hosts in the cluster because Incus the version 0.6x used on the cluster wasn't in the repo

Cluster list implies that all is working fine and as said the VM instance itself moves fine, just not custom block volumes.

The only way I have been able to get the volumes across is to export them on the client on host-p103 then importing. Not too bad for the 20 GiB volumes but the 300 GiB volumes take hours.

# Steps to reproduce
Even if I:

- create a new custom block volume
- attach the new custom block volume to the instance
- copy data from the original block volume to the new block volume
- detach the new custom block volume from the instance
- try `incus storage volume move...` or `...copy...` the new block volume using same pool & project on other host or additionally change volume name
- try the same in the client on the destination host

the same error just keeps coming up.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`incus info NAME --show-log`)
 - [ ] Container configuration (`incus config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/incus/incusd.log)
 - [x] Output of the client with --debug  [storage-move_custom-volume-block.txt](https://github.com/lxc/incus/files/14739568/storage-move_custom-volume-block.txt)
 - [ ] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the issue)

**Comment by stgraber** [comment]
Can you try passing `--mode=relay` as that sometimes lead to more useful errors.

**Comment by markrattray** [comment]
Hi, thanks. Here is the result:
[storage-move_custom-volume-block_mode-relay.txt](https://github.com/lxc/incus/files/14762584/storage-move_custom-volume-block_mode-relay.txt)

I've even tried a copy operation and to another cluster member that hasn't been rebuilt but the same result.

I give the source host a reboot tomorrow morning. 

Have a good evening.

**Comment by markrattray** [comment]
A reboot of the source host didn't help. 

There are other cluster members that might need rebooting too in case it's caused by a cluster wide state scenario, like an apt update but no restart. I could do them early tomorrow morning, but doesn't seem right since instances and their root volumes can be moved fine.

**Comment by stgraber** [comment]
The main issue here "websocket: close" was because of a failure to correctly forward errors between the two servers. This was fixed a few releases ago, so upgrading should at least get a clearer error, indicating whether it's expected (some configuration preventing the operation) or a bug we need to track down.
