### ISSUE TITLE
Naming of qcow2 file from "incus image export"

### ISSUE THREAD

**Issue by candlerb** [lxc/incus#668]
# Required information

Incus 0.6-202403181629-ubuntu22.04, Ubuntu 22.04

# Issue description

This is mainly a cosmetic issue, but I found it rather confusing, and it doesn't seem to be well documented.

As far as I can see, "incus image export" only allows you to supply a single name. This is the name of the .tar.gz file which contains the metadata.

However it writes two files, adding `.root` to this name to make the qcow2 image file name. You end up with `foo.tar.gz.root`, which I didn't expect to get, and the name is confusing as it's not a tar.gz file at all.

Having a separate qcow2 file like this (so I don't have to pull it out of a tarball) is really very convenient and I'd like to keep it that way - it's just the naming of the file that's odd.  Maybe export could allow an option to provide a second filename?  But now I know how it works I can always rename it, so it's not a big deal.

There's a related point, which is to do with the documentation of the [split tarball format](https://linuxcontainers.org/incus/docs/main/reference/image_format/#split-tarballs) for "incus image import". This clearly says that there are "two separate tarballs", one containing metadata and one containing the image file. However, the reality seems to be one tarball containing metadata, plus an image file *not* inside any tarball.  Testing shows that export doesn't wrap the image in a tarball, and import is happy to consume this unwrapped image.

The way that the fingerprint is calculated is also unclear. It says:

> The image identifier for such images is the SHA-256 of the concatenation of the metadata and root file system tarball (in that order).

Through experimentation, it seems to be the SHA-256 of the concatenation of the metadata tarball and the root file system image (in that order).

# Steps to reproduce

```
$ incus image list testzfs
+---------+--------------+--------+----------------------+--------------+-----------------+------------+----------------------+
|  ALIAS  | FINGERPRINT  | PUBLIC |     DESCRIPTION      | ARCHITECTURE |      TYPE       |    SIZE    |     UPLOAD DATE      |
+---------+--------------+--------+----------------------+--------------+-----------------+------------+----------------------+
| testzfs | c35820662b54 | no     | NSRC virtual machine | x86_64       | VIRTUAL-MACHINE | 1708.13MiB | 2024/03/25 16:11 UTC |
+---------+--------------+--------+----------------------+--------------+-----------------+------------+----------------------+

$ incus image export testzfs --vm /var/tmp/export.tgz /var/tmp/export.qcow2
...
Error: Invalid number of arguments

$ incus image export testzfs --vm /var/tmp/export.tgz
Exporting the image: ...
Image exported successfully!

$ ls -l /var/tmp/export.tgz*
-rw-rw-r-- 1 nsrc nsrc        224 Mar 26 18:05 /var/tmp/export.tgz
-rw-rw-r-- 1 nsrc nsrc 1791098880 Mar 26 18:05 /var/tmp/export.tgz.root

$ tar -tvzf /var/tmp/export.tgz
-rw-rw-r-- nsrc/nsrc       126 2024-03-25 16:10 metadata.yaml

$ file /var/tmp/export.tgz.root
/var/tmp/export.tgz.root: QEMU QCOW2 Image (v3), 21474836480 bytes

$ incus image delete c35820662b54
$ incus image import /var/tmp/export.tgz /var/tmp/export.tgz.root --alias testzfs
Image imported with fingerprint: c35820662b54da226c139aaed70b6be1619d1074cb8148af044ecdb0d02cc8b5

$ cat export.tgz export.tgz.root | sha256sum
c35820662b54da226c139aaed70b6be1619d1074cb8148af044ecdb0d02cc8b5  -
```

**Comment by stgraber** [comment]
I'll use this issue to update the docs to be less specific to the old image implementation (pre-squashfs and pre-vm).

For export, the problem is that we don't really know how many files we'll be given. Instead we just get a multi-part stream from the server and have to figure things out as they come in.
This is currently done by using `<filename>` for the first file and then `<filename>.<multipart section>` for any file after that.

So you can do `incus image export fingerprint foo` and usually will get both `foo` and `foo.root`.

Worth noting that when not specifying a filename, then the server provides a more useful set of filenames, for example:
```
stgraber@dakara:~/test$ incus image export rhel9
Image exported successfully!               
stgraber@dakara:~/test$ ls -lh
total 806M
-rw-r--r-- 1 stgraber domain admins 831M Mar 26 17:39 d7ee829d325fc21959f61fced13684c994c571002d7dea2bd85e9e34d0072916.qcow2
-rw-r--r-- 1 stgraber domain admins  288 Mar 26 17:39 meta-d7ee829d325fc21959f61fced13684c994c571002d7dea2bd85e9e34d0072916.tar.xz
stgraber@dakara:~/test$ 
```

When I first saw this issue, I thought you were reporting an issue with the way the server sets those filenames in the case where you're not providing a filename yourself, but when reading more closely, that's not the case and testing shows the logic working as intended.

(Also note that with our plans to add OCI image support, we'll soon find ourselves with images that may be comprised of a LOT of files)

**Comment by candlerb** [comment]
Also I was a bit surprised that `incus image export ...` without the `--vm` flag works even for a VM image; but you get a unified tarball rather than split files.

The help message says:

```
$ incus image export --help
Description:
  Export and download images
...
Flags:
      --vm   Query virtual machine images
```

I think this flag is used to switch between unified and split exports.

**Comment by candlerb** [comment]
Now I'm more confused. With or without the `--vm` flag, I'm getting VM image exports which are a single tarball, *and* with a forced additional filename extension:

```
$ incus image export nsrc-nmm --vm /home/nsrc/nsrc-vm/output/nsrc-nmm.tar.gz
Image exported successfully!
$ ls -l /home/nsrc/nsrc-vm/output/nsrc-nmm.tar.gz*
-rw-rw-r-- 1 nsrc nsrc 2218975680 Mar 29 09:00 /home/nsrc/nsrc-vm/output/nsrc-nmm.tar.gz.tar.gz
$ tar -tvzf /home/nsrc/nsrc-vm/output/nsrc-nmm.tar.gz.tar.gz
-rw-r--r-- root/root        91 2024-03-29 08:42 metadata.yaml
---------- root/root 2240610304 2024-03-29 08:46 rootfs.img
```

This is an image that I published myself, using `incus publish`. The fingerprint is `422316d6742e`. Under `/var/lib/incus/images` there is only a single file:

```
-rw------- 1 root root 2218975680 Mar 29 08:47 422316d6742e2d8a66519b18bb1d0a33e891e0062c88f6cf0090018eaa9e9056
```

whereas for most other images there are `<fp>` and `<fp>.rootfs`

I guess this means that whether an image is unified or split is an attribute of the image itself at the time it was published (and it will always be exported in the same way). However, there doesn't seem to be a flag to `incus publish` that controls this behaviour.

Does this mean that `incus publish` always creates unified images? If so, that may be worth a mention [here](https://linuxcontainers.org/incus/docs/main/reference/image_format/#image-tarballs).

**Comment by stgraber** [comment]
It is mentioned in the documentation:
```
This is the format that Incus itself uses internally when publishing images. It is usually easier to work with; therefore, you should use the unified format when creating Incus-specific images.
```

**Comment by stgraber** [comment]
The --vm flag is only relevant of you have the same image identifier (alias) pointing to two different images, one for containers and one for VMs.

That's possible on simplestreams image servers, for example images:ubuntu/22.04.
In that case, a normal export will get you the container image whereas --vm will grab the VM image. With that image server, both images will be in the split format.

**Comment by stgraber** [comment]
> Aside: mode 000 for rootfs.img within the tarball is a bit weird.

I'll send a fix for that one, though it's very much cosmetic as the tarball is never actually unpacked to disk and just read from directly.

**Comment by candlerb** [comment]
There is a related bit of surprising behaviour which just caught me out. If I do

```
incus image export someimage cndo
```

(where "someimage" is a unified container image) then I expect it to create `cndo.tar.gz` in the current directory, because this is what it normally does.  However, if there happens to be a subdirectory called `cndo` in the current directory, then instead it will create `cndo/<fingerprint>.tar.gz`

This caught me out because the application is called "cndo", and the scripts to build it are in directory called "cndo". Therefore, if I happen to be one level higher up in the directory tree when I do the export, then I get a fingerprint-based name in that subdirectory, instead of the fixed name prefix I thought I asked for in.

To make the filename deterministic, I now have a workaround in my scripts:

```
incus image export someimage export-cndo
mv export-cndo.tar.gz cndo.tar.gz
```

I think I know where this comes from. There could be more than one piece from the export, and I could be specifying either a filename stem or a subdirectory to put the pieces in. Incus decides which is intended based on the presence of a matching subdirectory. But that's magic and AFAICS [undocumented](https://linuxcontainers.org/incus/docs/main/reference/manpages/incus/image/export/) - the parameter is described as `<target file>` and that's all.

I think it would be better for this to be an explicit choice by the user. For example, if the `<target file>` ends with a slash then it's treated as a subdirectory prefix, and anything else is treated as a filename stem. That would be a non-backwards-compatible change though.

**Comment by bensmrs** [comment]
Eh, I can’t say `incus image` commands have received much love these last years. That’s definitely something I want to see revamped, like the other `export` commands, but almost every time I got back to `image` commands, I lost a few hair…

I’ll definitely get bored into doing it someday :)
