### ISSUE TITLE
oidc/fga; a user in the server admin role cannot create a named instance

### ISSUE THREAD

**Issue by rgl** [lxc/incus#679]
# Required information

 * Distribution: Debian
 * Distribution version: 12
 * The output of "incus info" or if that fails:
   * Kernel version: 6.1.0-18-amd64
   * LXC version: not sure where to get this from.
   * Incus version: 0.7
   * Storage backend in use: btrfs

# Issue description

The `alice` user is created as a server `admin` with:

```bash
fga tuple write \
  "user:alice@$openfga_domain" \
  admin \
  server:incus
```

At the Incus-UI, I cannot create an Instance when the name is set. the UI errors out with:

![image](https://github.com/lxc/incus/assets/43356/6ded2f7e-36a4-45ff-ab17-39bd2b634917)

Please note that leaving the name field empty, I can successfully create the instance. It only errors out with a 403 response status code when I set the name.

# Steps to reproduce

 1. Use OIDC to login at the Incus UI.
 2. Go to the "Create an instance" page, e.g., https://incus.test:8443/ui/project/default/instances/create
 3. Set the "Instance name" field.
 4. Observe it showing the error like the screenshot from above.

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`incus info NAME --show-log`)
 - [ ] Container configuration (`incus config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/incus/incusd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the issue)

**Comment by stgraber** [comment]
Do you have the same issue with the CLI?

**Comment by rgl** [comment]
using the cli works fine. here's the transcript:

```console
$ incus remote add incus.test --auth-type oidc
URL: https://pandora.incus.test:8443/realms/pandora/device?user_code=XJKD-DKNE
Code: XJKD-DKNE

$ incus launch images:debian/12 incus.test:debian-ct
Launching debian-ct

$ incus list incus.test:
+-----------+---------+-------------------+------+-----------+-----------+
|   NAME    |  STATE  |       IPV4        | IPV6 |   TYPE    | SNAPSHOTS |
+-----------+---------+-------------------+------+-----------+-----------+
| debian-ct | RUNNING | 10.2.0.233 (eth0) |      | CONTAINER | 0         |
+-----------+---------+-------------------+------+-----------+-----------+
```

**Comment by stgraber** [comment]
Okay, interesting. Both hit the same REST API so it's weird that the UI fails when the CLI succeeds.

Maybe check both `--debug` on the CLI and the developer tools network requests in the UI to see if there's anything obviously different between the two?

**Comment by rgl** [comment]
there's a major difference. the web ui first verifies (and stops there) whether the image already exists:

![image](https://github.com/lxc/incus/assets/43356/0c967e83-11bb-47e9-a4ea-7dcf80b7850d)

the cli immediately does a POST with the instance details:

```
DEBUG  [2024-03-27T18:37:43Z] Sending request to Incus                      etag= method=POST url="https://incus.test:8443/1.0/instances"
```

**Comment by stgraber** [comment]
Ah yeah, that'd be the issue then...

OpenFGA can have per-instance permissions, as a result, we don't return a 404 when using it but instead return 403 to avoid leaking information about what may or may not exist.

**Comment by rgl** [comment]
should a bug be filled in the web ui repo? i.e. to make it error out only when a 404 is returned?

**Comment by stgraber** [comment]
They've now got a built-in OpenFGA server in 5.21 so I don't know if they're affected by this too. Also worth noting that they're now on UI 0.7 while we ship 0.6, so it's not completely impossible that the issue may have been fixed already.

@edlerd would know :)

**Comment by stgraber** [comment]
I've got a couple of items related to this on my short-term TODO:
 - Update the Zabbly packages to use version 0.7 of the UI
 - Sort out: #292

**Comment by stgraber** [comment]
Ah, interesting decision, okay, we'll just patch around this then :)

**Comment by stgraber** [comment]
https://github.com/zabbly/incus/commit/c83023587eb0e3b01c99ba26e63f757ac15c6f9c
