### ISSUE TITLE
"incus storage info" doesn't show storage source

### ISSUE THREAD

**Issue by candlerb** [lxc/incus#690]
# Required information

Ubuntu 22.04, 0.7-202403271502-ubuntu22.04

# Issue description

`incus storage info` doesn't give all of the information about a storage pool, in particular it's missing the "source", even though `incus storage list` does show it.

# Steps to reproduce

```
$ incus storage list
+---------+--------+--------------------------------------+-------------+---------+---------+
|  NAME   | DRIVER |                SOURCE                | DESCRIPTION | USED BY |  STATE  |
+---------+--------+--------------------------------------+-------------+---------+---------+
| default | dir    | /var/lib/incus/storage-pools/default |             | 15      | CREATED |
+---------+--------+--------------------------------------+-------------+---------+---------+
| vg0     | lvm    | vg0                                  |             | 17      | CREATED |
+---------+--------+--------------------------------------+-------------+---------+---------+
| zfs     | zfs    | zfs0/lxd                             |             | 24      | CREATED |
+---------+--------+--------------------------------------+-------------+---------+---------+

$ incus storage info default
info:
  description: ""
  driver: dir
  name: default
  space used: 211.22GiB
  total space: 589.51GiB
used by:
  instances:
  ...
  profiles:
  ...
  volumes:
  ...
```

Missing from this info is the "source" which you get in "incus storage list".  (Also the "STATE", although I have never seen anything other than "CREATED" here)

**Comment by stgraber** [comment]
That's intentional, `incus storage info` is used to show storage state information like usage and the like, not be a duplicate of `incus storage show`.

**Comment by candlerb** [comment]
Ah right, I was confused about info and show being different things. Sorry for the noise.

(There does seem to be considerable overlap though; for example "used by" or "used_by" occurs in both)
