### ISSUE TITLE
Remove Ubuntu Fan support

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#7]
The Ubuntu Fan bridge which is primarily used in the clustering case is a very convenient feature, but it's one that Canonical never tried to upstream and therefore requires custom patches to both the Linux kernel and iproute2 to function.

As Incus has proper overlay networking support through standard OVS/OVN, that should be the focus and the Ubuntu Fan can go away.

**Comment by xnox** [comment]
> never tried to upstream

ubuntu fan violates RFC specifications of using reserved IP ranges thus is not acceptable upstream - or in general should not be operated on public internet.

Some canonical products still use ubuntu fan on GCE cloud and AWS cloud.

However, a more native approach would be better, standards compliant and even potentially more performant. For example on AWS cloud k8s typically uses Amazon VPC CNI plugin for Kubernetes https://github.com/aws/amazon-vpc-cni-k8s Which as far as I can understand can achieve the desired effect (automatically allocate interfaces for a container, and for the host, as of when needed). See design details on https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/cni-proposal.md

Potentially when deploying non-k8s container solutions, using amazon-vpc-ci-k8s may still make sense to achieve coherent networking strategy.

**Comment by dontlaugh** [comment]
While CNI could be adopted in principle, and it's really interesting to imagine re-using all that code in the Incus runtime, it's kind of a big spec (as you are probably aware).

[The CNI spec summary states](https://www.cni.dev/docs/spec/#summary)

> The CNI specification defines:
> 1. A format for administrators to define network configuration.
> 2. A protocol for container runtimes to make requests to network plugins.
> 3. A procedure for executing plugins based on a supplied configuration.
> 4. A procedure for plugins to delegate functionality to other plugins.
> 5. Data types for plugins to return their results to the runtime.

At a high level, the networking "objects" defined in the CNI spec map reasonably well to networks and zones as they have existed in classic LXD, but only at a high level. In practice, I'd wager that very little actually existing CNI code would work without changes.

It all feels very K8s to me. There was a "land rush" of vendors new and old into the space a few years ago, and a very strong pressure to converge on something. And a lot of very smart people did heroic and amazing work, but I don't think that a lot of those configuration interfaces should proliferate. 

As an aside, I am somewhat surprised that Podman is [deprecating CNI](https://github.com/containers/podman/commit/f07aa2addec29558cf89b3efed32094d597f5bc1).

OVN on the other hand, is a more full-featured target for integration that actually _does stuff_. But I wonder if it could be made easier.

**Comment by xnox** [comment]
Sure CNI doesn't look like a good fit. And OVN is much better. But native networking in a given public cloud might be best for small/medium deployments, no? the point of amazon-vpc-cni-k8s is that native amazon cloud networking is used to dynamically create interfaces & ip addresses, attach them to instances and plumb them to the container - which one can also control and firewall using regular amazon tooling & reporting.
