### ISSUE TITLE
Add USB support to `incus info --resources`

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#702]
Currently `incus info --resources` doesn't show USB device at all.

It would be good to add a concise listing of USB devices based on the data already available in the resources API (`/1.0/resources`).

This list should at least include:
 - Device vendor (name and id)
 - Device product (name and id)
 - Bus and device address
 - Serial number (if present)

So looking at something not too dissimilar to the `lsusb` output.

**Comment by RaviTriv** [comment]
Hey, I'm interested in working on this issue. Would be awesome if I could be assigned this. Thank you!

**Comment by stgraber** [comment]
Done!
