### ISSUE TITLE
Add system information to `incus info --resources`

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#705]
It would be useful to add a `System` section to `incus info --resources` showing the most useful fields from the matching section in the resources API.

I suspect we'd want:
 - Vendor
 - Product
 - Serial
 - Type
 - UUID
 - Chassis
   - Vendor
   - Product
   - Serial
 - Motherboard
   - Vendor
   - Product
   - Serial
 - Firmware
   - Vendor
   - Version
   - Date

**Comment by milaiwi** [comment]
Hello! My friends and I are sophomore students at University of Texas at Austin. We just completed a class in Virtualization and would love to contribute to this. Can you provide some more information on how we can begin working on this?

**Comment by stgraber** [comment]
I've assigned it to you now.

You should probably start by getting Incus running on a machine.
Once you do, you'll be able to do `incus info --resources` to look at the current output and `incus query /1.0/resources` to look at all the data available.

You'll then want to modify `cmd/incus/info.go` to add a new section to `incus info --resources` showing that system information.

**Comment by milaiwi** [comment]
Appreciate it! We'll start working on it now!

**Comment by milaiwi** [comment]
We're almost done implementing, but we had a few style questions:

- Should the System section appear at the top of the output of incus info --resources?
- Should we have a block of  print statements within remoteInfo that displays this information (similar to how it is done with Memory) or create a renderSystem function (similar for renderCPUs)? Since there is not a list of Systems, as there is with CPUs and Disks, we're currently just leaving a block of print statements.

Thanks!

**Comment by stgraber** [comment]
Yeah, I think having it show up at the top before the CPU section would make sense and another chunk of printfs is fine too. We can keep the separate functions for when we're rendering multiple entries.

**Comment by milaiwi** [comment]
Hello Stéphane,

I've submitted a pull request to address issue #705, adding system information to incus info --resources as you assigned. Here's the link to the PR: https://github.com/lxc/incus/pull/710. I tried to ensure it aligns with the project's guidelines and the feature request's details. Please review it at your convenience, and let me know if there are any adjustments or additional information needed. I'm eager to make any necessary changes to fit the project's standards. Thank you for the opportunity to contribute!

Best regards,
Mohamed Ilaiwi
