### ISSUE TITLE
Deleting OVN networks fail in a clustered environment

### ISSUE THREAD

**Issue by panfantastic** [lxc/incus#709]
Hi

I'm using 0.7.0 of Incus from the Zabbly apt repo alongside the microovn snap in a 3 node cluster environment.

The issue I'm seeing is that I cannot cleanly delete an OVN network.  The general error message is of the form:

`failed to notify peer 10.20.30.3:8443: Failed deleting OVS chassis "f11" from chassis group "incus-net28": object not found`

The network is no longer listed in the northbound, but the incus database still has a listing for the network and can't be deleted without modifying the db manually.

**Comment by panfantastic** [comment]
In a clean environment trying to create ovn networks and delete them...

```
root@f8:~# incus network create v1 network=uplink --type=ovn
Network v1 created
root@f8:~# microovn.ovn-nbctl show
switch cfe1a098-e60c-4d69-b3a6-e38cdb0dbb1f (incus-net29-ls-ext)
    port incus-net29-ls-ext-lsp-router
        type: router
        router-port: incus-net29-lr-lrp-ext
    port incus-net29-ls-ext-lsp-provider
        type: localnet
        addresses: ["unknown"]
switch 0cfe3bb6-0d0f-43e4-9d14-21c5bb6bd4c9 (incus-net29-ls-int)
    port incus-net29-ls-int-lsp-router
        type: router
        router-port: incus-net29-lr-lrp-int
router d2ccf537-4ff7-46fe-8aa0-54893555929d (incus-net29-lr)
    port incus-net29-lr-lrp-int
        mac: "00:16:3e:51:76:bd"
        networks: ["10.71.59.1/24", "fd42:8a8e:e5f:b546::1/64"]
    port incus-net29-lr-lrp-ext
        mac: "00:16:3e:51:76:bd"
        networks: ["10.20.30.51/24"]
    nat 84360452-8038-430e-a151-5066d1573a0c
        external ip: "10.20.30.51"
        logical ip: "10.71.59.0/24"
        type: "snat"
root@f8:~# incus network delete v1
Error: failed to notify peer 10.20.30.3:8443: Failed deleting OVS chassis "f11" from chassis group "incus-net29": object not found
root@f8:~# microovn.ovn-nbctl show
root@f8:~# 
```

**Comment by stgraber** [comment]
I've got that one reproduced locally, it didn't trip our testing due to automated testing only running on single-chassis deployments...

**Comment by stgraber** [comment]
The fix for this one is now in the zabbly stable repository.

**Comment by panfantastic** [comment]
Thank you!  I saw a short while ago that it was in zabbly stable and can confirm all is working as expected.
