### ISSUE TITLE
Add `all-projects` support for storage buckets

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#715]
Similar to the work that's been done on instances, images, storage volumes and more, it'd be good to support the `?all-projects=true` URL parameter for `/1.0/storage-pools/POOL/buckets`.

To do this, we'll need:
 - API extension (`storage_buckets_all_projects`)
 - GetStoragePoolBucketsAllProjects function in `client`
 - Support for `all-projects=true` in `storagePoolBucketsGet`
 - Support for `--all-projects` flag in `incus storage bucket list` (cmd/incus)

**Comment by sona78** [comment]
I would love to complete this task if it hasn't been assigned yet

**Comment by stgraber** [comment]
Sure, I assigned it to you now!
