### ISSUE TITLE
Add `all-projects` support for networks

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#716]
Similar to the work that's been done on instances, images, storage volumes and more, it'd be good to support the `?all-projects=true` URL parameter for `/1.0/networks`.

To do this, we'll need:
 - API extension (`networks_all_projects`)
 - GetNetworksAllProjects function in `client`
 - Support for `all-projects=true` in `networksGet`
 - Support for `--all-projects` flag in `incus network list` (cmd/incus)

**Comment by sona78** [comment]
Would love to help out with this issue

**Comment by stgraber** [comment]
@sona78 assigned it to you
