### ISSUE TITLE
Add customizable columns to `incus network list`

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#719]
Similarly to `incus list`, `incus image list`, `incus config trust list` and others.

It would be good to have `incus network list` also feature a customizable list of columns.

**Comment by amroKerkizz** [comment]
Hi! My partner and I are a group from UT and would love to take this issue on if it's still up

**Comment by stgraber** [comment]
Done!

**Comment by amroKerkizz** [comment]
Already have too many issues so I unassigned myself!

**Comment by sharkman424** [comment]
Hello, could my group take over this issue please? We are also from UT Austin doing an open source contribution project.

**Comment by stgraber** [comment]
Done!

**Comment by sharkman424** [comment]
PR opened
