### ISSUE TITLE
Command tls2jwt not found

### ISSUE THREAD

**Issue by Sanes** [lxc/incus#728]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "incus info" or if that fails:
   * Incus version: 0.7 daily

# Issue description
```
tls2jwt client.key client.crt now 120
tls2jwt: command not found
```

**Comment by stgraber** [comment]
`tls2jwt` is an example tool which we have in our testsuite, not a stable production binary that we ship.

You can build it for yourself with `go install -v -x github.com/lxc/incus/test/tls2jwt@latest`
