### ISSUE TITLE
incus info: maintain the order of network interfaces

### ISSUE THREAD

**Issue by istankovic** [lxc/incus#735]
# Required information

 * Distribution: Archlinux
 * The output of "incus info" or if that fails:
   * Kernel version: 6.8.2-arch2-1
   * LXC version: 5.0.3
   * Incus version: 0.7

# Issue description

The order of network interfaces as shown by `incus info <instance>` may differ between invocations for the same instance.
This makes it harder to spot changes between repeated invocations so it would make sense to output the interfaces in some order, e.g. lexicographic.

**Comment by trannlong** [comment]
Hi, we're a group from UT Austin and we'd like to tackle this issue. Could we get it assigned to us please?

**Comment by stgraber** [comment]
Done!

**Comment by stgraber** [comment]
Hey @trannlong, we got a PR fixing this from @MHaukelid so this one has now been resolved.
Let me know if there's something else you'd like to pick up.

**Comment by istankovic** [comment]
Thanks!
