### ISSUE TITLE
Architectural Feedback: More/Less declarative configuration

### ISSUE THREAD

**Issue by rvveber** [lxc/incus#737]
I and probably many others, work with incus irregularely.

It is hard for me, to remember the configuration options + the command syntax, that go into creating an instance.
It is a large task to overcome, when you want to add a container that fits into your existing, maybe, very custom infrastructure.
It becomes an increasingly large task, the more time is between instance creation.

This makes it exponentially difficult to efficiently and reliably create new instances.

The solution to this are boilerplate/template configurations that you will copy and modify at best.
Another solution might be to write a bash script that executes pre-configured incus commands.

But what if one already created a lot of instances and other incus entities, and in hindsight wants to migrate to declarative configuration files?
Yes, they could write the output of "incus config show <instance_name> --expanded"  and go through every single instance and all linked entitites.
They would need architectural knowledge about the entities that exist, how they are linked with each other, and they would need to create a file, a directory, potentially a directory structure, and the actual yml configuration itself.
Then they would still need to remember how to inject the files, or build a script around it to keep overview.
It is really painful and time-consuming to do so, as one would need to build a directory with a yaml configuration for every entity. 

Here, i propose inspiration to the docker-compose- or the nftables equivalent.
A global configuration object, that is natively encouraged by incus, to compose configurations declaratively and iteratively.
I propose to shift the priority for entity configuration/creation to a declarative concept and encourage the use of it more in the documentation.

I believe, one is able to export a "global"/all-entity-inclusive configuration object already, but they are not encouraged to do so, one would need to explicitly find out how to do so, and this is enough to prevent it from happening right at the beginning.
Therefore i hereby request 
- More focus and encouragement on declarative configuration, both in the cli, as well as in the docs.
Or
- No change in focus and instead a way, to generate the creation command from an existing entity, leaving out default values, effectively reverse-engineering the initial command it took, to create the entity.

**Comment by adamcstephens** [comment]
For declarative configurations there is the Incus Terraform provider https://github.com/lxc/terraform-provider-incus

I don't necessarily like that it keeps its own extra set of state of all the resources, but it does exist today and can fit this need. I'm a big fan of declarative configuration though, and would love to see this as a native option .

**Comment by stgraber** [comment]
Agreed, tools like Terraform, for which we produce an official provider as well as other related tools like Ansible are a much better place to handle this kind of thing.

For simpler template type cases, Incus profiles can be a good solution too.

**Comment by rvveber** [comment]
@stgraber Understandable, but profiles are unfortunately only usable with instances, or am i missing something?
What if i need to configure networking? 
Looks like i can't even push a yml file as config to the command for creating a network. 

What do you think about the simple solution, to allow passing .yml files to every entity creation command?
And another QOL command to generate entity creation and entity modification commands from existing entities?

(I will give Ansible a try, altough i have not yet worked with it, i believe it will be worth the time investment.)

**Comment by jarrodu** [comment]
> What do you think about the simple solution, to allow passing config/yml files to every entity creation command?

Which entities don't allow this? I think most of them do. Or at least you can edit them after they are created and then pass the YAML in through redirection.

> (I will give Ansible a try, altough i have not yet worked with it, i believe it will be worth the time investment.)

I think you might be better off starting with Terraform. Ansible is great after the the instances and infrastructure are already deployed. When you get the network, storage, and instances running, then Ansible comes in to finish the job.

Both are well worth the time investment. :-)

Feel free to come over to the [Discourse forum](https://discuss.linuxcontainers.org/).

**Comment by stgraber** [comment]
Currently only `incus create` and therefore `incus launch` allow reading from stdin at create time, I agree we should expand that to all other `create` commands.
