### ISSUE TITLE
Cannot create vm in a nested incus with delegated zfs volume

### ISSUE THREAD

**Issue by tangruize** [lxc/incus#739]
# Required information

 * Distribution: Linux tryit 6.8.4-zabbly+ #ubuntu22.04 SMP PREEMPT_DYNAMIC Fri Apr  5 19:25:12 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux <https://linuxcontainers.org/incus/try-it>

# Issue description

When create a vm inside a nested incus container with delegated zfs volume, it failed with the following msg:

```txt
root@ubuntu:~# incus launch images:ubuntu/24.04 ubuntu-vm2 --vm -s zfs
Launching ubuntu-vm2
Error: Failed instance creation: Failed creating instance from image: Could not locate a zvol for default/containers/ubuntu/incus/images/0524672cd1ca49c520c2792543e7ea6306867dad05120b3dd282ffc094229f89.block
```

# Steps to reproduce

 1. Init an ubuntu container using incus, give proper zfs and nesting permissions and passthough devices for vm:
```sh
incus storage set default volume.zfs.delegate true
incus launch images:ubuntu/24.04 ubuntu
incus config set ubuntu security.nesting true
x=kvm
incus config device add ubuntu $x unix-char path=/dev/$x
x=vsock
incus config device add ubuntu $x unix-char path=/dev/$x
x=vhost-net
incus config device add ubuntu $x unix-char path=/dev/$x
x=vhost-vsock
incus config device add ubuntu $x unix-char path=/dev/$x
```
 2. Run incus inside the ubuntu container:
```sh
apt update
apt install zfsutils-linux incus qemu-system-x86
incus admin init
incus storage create zfs zfs source=default/containers/ubuntu/incus
incus launch images:fedora/39 fedora-container -s zfs    ## success
incus launch images:ubuntu/24.04 ubuntu-vm --vm          ## success
incus launch images:ubuntu/24.04 ubuntu-vm2 --vm -s zfs  ## failed
```

**Comment by stgraber** [comment]
That's unfortunately expected behavior.

Block devices aren't currently namespaced which makes it impossible for a container to own zvols at this time and in turn breaks the creation of virtual machines on a delegated ZFS volume.
