### ISSUE TITLE
apparmor's is_container_with_internal_policy() on Debian/Ubuntu does not recognize incus

### ISSUE THREAD

**Issue by jdstrand** [lxc/incus#740]
This is technically a distro issue, but filing it here in case someone wants to do something within incus or use this as a tracking bug to fix the distributions.

After migrating containers from lxd to incus, I noticed that apparmor is not loading. This is due to `/lib/apparmor/rc.apparmor.functions` on (at least) Ubuntu 22.04 (other releases (eg, 18.04) might use `/lib/apparmor/functions`):
```
is_container_with_internal_policy() {
	# this function is sometimes called independently of
	# is_apparmor_loaded(), so also define this here.
	local ns_stacked_path="${SFS_MOUNTPOINT}/.ns_stacked"
	local ns_name_path="${SFS_MOUNTPOINT}/.ns_name"
	local ns_stacked
	local ns_name

	if ! [ -f "$ns_stacked_path" ] || ! [ -f "$ns_name_path" ]; then
		return 1
	fi

	read -r ns_stacked < "$ns_stacked_path"
	if [ "$ns_stacked" != "yes" ]; then
		return 1
	fi

	# LXD and LXC set up AppArmor namespaces starting with "lxd-" and
	# "lxc-", respectively. Return non-zero for all other namespace
	# identifiers.
	read -r ns_name < "$ns_name_path"
	if [ "${ns_name#lxd-*}" = "$ns_name" ] && \
	   [ "${ns_name#lxc-*}" = "$ns_name" ]; then
		return 1
	fi

	return 0
}
```

This can be worked around by adjusting it to have:
```
	# LXD, LXC and incus set up AppArmor namespaces starting with "lxd-",
	# "lxc-", and "incus-" respectively. Return non-zero for all other namespace
	# identifiers.
	read -r ns_name < "$ns_name_path"
	if [ "${ns_name#lxd-*}" = "$ns_name" ] && \
	   [ "${ns_name#lxc-*}" = "$ns_name" ] && \
	   [ "${ns_name#incus-*}" = "$ns_name" ] ; then
		return 1
	fi

	return 0
```

**Comment by jdstrand** [comment]
In a Ubuntu 22.04 container, I decided to do this to handle updates to apparmor blowing away the changes:
```
$ sudo mkdir /etc/systemd/system/apparmor.service.d
$ sudo sh -c "cat <<EOF > /etc/systemd/system/apparmor.service.d/override.conf
[Service]
ExecStartPre=sed -i 's/lxd-/incus-/' /lib/apparmor/rc.apparmor.functions
EOF
"

$ sudo systemctl daemon-reload
$ sudo systemctl stop apparmor ; sudo systemctl start apparmor

# this now show the (non-snapd) profiles
$ sudo aa-status
```

**Comment by stgraber** [comment]
Hey there, 

Yeah, I've noticed that quite a few months ago and I immediately sent a fix upstream which has been merged. 

After that, it's unfortunately up to individual distros whether to pick up the fix from upstream...

You may want to file an Ubuntu bug to see if the upstream fix can be SRUed in this case. 

So far my instructions for anyone impacted has been to run:
```
sed -i "s/lxd/incus/g" /lib/apparmor/rc.apparmor.functions
reboot
```

It's not the cleanest workaround but it's simple and effective.

**Comment by stgraber** [comment]
Ah and indeed your approach of putting it in systemd will have it survive package updates too without the need to reapply it.

**Comment by jdstrand** [comment]
> You may want to file an Ubuntu bug to see if the upstream fix can be SRUed in this case.

https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2060535

**Comment by stgraber** [comment]
Thanks!
