### ISSUE TITLE
security.ipv4_filtering flag does not use the IP address provided via cloud-init

### ISSUE THREAD

**Issue by atomus1990** [lxc/incus#746]
Step 1

 Launch a VM that uses cloud-init:

name: vm5
description: vm5
type: virtual-machine
profiles:
  - default
source:
  alias: ubuntu/jammy/cloud
  mode: pull
  protocol: simplestreams
  server: https://images.linuxcontainers.org
  type: image
devices: 
  eth0:
    host_name: vm5.vif0
    hwaddr: aa:bb:aa:bb:aa:cc
    name: vif0
    network: net1
    type: nic
  root:
    path: /
    pool: local
    size: 20GiB
    type: disk
config: 
  cloud-init.network-config: |-
    version: 2
    ethernets:
      eth0:
        match:
          macaddress: 'aa:bb:aa:bb:aa:cc'
        set-name: eth0
        addresses:
          - 10.18.218.100/24  <<<
        routes:
          - to: default
            via: 10.18.218.1
        nameservers:
          addresses:
            - 8.8.8.8
       
Step 2

Activate security.ipv4_filtering: "true"

Step 3

Check nftables rules:

 chain fwd.vm5.eth0 {
                type filter hook forward priority filter; policy accept;
                iifname "vm5.vif0" ether saddr != aa:bb:aa:bb:aa:cc drop
                iifname "vm5.vif0" arp saddr ether != aa:bb:aa:bb:aa:cc drop
                iifname "vm5.vif0" icmpv6 type nd-neighbor-advert @nh,528,48 != 0xaabbaabbaacc drop
                iifname "vm5.vif0" arp saddr ip 10.18.218.2 accept <<<
                iifname "vm5.vif0" ip saddr 10.18.218.2 accept <<<
                iifname "vm5.vif0" ether type arp drop
                iifname "vm5.vif0" ether type ip drop
                iifname "vm5.vif0" ether type != { ip, arp, ip6 } drop
        }

Instead of using the 10.18.218.100 address, it uses 10.18.218.2

**Comment by atomus1990** [comment]
The nftables uses the address if specified:

 ipv4.address:  10.18.218.99

**Comment by stgraber** [comment]
That's normal, Incus doesn't inspect the content of the container or whatever provisioning tool you may be using to apply a static configuration.

You need to set `ipv4.address` on your network interface in the Incus config for Incus to be able to apply the policy.
