### ISSUE TITLE
Make sure to connect to OVN during cluster join (before bringing up networks)

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#748]
Currently in environments where we need to connect to the OVN NB DB, Incus only does so after attempting to bring up the current networks. That obviously can't work, so some re-shuffling of joining logic is needed.

**Comment by athulnair02** [comment]
Hi, I would like to try and work on this issue! Where is a good place to start looking and focusing on?

**Comment by stgraber** [comment]
Hey there, this one is already assigned (to me) as I've got some preliminary code to debug it and initial fixes (it's part of the cluster join logic).
