### ISSUE TITLE
Incus on Opensuse Tumbleweed

### ISSUE THREAD

**Issue by Vukodlak7** [lxc/incus#751]
Has anybody managed to get Incus to run on Opensuse Tumbleweed?
I know there are no packages for it, and i tried to build from source and that was a dependency nightmare.
I used LXC for a long time and now that I can only install Ubuntu it is useless to me.

**Comment by stgraber** [comment]
Support questions should go to https://discuss.linuxcontainers.org

We don't directly handle packaging in any distro, so while we'd love for OpenSUSE to finally get a native Incus package, we have really no influence on this, other than nagging @cyphar every so often!

Someone does maintain some unofficial builds for OpenSUSE though, so maybe give that one a shot?
https://build.opensuse.org/package/show/home:cmspam:branches:home:MaxxedSUSE/incus

**Comment by Vukodlak7** [comment]
Many thanks stgraber for pointing me in the right direction!  I am getting desperate at this point haha
I will post it in the support linuxcontainers
