### ISSUE TITLE
Add support for ZFS mirror/striping

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#752]
We should expand the syntax of `source` on ZFS storage pools to support:
 - striping (multiple zdevs)
 - mirroring (mirrored zdevs)
 - RAID5 (raidz1)
 - RAID6 (raidz2)

Probably something like:
 - `source=/dev/sda,/dev/sdb`
 - `source=mirror=/dev/sda,/dev/sdb`
 - `source=raidz1=/dev/sda,/dev/sdb,/dev/sdc,/dev/sdd,/dev/sde`
 - `source=raidz2=/dev/sda,/dev/sdb,/dev/sdc,/dev/sdd,/dev/sde`

For now we'll stay away from doing multiple mirrors or mix of raidz levels and the like, but the syntax above should hopefully allow for some of that as well as eventual addition of things like arc and log devices.

**Comment by ps-gill** [comment]
Is this one still available? I'm willing to work on it.

**Comment by stgraber** [comment]
Sure, got it assigned to you!

**Comment by cyphar** [comment]
At the moment, if you use an existing ZFS pool name as the storage source you can set it up however you like. Is that not intended?

I'm not sure it would be a good idea to put the initial pool configuration in the incus config format. Once you've configured a ZFS pool, ZFS doesn't care about the names assigned to individual drives (instead, `zpool import` looks at the unique ID stored on each drive in the pool) and the layout is all stored on the drives themselves. Not to mention the pool layout can change afterwards through regular ZFS administration. Almost all ZFS users would expect the pool name to be the thing incus cares about, and IMHO would expect ZFS to be configured directly.

(Also, being able to refer to the pool purely by name means that if you want to migrate the pool you can use `zfs send | zfs recv` to migrate the pool, rename the new pool and AFAIK incus will use the new pool without issues.)

Then again, maybe I'm misunderstanding the aim of this feature.

**Comment by stgraber** [comment]
Incus always rewrites the source property to the pool name after creating it so that won't change with this. 

This will however allow for the creation of more complex zpool through the API alone, making it possible to automate production cluster deployments without having to separately handle this stuff through ssh.
