### ISSUE TITLE
6.0 - UI issue

### ISSUE THREAD

**Issue by ThinkFar** [lxc/incus#766]
After successfully installing Incus on Debian 12 using APT Backport, exposing it to the network through incus init, and attempting to access the appropriate port and <ipv4>:8443/ui address, a 404 error is encountered.

When I utilized Zabbly to install earlier versions on Debian 11, it worked seamlessly with the same configuration. 

Am I missing something? 

If there is anything I can do to assist with debugging, please let me know!

Thanks for incus and lxc!

**Comment by stgraber** [comment]
The Zabbly packages that I provide do indeed offer a packaged version of the LXD UI (renamed to Incus UI). Not all distributions are going to do that and Debian currently does not provide a UI package.

**Comment by stgraber** [comment]
There is no official Incus UI, Incus will simply look at the INCUS_UI environment variable and serve whatever is stored at that path as the UI when you access /ui/.

The Zabbly packages have the `incus-ui-canonical` package which puts the rebranded LXD UI into /opt/incus/ui/ and makes sure that Incus starts with INCUS_UI=/opt/incus/ui/ set in its environment.

Looking at repology, it looks like other than the Zabbly packages, only ArchLinux provides UI packages at this time.

**Comment by ThinkFar** [comment]
I attempted to revert to the Zabbly package on Debian 12, but now, upon accessing /ui/, it returns a 304 error.

**Comment by stgraber** [comment]
Hmm, 304 is pretty unusual, that's not something we return inside of Incus.

What do you get if you do `curl -k https://localhost:8443/ui/`?

**Comment by ThinkFar** [comment]
`curl -k https://localhost:8443/ui/`

Results in:

`<pre>
</pre>`

**Comment by stgraber** [comment]
What do you have in `/opt/incus/ui/`? Especially the content of the `index.html` file that should be in there.

**Comment by ThinkFar** [comment]
I installed Incus with Zabbly on Debian 12. 

The `ui` folder is empty.

**Comment by stgraber** [comment]
Did you install the `incus-ui-canonical` package?

**Comment by ThinkFar** [comment]
I thought it was included in the Zabbly package. I tried to find documentation for the installation but couldn't find it.

**Comment by gibmat** [comment]
> Debian currently does not provide a UI package.

Just in case anyone comes across this in the future, [Debian bug #1067132](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1067132) is where any progress on packaging a web-based UI for Incus will be tracked.
