### ISSUE TITLE
Unable to set limits.memory.swap on restricted projects

### ISSUE THREAD

**Issue by victoitor** [lxc/incus#808]
# Required information

 * Distribution: Debian
 * Distribution version: 12
 * The output of "incus info" or if that fails:
   * Kernel version: 6.1.0-18-amd64
   * Incus version: 6.0
   * Storage backend in use: btrfs

# Issue description

Unable to set limits.memory.swap on a restricted project even when restricted.containers.lowlevel is set to allow.

# Commands
```
pargo@bastion:~$ incus profile set keycloak limits.memory.swap=2GB
Error: Failed checking if profile update allowed: Use of low-level config "limits.memory.swap" on profile "keycloak" of project "sandbox" is forbidden
pargo@bastion:~$ incus project show sandbox
config:
  features.images: "true"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
  restricted: "true"
  restricted.backups: allow
  restricted.cluster.groups: compartilhado
  restricted.cluster.target: allow
  restricted.containers.interception: allow
  restricted.containers.lowlevel: allow
  restricted.containers.nesting: allow
  restricted.devices.nic: allow
  restricted.snapshots: allow
description: ""
name: sandbox
```

**Comment by stgraber** [comment]
Yes, that is absolutely intentional.

Swap space effectively allows exceeding the memory limit on the project and so requires the project to be configured to access low-level keys in order to be allowed (`restricted.containers.lowlevel=allow`).

**Comment by victoitor** [comment]
> Yes, that is absolutely intentional.
> 
> Swap space effectively allows exceeding the memory limit on the project and so requires the project to be configured to access low-level keys in order to be allowed (`restricted.containers.lowlevel=allow`).

On the command section I show the the error together with the project configurations and it is set to allow. There's also no memory limit on this project.

**Comment by stgraber** [comment]
Oh, oops, I missed that, not sure what's going on with the check then.

**Comment by stgraber** [comment]
Ah, I see, it's the profile handling in the check that's a problem.

**Comment by TinkeringWithUS** [comment]
We would like to take this issue if it is open. Can you also give some pointers on where to start @stgraber ? Thanks!

**Comment by stgraber** [comment]
@TinkeringWithUS sorry, I already started looking at this one because of the Incus 6.1 release due out in a few hours.

**Comment by TinkeringWithUS** [comment]
Thanks for the quick response. If there's anything we can help with the new Incus release, we would gladly take it on.
