### ISSUE TITLE
Add `get_project` instance placement scriptlet function

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#811]
Similar to the recently added `get_instances` and `get_cluster_members` functions that were added in #780, it'd be very useful to have a `get_project(name)` function that would give us the `api.Project` value for the named project.

This could then be used in scriptlets that need to look up specific project restrictions or limits.

**Comment by rpunjani** [comment]
Hello, I'm a student from UT Austin taking the virtualization course (360v). I was wondering if I could tackle this issue. Thanks.

**Comment by stgraber** [comment]
Sure, assigned it to you!
