### ISSUE TITLE
LXD->Incus regression: `incus shell` no longer has autocomplete

### ISSUE THREAD

**Issue by kkremitzki** [lxc/incus#814]
# Required information

 * Distribution: Debian
 * Distribution version: 12
 * The output of "incus info" or if that fails:
   * Kernel version: 6.1.0-20-amd64
   * LXC version: Does this refer to e.g. `liblxc1`? If so, `1:5.0.2-1+deb12u2`. In case it's relevant, the LXD version is `5.0.2-5`.
   * Incus version: 6.0.0-1~bpo12+1
   * Storage backend in use: N/A

# Issue description

I am working on migrating my Debian hosts from LXD onto Incus, available via `bookworm-backports`. However, it seems there's been a behavior regression for both bash and zsh shell completion. `lxc shell` completes instance names, but `incus shell` does not. The command itself also lost shell completion, besides not completing instance/container names.

# Steps to reproduce

 1. Launch two VMs with Incus: `incus launch images:debian/bookworm/cloud --vm lxd-vm && incus launch images:debian/bookworm/cloud --vm incus-vm`.
 2. Install LXD on the first one: `incus exec lxd-vm -- sh -c 'apt update && apt install -y lxd iptables && lxd init --auto && usermod -aG lxd debian`
 3. Install Incus on the second one: `incus exec incus-vm -- sh -c 'echo deb http://deb.debian.org/debian bookworm-backports main | tee /etc/apt/sources.list.d/backports.list && apt update && apt install -y -t bookworm-backports incus && incus admin init --auto && usermod -aG incus-admin debian'`
 4. Enter the LXD VM: `incus exec lxd-vm -- su -l debian`. Source the completion script: `source /usr/share/bash-completion/completions/lxc`. Type `lxc sh<tab>` and note the command is completed. If you create a container, `lxc shell <tab>` will complete the container's name.
 5. Enter the Incus VM: `incus exec incus-vm -- su -l debian`. Source the completion script: `source /usr/share/bash-completion/completions/incus`. Type `incus sh<tab>` and note no command completion occurs. Similarly, if you create a container, its name will not be completed if you type `incus shell <tab>`.

**Comment by stgraber** [comment]
That has already been fixed in the main branch.

**Comment by gibmat** [comment]
I'll cherry-pick #755 into Debian's packaging. (No ETA on when the next package upload will be.)

**Comment by kkremitzki** [comment]
Oops, I tried testing with a main build but I must have not done it correctly. Thanks for the quick response and thanks @gibmat for the reference & offer to fix in Debian!
