### ISSUE TITLE
During tar image unpacking, all dev folders excluded not just /dev and /rootfs/dev

### ISSUE THREAD

**Issue by carbonXIII** [lxc/incus#815]
# Required information

 * Distribution: Fedora CoreOS
 * Distribution version: Rawhide
   * Kernel version: 6.7.0-68.fc40.x86_64
   * Incus version: 6.0.0
   * Storage backend in use: zfs

# Issue description

Attempting to create an instance from a tar file including any folder named `dev` (not just `/dev` or `/rootfs/dev`) will exclude that folder from the image. In my particular case, there is a hard link to the file that was not loaded, so image unpacking fails entirely.

# Steps to reproduce

0. Create a problematic tar file (here's a minimal example, not a real "working" image):
```bash
cd $(mktemp -d)

mkdir -p rootfs/bad/dev/
touch rootfs/bad/dev/a
ln rootfs/bad/dev/a rootfs/b

cat << EOF > metadata.yaml
architecture: x86_64
creation_date: 1424284563
properties:
  description:  Bad image
  os: Fedora CoreOS
EOF

tar -cvf bad_image.tar $(find . -type f)
```
 1. Add a container image from the tar file
```bash
incus image import bad_image.tar --alias bad_image
```
 2. Attempt to create an instance from the image
```bash
incus create bad_image badnode
```

This fails with:
```
Creating badnode
Error: Failed creating instance from image: Unpack failed: Failed to run: tar --wildcards --exclude=dev/* --exclude=./dev/* --exclude=rootfs/dev/* --exclude=rootfs/./dev/* --restrict --force-local -C /var/lib/incus/storage-pools/data/images/d1697f737957879cb930b067f2c46b60019b4df33233b2f9b31bcfaa0315d5b6 --numeric-owner --xattrs-include=* -xf -: exit status 2 (tar: ./rootfs/b: Cannot hard link to ‘./rootfs/bad/dev/a’: No such file or directory
tar: Exiting with failure status due to previous errors)
```

For the record this is caused by [this tar flag](https://github.com/lxc/incus/blob/410ecc8292b4a78fd556f0c39da410f34cb7f58f/shared/archive/archive.go#L146) in the unpacking code:
```
args = append(args, "--exclude=dev/*")
```
On my system at least, this `tar` wildcard seems to match any file in folders named `dev`

Here's my `tar --version` as well
```
tar (GNU tar) 1.35
```

**Comment by candlerb** [comment]
Could this be considered for backport to incus 6.0 LTS please?

Stock Ubuntu 24.04 has a file which is affected by this, in the `dhcpcd-base` package which is installed as a dependency of `cloud-init`

```
rootfs/usr/lib/x86_64-linux-gnu/dhcpcd/dev/udev.so
                                       ^^^
```

More info: https://discuss.linuxcontainers.org/t/file-goes-missing-during-image-publish-usr-lib-x86-64-linux-gnu-dhcpcd-dev-udev-so/19969

**Comment by stgraber** [comment]
All bugfixes will make it into 6.0.1.
