### ISSUE TITLE
Add generated documentation for image restrictions

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#820]
Incus is slowly moving to automatically generated documentation for its configuration keys.

This can be done through the `gendoc:generate` type comments in the code, followed by running `make update-metadata` and consumption in the documentation through `{include} ../config-option.txt`.

This issue is for the keys defined in `doc/image-handling.md` to be moved to code in `internal/server/instance/drivers/driver_lxc.go` and `internal/server/instance/drivers/driver_qemu.go`.

**Comment by TinkeringWithUS** [comment]
Can I get this assigned? We just to have the gen doc comment above where the parameter is being assigned right?

**Comment by stgraber** [comment]
Done!

**Comment by TinkeringWithUS** [comment]
Thanks! How can I validate that documentation is correct?

**Comment by TinkeringWithUS** [comment]
The defaults in the documentation is a hyphen, -. In the gendoc comment, would it be better for the default to be specified as a blank like so "default: " or just not leave out the default field entirely?

**Comment by stgraber** [comment]
I think we've usually just left out the default value in such cases.

And yeah, right above the actual check is fine for keys like those which don't have a validator.

**Comment by TinkeringWithUS** [comment]
<img width="586" alt="ss_incus_image_requirements" src="https://github.com/lxc/incus/assets/112668294/723f4dbe-f11f-456e-ae2f-6a21a619d8ea">
Is this current format fine for image requirements? For comparison, the current key display. 
<img width="586" alt="ss_incus_regular_image" src="https://github.com/lxc/incus/assets/112668294/a3420075-d145-4c9a-9e0f-08f1e1d59009">
