### ISSUE TITLE
Add generated documentation for network zones

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#821]
Incus is slowly moving to automatically generated documentation for its configuration keys.

This can be done through the `gendoc:generate` type comments in the code, followed by running `make update-metadata` and consumption in the documentation through `{include} ../config-option.txt`.

This issue is for the keys defined in `doc/howoto/network_zones.md` to be moved to code in `internal/server/network/zone/zone.go`.

**Comment by rpunjani** [comment]
Hello. Can I get this issue assigned to me? Thanks.

**Comment by stgraber** [comment]
Done!

**Comment by rpunjani** [comment]
I was wondering what the "entity" and "group" parameters would be?

**Comment by stgraber** [comment]
entity would be `network_zone`, group will be one of `peers`, `dns`, `network` or `user` depending on the key
