### ISSUE TITLE
Add generated documentation for instance kernel limits

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#822]
Incus is slowly moving to automatically generated documentation for its configuration keys.

This can be done through the `gendoc:generate` type comments in the code, followed by running `make update-metadata` and consumption in the documentation through `{include} ../config-option.txt`.

This issue is for the keys defined in `doc/reference/instance_options.md` to be moved to code in `internal/instance/config.go`.

**Comment by camnwalter** [comment]
Hi! Can you assign this one to me too?
Is it just the table here: https://github.com/lxc/incus/blob/main/doc/reference/instance_options.md#kernel-resource-limits?

**Comment by stgraber** [comment]
Yep, that's the one
