### ISSUE TITLE
Incus 6.1: Stopped VMs showing error: Error: stat /proc/0: no such file or directory

### ISSUE THREAD

**Issue by cmspam** [lxc/incus#869]
# Required information

 * Distribution: NixOS
 * Distribution version: Unstable

# Issue description

Some change between 6.0 LTS and 6.1 has caused an issue on NixOS with stopped VMs.
Any stopped VM will show the status of ERROR, and running incus info --show-log <VM> results in:
```Error: stat /proc/0: no such file or directory```

This issue does not occur with 6.0 LTS. I opened an issue with NixOS, but it seems to be a likely upstream bug.
https://github.com/NixOS/nixpkgs/issues/311525

# Steps to reproduce

 1. Create VM
 2. Make sure VM is stopped
 3. Run incus info --show-log <VM name>

**Comment by stgraber** [comment]
This was fixed in main a few days ago.

https://github.com/lxc/incus/commit/2fe62a272e3819d0e31ef2a5f8ed5566d607814a

**Comment by adamcstephens** [comment]
@stgraber will there be a point release for this, or should we patch this ourselves until 6.2 ?

**Comment by stgraber** [comment]
Not planning a point release as I wouldn't be able to do it until the end of May, at which point we'd be just a week from 6.2.
