### ISSUE TITLE
Build from Sources - checksum mismatch

### ISSUE THREAD

**Issue by rajbock** [lxc/incus#873]
golang = 1.22.3

6.0.0 works!
6.1.0 ->

verifying github.com/osrg/gobgp/v3@v3.26.0: checksum mismatch
        downloaded: h1:v7Ud/4Ucol5njnuf8Io5JXf6fkdBHMhd68jk9Vq/k0U=
        go.sum:     h1:/iHaQKNgp0dRI3/RGt/j60aUeoGng6CL0VATVfQXEPE=

**Comment by stgraber** [comment]
Hmm, can you try on a clean system or VM? 
That sounds like some kind of network corruption of that dependency. 

Alternatively you can grab the 6.1 release tarball from our website that has the dependencies bundled.

**Comment by stgraber** [comment]
We've not had any other report of issues and our own package builds have been working fine daily, so going to assume this was a temporary glitch.
