### ISSUE TITLE
incus-simplestreams: add options for adding a unified tarball image

### ISSUE THREAD

**Issue by melato** [lxc/incus#888]
incus remote can use a unified tarball image from a simplestreams remote.
But *incus-simplestreams add* does not.  It requires two arguments (metadata file, data file), and supports only squashfs or disk-kvm.img datafiles.

*incus-simplestreams add" can be enhanced to allow either one or two arguments.  If there is a single argument, set the file type to incus_combined.tar.gz.

This will make it easy to:
- use *incus publish* to create an image from a container (generates a unified tarball)
- use *incus image export* to export the resulting unified tarball
- use *incus-simplestreams add* to add the unified tarball to a simplestreams directory.  This is the missing part.

See also https://github.com/lxc/incus/issues/871#issuecomment-2125439522

**Comment by melato** [comment]
You can assign this to me.  It's easy, once I figure out how to submit pull requests properly.

**Comment by stgraber** [comment]
Done!

**Comment by stgraber** [comment]
@melato any luck with this one?

**Comment by melato** [comment]
I'll look at it today, and probably submit it before the end of the month.  I have an implementation that works, but because it involves a bit of refactoring, I want to revisit it so as to avoid reviewing changes multiple times.  I had several distractions in the last month.

**Comment by stgraber** [comment]
Sounds good!

**Comment by melato** [comment]
# Test Procedure
assume $BASE is a base test directory

# create an image
	incus launch images:alpine/3.19 bash1
	incus exec bash1 apk add bash
	incus stop bash1
	incus snapshot create bash1 copy

# publish, export, add to simplestreams
	mkdir -p $BASE/image
	incus publish --alias bash1 bash1
	incus image export bash1 $BASE/image/image

	mkdir -p $BASE/simplestreams
	cd $BASE/simplestreams
	incus-simplestreams add --no-default-alias --alias bash1 $BASE/image/image.tar.gz

# create a "test" simplestreams remote
    create a web server with root at $BASE/simplestreams, at a url, (example url: https://images.example.org)
    incus remote add --protocol simplestreams test $url
	
# test the simplestreams image
	incus launch test:bash1 b1
	incus exec b1 bash
	
I sometimes need to delete a directory from /var/cache/incus,
if launch fails to find the image.

**Comment by melato** [comment]
I created pull request https://github.com/lxc/incus/pull/963 with code that I have tested multiple times, using the test procedure above.  In order to avoid numerous unwieldy if statements, I moved the data file code (computing sha256 hash, detecting or setting various properties) to a separate type.

**Comment by melato** [comment]
A further refactoring would be to share code between metadata and data computations, but I don't want to delay this any further, so I stopped here.

**Comment by melato** [comment]
Forgot to update the command usage.  @stgraber should I add a second pull request, or create a new pull request for both changes?

**Comment by stgraber** [comment]
You can still modify the content of your pull request, either push a second commit in there or amend the one you have and force push.

**Comment by melato** [comment]
I just checked in a code formatting fix, as noted by the automated tests.  I have the pull request in draft status until the tests are clean.

**Comment by melato** [comment]
All tests have passed.  Ready for review:  https://github.com/lxc/incus/pull/963
