### ISSUE TITLE
Failed creating instance record: Instance type "virtual-machine" is not supported on this server: QEMU command not available for CPU architecture

### ISSUE THREAD

**Issue by TheKnarf** [lxc/incus#894]
Trying to run `incus launch images:ubuntu/22.04 ubuntu-vm --vm` gave me the following error:

```
Failed creating instance record: Instance type "virtual-machine" is not supported on this server: QEMU command not available for CPU architecture
```

If you don't have QEMU installed it'll just give you this error message. It would be nice if it actually told you to install QEMU.

I then ran the following to install qemu on my Debian server:

```bash
$ sudo apt install -y qemu-utils qemu-system-x86
```

This still didn't resolve the issue. To solve it I had to restart `incus` by running:

```bash
$ incus admin shutdown
$ incus admin waitready
```

And now finally starting VM's worked.
It would be nice if:

- It could give a better error message. Maybe something along the line of: `qemu-system-x86 is not installed. Install it and retry`

- You didn't have to restart the server for it to pickup the new installation.

<!--
Github issues are used for bug reports. For support questions, please use [our forum](https://discuss.linuxcontainers.org/).

Please fill the template below as it will greatly help us track down your issue and reproduce it on our side.
Feel free to remove anything which doesn't apply to you and add more information where it makes sense.

# Required information

 * Distribution:
 * Distribution version:
 * The output of "incus info" or if that fails:
   * Kernel version:
   * LXC version:
   * Incus version:
   * Storage backend in use:

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Steps to reproduce

 1. Step one
 2. Step two
 3. Step three

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`incus info NAME --show-log`)
 - [ ] Container configuration (`incus config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/incus/incusd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `incus monitor --pretty` while reproducing the issue)

**Comment by stgraber** [comment]
What packages get you the right QEMU bits vary from distribution to distribution and even change between releases, it's not something we can give you in an error message.

**Comment by stgraber** [comment]
The list of instance types supported is part of the most common API route in Incus, on busy servers, that information may be returned multiple times a second, we don't want to hammer the system looking for the QEMU binary every time so we detect all the different virtualization drivers, their versions and capabilities on startup.

**Comment by stgraber** [comment]
What may make sense is to add more detailed instructions for the VM case in doc/installing.md for distros which don't pull in QEMU by default.

**Comment by TheKnarf** [comment]
> What packages get you the right QEMU bits vary from distribution to distribution and even change between releases, it's not something we can give you in an error message.

When its looking for a binary it knows what binary its looking for. So there is no reason you couldn't show that in the message. `QEMU command not available for CPU architecture` is also really confusing at first, so the error message in itself is just bad as a first time user.

> The list of instance types supported is part of the most common API route in Incus, on busy servers, that information may be returned multiple times a second, we don't want to hammer the system looking for the QEMU binary every time so we detect all the different virtualization drivers, their versions and capabilities on startup.

Maybe you could have a filewatch for the routes where QEMU gets installed? That way it can autorefresh once you install a new one.

> What may make sense is to add more detailed instructions for the VM case in doc/installing.md for distros which don't pull in QEMU by default.

At a minimum. But a better error message should be the highest priority. It took me a lot of googling just to even understand the error message, let alone to piece together what it ment.

![Screenshot 2024-05-26 at 11 27 31](https://github.com/lxc/incus/assets/213777/c85d16d5-47dd-4eec-a8d9-78ed40b5583f)

Also; please don't close the issue when you haven't fixed anything... At the very least just tag the issue with `Documentation improvement` or something... Feels kinda rude 😅

**Comment by stgraber** [comment]
> When its looking for a binary it knows what binary its looking for. So there is no reason you couldn't show that in the message. `QEMU command not available for CPU architecture` is also really confusing at first, so the error message in itself is just bad as a first time user.

I'll send a small change to propagate the error we get from exec.LookPath.
So that should result in something like: `QEMU command not available: exec: "qemu-system-XYZ": executable file not found in $PATH`

**Comment by stgraber** [comment]
> Maybe you could have a filewatch for the routes where QEMU gets installed? That way it can autorefresh once you install a new one.

We won't be doing that, no. Those kernel APIs are pretty awful and have caused us performance issues in the past.

**Comment by TheKnarf** [comment]
>> Maybe you could have a filewatch for the routes where QEMU gets installed? That way it can autorefresh once you install a new one.
>
> We won't be doing that, no. Those kernel APIs are pretty awful and have caused us performance issues in the past.

Maybe the error message could reflect that? In other words; could it tell the user that they need to restart the service after install.

Something like:

```
QEMU command not available: exec: "qemu-system-XYZ": executable file not found in $PATH

You can fix this by installing `qemu-system-` using your package manager.
After install you'll need to restart the incus service by running:

$ incus admin shutdown
$ incus admin waitready
```

**Comment by martinrebane** [comment]
Hi! The current error message is totally misleading. It tells me **something that is possible is not possible** "Error: Failed creating instance record: Instance type "virtual-machine" is not supported on this server: QEMU command not available for CPU architecture". In fact, installing qemu helps and solves the problem.

Current way is the worst way to handle this problem! Please do something :)

**Comment by stgraber** [comment]
The error these days is:
```
Error: Failed instance creation: Failed creating instance record: Instance type "virtual-machine" is not supported on this server: QEMU command not available: exec: "qemu-system-x86_64": executable file not found in $PATH
```

**Comment by buildwithdan** [comment]
I used the ubuntu 24.04 LTS , apt install incus for my RPI4, and still having the same issue....

`r00t@rpi4:~/hoas$ incus launch images:ubuntu/22.04 ubuntu-vm --vm
Launching ubuntu-vm
Error: Failed instance creation: Failed creating instance record: Instance type "virtual-machine" is not supported on this server: QEMU failed to run feature checks`

any ideas, busy trying to install other packages to see if I can pin it down. Will post more when fixed on my end.

**Comment by stgraber** [comment]
If you just used the incus from Ubuntu 24.04, it doesn't pull QEMU so it's normal for it not to support VMs unless you manually go and install what it needs for that.

If using the Zabbly repository, then it should have brought everything that's needed for VM support.

**Comment by fanuch** [comment]
Would like to add that I would have kept on going in the wrong direction if not for this thread.
Thanks @TheKnarf for outlining the error and solution in your post.

Agreed that this error message needs a tinker.

```
QEMU command not available for CPU architecture
```

Was not accurate and all I needed was to install `qemu-system` (worked that out) and `incus admin shutdown/waitready` (did not work this out and was deep diving stackoverflow)

--- 

Just realised I didn't see that updated error?

I was catching this in `incus import`
