### ISSUE TITLE
btrfs qgroup limit none -e arguments out of order.

### ISSUE THREAD

**Issue by dazoe** [lxc/incus#895]
I came across this when attempting to recover my incus install from a failed hard drive so not entirely sure how to replicate.
incus is attempting to run `btrfs qgroup limit none -e .... ` i think it should be `btrfs qgroup limit -e none .... `
When I run the command manually using `btrfs qgroup limit none -e .... ` I get 
```
# btrfs qgroup limit none -e 0/323 qtest
usage: btrfs qgroup limit [options] <size>|none [<qgroupid>] <path>

    Set the limits a subvolume quota group.

    -c                        limit amount of data after compression. This is the default, it is currently not possible
                              to turn off this option 
    -e                        limit space exclusively assigned to this qgroup 
```
Seems to be called here
https://github.com/lxc/incus/blob/3f91a7cc74d507668ade85fbb1d0c0c4f902b65f/internal/server/storage/drivers/driver_btrfs_volumes.go#L1138
It is used correctly just a few lines above
https://github.com/lxc/incus/blob/3f91a7cc74d507668ade85fbb1d0c0c4f902b65f/internal/server/storage/drivers/driver_btrfs_volumes.go#L1127

Also I just noticed this seems to affect AlpineLinux but not ArchLinux. Not sure why yet, it might boil down to a difference between glibc and muslc.
I started typing this issue awhile ago and indeed is is a difference between glibc and musl. `GNU getopt permutes argv to pull options to the front, ahead of non-option arguments. musl and the POSIX standard getopt stop processing options at the first non-option argument with no permutation.` -https://wiki.musl-libc.org/functional-differences-from-glibc.html

**Comment by stgraber** [comment]
Yeah, smells like a difference in getopt behavior.
