### ISSUE TITLE
Introduce a proper `inc snapshot` subcommand

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#9]
One bit of inconsistency that's always bothered me with LXD is that `lxc snapshot` and `lxc restore` are top level commands of their own. This makes it very awkward to allow for snapshot listing, renaming, ...

We've been wanting to fix this for years, but couldn't without breaking backward compatibility. As the fork doesn't pretend to be backward compatible at the CLI level, it's a good opportunity to fix that one.

**Comment by monstermunchkin** [comment]
Should there be a proper subcommand for managing storage volume snapshots as well?

**Comment by stgraber** [comment]
Yeah, I think we should do the same thing with `lxc storage volume snapshot` indeed.

**Comment by monstermunchkin** [comment]
I guess what we need is `inc snapshot {create,delete,rename,copy,info,restore}`. And the same for `inc storage volume snapshot {create,delete,rename,copy,info,restore}`.

`inc rename` (and `inc move`) and `inc copy` already support renaming and copying snapshots respectively. Should `inc rename` (and `inc move`) be limited to only support instances? I believe `inc copy` should keep some support for snapshots as one can do this: `inc copy c1/snap0 c2`. But we could drop snapshot to snapshot copying in `inc copy`.

Alternatively, this could be done in `inc snapshot restore` with a third positional argument like this:
```
inc snapshot restore c1 snap0 c2`
```

@stgraber what are your thoughts on this?

**Comment by stgraber** [comment]
Yeah, agreed on the new commands.

For rename/move we should remove the snapshot support.

Copy would keep it but indeed only for creating a new instance from a snapshot.

Support in delete would go away too.
