### ISSUE TITLE
Compleition fix for "Incus publish" command (snapshots)

### ISSUE THREAD

**Issue by rauladler** [lxc/incus#901]
When using “incus publish” command to create template from the snapshot of some instance, then “tab” key from the keyboard is helping with instance name selection, but it does not helping with the snapshot selection.

Fixing this issue would help users to enter commands faster.

Steps to repeat it:
`incus publish _instance-name_/` and press "tab" key from the keyboard.

**Comment by stgraber** [comment]
I sent a branch that fixes this one. It will start completing snapshots as soon as you enter the `/` after an instance name.
