### ISSUE TITLE
Allow pool-specifc disk limits in projects

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#906]
The current `limits.disk` resource limit on projects only allows restricting the overall disk footprint, this is fine in many environments but for those of us with clusters having different class of storage, like:

```
stgraber@castiana:~/data/code/lxc/incus (lxc/main)$ incus storage list s-dcmtl-cluster:
+--------+--------+---------------------------+---------+---------+
|  NAME  | DRIVER |        DESCRIPTION        | USED BY |  STATE  |
+--------+--------+---------------------------+---------+---------+
| hdd    | ceph   | Slow HDD storage          | 9       | CREATED |
+--------+--------+---------------------------+---------+---------+
| local  | zfs    | Local NVME storage        | 63      | CREATED |
+--------+--------+---------------------------+---------+---------+
| shared | cephfs | Shared filesystem storage | 8       | CREATED |
+--------+--------+---------------------------+---------+---------+
| ssd    | ceph   | Fast SSD storage          | 70      | CREATED |
+--------+--------+---------------------------+---------+---------+
```

Having all storage treated equal isn't ideal and so having per-pool limits would be preferable.

The easiest way would be to not only have `limits.disk` but also `limits.disk.pool.XYZ` where `XYZ` in this case would be one of `hdd`, `local`, `shared` or `ssd`.

A limit of `0` would prevent the use for a storage pool entirely and should result in its exclusion from `incus storage list` for that project.

**Comment by awalvie** [comment]
Can I be assigned this issue please!

**Comment by stgraber** [comment]
Cool, I assigned it to you!

**Comment by awalvie** [comment]
Sorry about the delay, but from what I understand I'll have to update `projectConfigKeys` for `func projectValidateConfig` in `api_project.go` with an additional field for `limits.disk.pool.type` but am not sure where the actual limit on the pool gets configured and set after that. I saw that the function gets called as part of `func projectPost`, but that seems to just create an entry in the database. Is there something else that needs to be done outside of that?

**Comment by stgraber** [comment]
Sorry for the delay here.

Note that the key is really meant to be `limits.disk.pool.NAME` so not a static config key name as the pool name will be part of it.

You're correct that the main spot where this needs to be added is in `projectValidateConfig`.
That will allow you to set it through `incus project set`.

The actual enforcement however is done in `internal/server/project/permissions.go` where you'll want to look where current `limits.disk` is checked and add the equivalent per-pool checking.

**Comment by stgraber** [comment]
@awalvie any luck with this one?

**Comment by stgraber** [comment]
Nope, no rush, was just wondering. I hope you had a good vacation!

**Comment by awalvie** [comment]
Sorry about the leave of absence again, I had to go for a company event. I'll be working on this, this week!

**Comment by stgraber** [comment]
sounds great, thanks!

**Comment by awalvie** [comment]
Still haven't been able to find time for this, and I don't wanna keep the issue waiting. Can I be unassigned please. Really sorry for keeping this waiting for so long.

**Comment by stgraber** [comment]
Done!

**Comment by dominicfollett** [comment]
Hey there! I'd love to help out with this issue. I'm pretty new to the Incus project and am just busy getting everything set up.
I can't provide a time estimate just yet, but will keep you updated as I go if that's okay.

**Comment by stgraber** [comment]
Hey @dominicfollett. I'm going to spend a bit of time this afternoon trying to quickly get that one working with a hope of still having it make it to Incus 6.4 (planned for today).

If that doesn't work out, then I'll gladly send over what I have and let you pick it from there with a target of Incus 6.5 (a month or so from now).
