### ISSUE TITLE
upgraded from Incus 6.0 LTS to Incus 6.2 - now "incus ls <instance-name> no longer lists only the <instance-name> but all Incus instances

### ISSUE THREAD

**Issue by bmullan** [lxc/incus#910]
Ubuntu 24.04 host

This past week I upgraded from Incus v6.0 LTS to Incus v6.2

Prior to the upgrade I could execute the following:

> **$ incus ls \<instance-name\>**

and **_it would return only the one table row_** for that \<instance name\>.

_Since the upgrade to Incus 6.2 this no longer works the same.._

> **$ incus ls \<instance-name\>** 

**_now lists ALL Incus Instances?_**

_Is this a bug or a change of function?_

**Comment by bmullan** [comment]
FYI..
I think has something to do with all the updates for Ubuntu 24.04 happening.

Since I was _using Incus 6.2 on both Ubuntu 22.04 and on Ubuntu 24.04_ 
I rebooted to Ubuntu 22.04 and retried the command:

> **$ incus ls \<instance name\>**

*This works and lists only the table row for \<instance name\> again.*

**Comment by stgraber** [comment]
Nothing changed on our side that'd explain that and we actually do have tests on `incus list` for this logic.

Can you maybe see if `incus list` somehow behaves differently from `incus ls`?
If so, then you may want to look at `incus alias list` to see if you don't have a custom definition in place that may explain the difference.

If not, then the `--debug` output may be useful to further track this down.

**Comment by stgraber** [comment]
@bmullan
