### ISSUE TITLE
Allow adding external interfaces to an OVN network

### ISSUE THREAD

**Issue by stgraber** [lxc/incus#937]
We should support `bridge.external_interfaces` with OVN by creating the matching logical switch port, marking its addresses as `unknown` and then connecting that to the interface the user requested.

**Comment by SpiffyEight77** [comment]
@stgraber 
Thank you for your help with the previous PR. 
I'd like to further explore and understand the incus network and do my best to implement this feature.
Could you assign this task to me? 🙇🏻‍♂️

**Comment by stgraber** [comment]
Done!

**Comment by SpiffyEight77** [comment]
I'm still working on this task and I'll try to submit a PR for it by next weekend. 🙇🏻‍♂️

**Comment by stgraber** [comment]
Thanks!

**Comment by SpiffyEight77** [comment]
@stgraber 
I'm truly sorry, I had planned to submit the PR this weekend, but work has gotten busier recently, so I need more time to prepare the PR. I apologize for informing you so late. 🙇🏻‍♂️

**Comment by stgraber** [comment]
No worries!

**Comment by stgraber** [comment]
@SpiffyEight77 how's it going with this one?

**Comment by SpiffyEight77** [comment]
@stgraber 
Thank you for asking. I'm currently running some tests on my local environment and may need a bit more time.

**Comment by stgraber** [comment]
Sounds good!
