### ISSUE TITLE
Ubuntu 24.04 failed create bucket

### ISSUE THREAD

**Issue by Sanes** [lxc/incus#940]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 24.04
 * The output of "incus info" or if that fails:
 * Incus version: 6.0

`# incus storage bucket create default image`

`Error: Failed creating storage bucket: Failed connecting to bucket: exec: "minio": executable file not found in $PATH`

**Comment by stgraber** [comment]
That's not an Incus issue but a packaging one.

I suspect you installed `incus` directly from Ubuntu 24.04 which uses the lightweight package that comes from Debian. This doesn't bring in minio for you, so you'll need to get that installed on the system by yourself.

An alternative would be to use the packages that I produced which are much heavier weight and do come with minio out of the box. https://github.com/zabbly/incus
