### ISSUE TITLE
localectl fails inside container running debian 12

### ISSUE THREAD

**Issue by iils-jschmidt** [lxc/incus#947]
`localectl` fails inside an incus container running debian 12. Reason: `localectl` depends on `systemd-localed` which (at least on Debian 12) uses PrivateNetwork=yes. Which is blocked by apparmor of the host. 

 * Distribution: debian 12 (host and container)
 * Kernel version: Linux version 6.1.0-21-amd64
 * Incus version: 6.0.0 (from backports)
 * Storage backend in use: ZFS

**Comment by stgraber** [comment]
```
stgraber@dakara:~$ incus launch images:debian/12 d12
Launching d12
stgraber@dakara:~$ incus exec d12 bash      
root@d12:~# localectl 
System Locale: LANG=en_US.UTF-8
    VC Keymap: (unset)         
   X11 Layout: (unset)         
root@d12:~# systemctl -a | grep systemd-localed
  systemd-localed.service              loaded    active   running   Locale Service
root@d12:~# 
```

**Comment by iils-jschmidt** [comment]
```
root@container-host:~# incus launch images:debian/12 d12
Launching d12
root@container-host:~# incus exec d12 bash
root@d12:~# localectl
```
nothing ...

on host's syslog:

> Jun 20 11:45:25 container-host kernel: [1424311.878907] audit: type=1400 audit(1718876725.939:181): apparmor="DENIED" operation="file_lock" profile="incus-d12_</var/lib/incus>" pid=155352 comm="(-localed)" family="unix" sock_type="dgram" protocol=0 requested_mask="send"

**Comment by gibmat** [comment]
Looks like the known apparmor bug in the 6.1 LTS kernel. (See the last bullet point under "other issues" here: https://wiki.debian.org/LXD#Other_issues. It applies equally to LXD and Incus.)

**Comment by stgraber** [comment]
Yeah and that explains why I'm not seeing it here as I'm using Debian 12 but with mainline kernels.

**Comment by iils-jschmidt** [comment]
Thanks for the pointer. The newer kernel is necessary to use ZFS with id shifting.
