### ISSUE TITLE
Adding Red Hat distrobuilder installation to the "Installing from source" section

### ISSUE THREAD

**Issue by cemzafer** [lxc/incus#954]
# Required information

 * Distrobuilder installation
 
# Issue description

There are Debian based and ArchLinux based informations on the distrobuilder page, https://github.com/lxc/distrobuilder.
The following information can be added to the page as follows.

Red Hat-based:

sudo dnf update
sudo dnf install golang debootstrap rsync gnupg2 squashfs-tools git make

Thanks.

**Comment by stgraber** [comment]
Just noticed that this was filed in the wrong repo and a fix was already merged in the distrobuilder repo.
