### ISSUE TITLE
Feature: Add storage pools isolation per project

### ISSUE THREAD

**Issue by tregubovav-dev** [lxc/incus#976]
# Issue 

Currently `LXD` and `Incus` do not allow to restrict storage pool usage per project basis. That means any project can create instances, volumes and/or backets on any storage pools in the cluster. Multiple use-cases may require more granular resources isolation per project.

# Feature request
I would like to offer adding more options to the `features.storage.*` options set:
- `features.storage.default` - this is default storage in the project which will be used for deploying `rootfs`s if it's not overwritten in instance or profile configuration.
- `features.storage.allowed` - list of storage pools allowed to use in this project.

**Comment by stgraber** [comment]
Closing as we already have an issue in progress to resolve this.
